// Conformance: every registry entry's `config` must describe the tier that
// actually plays.
//
// WHY this test exists. `EngineDefinition.config` and `configHash` are catalog
// metadata: TypeScript reads only `config.kind` (to route a move), so every
// other field is unchecked prose that nothing executes. They are written to
// `engine_versions` and snapshotted per game into `eve_games`
// (white_config_hash / white_play_signature, engine-runner.ts), which makes
// them the ONLY record of what settings played a given game. A field nobody
// reads and nobody checks drifts silently, and it did: on 2026-09-06
// `misty-jungle-flip` still claimed 512K nodes / 2500ms under the day-one hash
// `misty-jungle-flip-0.1.0` while the live tier ran 2.5M nodes / 5000ms on
// binary v0.5.1, and `misty-banqi` claimed `movetime_ms: 1500` — a number that
// had never been any tier's setting — with no node budget recorded at all.
//
// The rule this enforces: a `(configHash, config)` pair is IMMUTABLE once
// shipped. When a tier moves, the registry entry's config moves with it AND the
// hash bumps, so old game rows keep pointing at the settings that really ran.
// Editing config in place under a stable hash is the failure mode — it makes
// every past game retroactively claim the new settings.
//
// Table-driven on purpose: the cases are generated by mapping over each
// family's live tier list, so a NEW tier is covered the moment it is added,
// with nobody having to remember this file. The coverage assertion at the
// bottom closes the other direction — a new registry entry in a tier-backed
// config family must be either checked here or explicitly exempted.

import assert from 'node:assert/strict';
import test from 'node:test';
import { BANQI_ENGINE_VERSION, BANQI_PLAYABLE_ENGINES } from './banqi-engine.js';
import { type EngineConfig, knownEngineIds, loadEngine } from './engine-registry.js';
import { JIEQI_PLAYABLE_ENGINES } from './jieqi-engine.js';
import { JUNGLE_FLIP_ENGINE_VERSION, JUNGLE_FLIP_PLAYABLE_ENGINES } from './jungle-flip-engine.js';

type TierSyncCase = {
  /** Which tier table this expectation was derived from, for the failure message. */
  family: string;
  engineId: string;
  config: EngineConfig;
};

// Each block restates the tier -> catalog mapping INDEPENDENTLY of the registry.
// That is the point: for the families the registry generates from their tier
// list (see the exemptions below) a row here would only echo the generator, so
// only the hand-written entries are covered.
const TIER_SYNC_CASES: readonly TierSyncCase[] = [
  ...JIEQI_PLAYABLE_ENGINES.map(
    (tier): TierSyncCase => ({
      family: 'jieqi',
      engineId: tier.id,
      config: {
        kind: 'pikafish',
        movetime_ms: tier.movetimeMs,
        // Absent on the top tier, which runs uncapped depth.
        ...(tier.depth === undefined ? {} : { depth: tier.depth }),
      },
    }),
  ),
  ...BANQI_PLAYABLE_ENGINES.map(
    (tier): TierSyncCase => ({
      family: 'banqi',
      engineId: tier.id,
      config: { kind: 'banqi-uci', nodes: tier.nodes, movetime_ms: tier.movetimeCapMs },
    }),
  ),
  ...JUNGLE_FLIP_PLAYABLE_ENGINES.map(
    (tier): TierSyncCase => ({
      family: 'jungle-flip',
      engineId: tier.id,
      config: { kind: 'jungle-flip-uci', nodes: tier.nodes, movetime_ms: tier.movetimeCapMs },
    }),
  ),
];

test('registry config matches the live tier it claims to describe', () => {
  assert.ok(TIER_SYNC_CASES.length > 0, 'tier tables produced no cases — check the imports');
  for (const { family, engineId, config } of TIER_SYNC_CASES) {
    const engine = loadEngine(engineId);
    assert.deepEqual(
      engine.config,
      config,
      `${engineId} (${family}): registry config has drifted from the live tier. ` +
        'Update the config AND bump configHash/playSignature — never edit config in ' +
        'place under a shipped hash, or past eve_games rows will claim settings that ' +
        'never ran.',
    );
  }
});

test('tier-backed entries sign their config with a single provenance string', () => {
  // configHash and playSignature are two columns of the same claim for these
  // entries; a split would give one game row two different answers to "what
  // played this". (The python-worker engines deliberately differ — there the
  // signature is the engine-repo commit and the hash names the profile.)
  for (const { engineId } of TIER_SYNC_CASES) {
    const engine = loadEngine(engineId);
    assert.equal(engine.configHash, engine.playSignature, `${engineId} hash/signature split`);
  }
});

test('the two single-bot node-budget engines name their build and budget in the hash', () => {
  // These are the entries that drifted. Both are ONE versioned bot whose only
  // strength dial is the node budget, so the hash has to move when either the
  // binary version or the budget moves — otherwise the config can change while
  // the identity stays put, which is exactly the bug this file exists for.
  // Convention borrowed from the pikafish-xiangqi entries:
  // `<engine>-<version>-nodes-<N>`.
  const banqi = loadEngine('misty-banqi');
  assert.equal(
    banqi.configHash,
    `misty-banqi-${BANQI_ENGINE_VERSION}-nodes-${BANQI_PLAYABLE_ENGINES[0].nodes}`,
  );
  const jungleFlip = loadEngine('misty-jungle-flip');
  assert.equal(
    jungleFlip.configHash,
    `misty-jungle-flip-${JUNGLE_FLIP_ENGINE_VERSION}-nodes-${JUNGLE_FLIP_PLAYABLE_ENGINES[0].nodes}`,
  );
});

// Config families whose entries are driven by a tier table somewhere. An entry
// in one of these MUST be covered above or exempted below. 'builtin' and
// 'python-subprocess' are absent on purpose: those engines live in the private
// mistboard-engine repo and have no tier table in this repo to check against —
// their provenance is the `engine_pin` commit, not a local constant.
const TIER_BACKED_CONFIG_KINDS: ReadonlySet<EngineConfig['kind']> = new Set([
  'fairy-stockfish',
  'pikafish',
  'pikafish-xiangqi',
  'banqi-uci',
  'jungle-flip-uci',
]);

// Families the registry GENERATES from their tier list (Object.fromEntries over
// XIANGQI_FSF_PLAYABLE_ENGINES / XIANGQI_ALL_ENGINE_TIERS). Drift is
// structurally impossible there, and a case above would restate the generator
// rather than check it.
const GENERATED_FROM_TIER_TABLE: ReadonlySet<string> = new Set([
  'fairy-stockfish-xiangqi',
  'pikafish-xiangqi',
]);

// Retired entries kept only so old game records still resolve through
// isKnownEngineClientId. They describe configs that really did run (banqi was
// three movetime-only difficulty tiers until 2026-06-18) and have no live tier
// to track. They must NOT be refreshed when the surviving bot's tier moves —
// that would be the in-place edit this whole file is against.
const RETIRED_NO_LIVE_TIER: ReadonlyMap<string, string> = new Map([
  ['misty-banqi-amateur', 'retired 2026-06-18 when banqi collapsed to one node-budgeted bot'],
  ['misty-banqi-strong', 'retired 2026-06-18 when banqi collapsed to one node-budgeted bot'],
  ['misty-banqi-strongest', 'retired 2026-06-18 when banqi collapsed to one node-budgeted bot'],
]);

test('every tier-backed registry entry is either checked or explicitly exempt', () => {
  const covered = new Set(TIER_SYNC_CASES.map((entry) => entry.engineId));
  const unaccounted: string[] = [];
  for (const engineId of knownEngineIds()) {
    const engine = loadEngine(engineId);
    if (!TIER_BACKED_CONFIG_KINDS.has(engine.config.kind)) continue;
    if (covered.has(engineId)) continue;
    if (GENERATED_FROM_TIER_TABLE.has(engine.engineId)) continue;
    if (RETIRED_NO_LIVE_TIER.has(engineId)) continue;
    unaccounted.push(engineId);
  }
  assert.deepEqual(
    unaccounted,
    [],
    'these engines have a tier-backed config kind but nothing checks them against a live ' +
      'tier. Add them to TIER_SYNC_CASES, or to one of the exemption sets with a reason.',
  );
});
