// Generated by scripts/gen-anti-diagrams.mts in this repository (--blog).
// Do not hand-edit: the positions are replayed through the anti-xiangqi rule
// kernel there (scripts/variant-lab/lab/variants/anti-xiangqi.ts on
// packages/game/src/xiangqi-rule-kernel.ts) and asserted before they are
// written out, so a rules change redraws these boards instead of leaving them
// quietly wrong. Drawn with the shared xiangqi diagram toolkit so they follow
// the reader's board and piece pickers like every other xiangqi figure.

import type { XiangqiPiece, XiangqiSquare } from '@mistboard/game';
import {
  activeXiangqiPieceSet,
  XQ_BOARD_H,
  XQ_BOARD_W,
  xqBoardSvg,
  xqSvg,
  xqVisionDemoState,
} from './articles/diagrams.js';
import { renderXiangqiPieceGlyphed } from './xiangqi-piece-sets.js';

type Board = Partial<Record<XiangqiSquare, XiangqiPiece>>;

const PAIR_W = XQ_BOARD_W * 2 + 28;
const PAIR_GAP_X = XQ_BOARD_W + 28;
const FIGURE_H = XQ_BOARD_H + 34;

/** After 1. Cxb10: Black to move, and the kernel says these are the only two captures. */
export const ANTI_AFTER_1: Board = {
  a1: { color: 'red', role: 'chariot' },
  a10: { color: 'black', role: 'chariot' },
  a4: { color: 'red', role: 'soldier' },
  a7: { color: 'black', role: 'soldier' },
  b1: { color: 'red', role: 'horse' },
  b10: { color: 'red', role: 'cannon' },
  b8: { color: 'black', role: 'cannon' },
  c1: { color: 'red', role: 'elephant' },
  c10: { color: 'black', role: 'elephant' },
  c4: { color: 'red', role: 'soldier' },
  c7: { color: 'black', role: 'soldier' },
  d1: { color: 'red', role: 'advisor' },
  d10: { color: 'black', role: 'advisor' },
  e1: { color: 'red', role: 'general' },
  e10: { color: 'black', role: 'general' },
  e4: { color: 'red', role: 'soldier' },
  e7: { color: 'black', role: 'soldier' },
  f1: { color: 'red', role: 'advisor' },
  f10: { color: 'black', role: 'advisor' },
  g1: { color: 'red', role: 'elephant' },
  g10: { color: 'black', role: 'elephant' },
  g4: { color: 'red', role: 'soldier' },
  g7: { color: 'black', role: 'soldier' },
  h1: { color: 'red', role: 'horse' },
  h10: { color: 'black', role: 'horse' },
  h3: { color: 'red', role: 'cannon' },
  h8: { color: 'black', role: 'cannon' },
  i1: { color: 'red', role: 'chariot' },
  i10: { color: 'black', role: 'chariot' },
  i4: { color: 'red', role: 'soldier' },
  i7: { color: 'black', role: 'soldier' },
};
/** After 1. Cxb10 Cxh1 2. Rxh1 Rxb10: the ending both sides reach, Red to move. */
export const ANTI_SURVIVOR: Board = {
  a1: { color: 'red', role: 'chariot' },
  a4: { color: 'red', role: 'soldier' },
  a7: { color: 'black', role: 'soldier' },
  b1: { color: 'red', role: 'horse' },
  b10: { color: 'black', role: 'chariot' },
  b8: { color: 'black', role: 'cannon' },
  c1: { color: 'red', role: 'elephant' },
  c10: { color: 'black', role: 'elephant' },
  c4: { color: 'red', role: 'soldier' },
  c7: { color: 'black', role: 'soldier' },
  d1: { color: 'red', role: 'advisor' },
  d10: { color: 'black', role: 'advisor' },
  e1: { color: 'red', role: 'general' },
  e10: { color: 'black', role: 'general' },
  e4: { color: 'red', role: 'soldier' },
  e7: { color: 'black', role: 'soldier' },
  f1: { color: 'red', role: 'advisor' },
  f10: { color: 'black', role: 'advisor' },
  g1: { color: 'red', role: 'elephant' },
  g10: { color: 'black', role: 'elephant' },
  g4: { color: 'red', role: 'soldier' },
  g7: { color: 'black', role: 'soldier' },
  h1: { color: 'red', role: 'chariot' },
  h10: { color: 'black', role: 'horse' },
  h3: { color: 'red', role: 'cannon' },
  i10: { color: 'black', role: 'chariot' },
  i4: { color: 'red', role: 'soldier' },
  i7: { color: 'black', role: 'soldier' },
};
/** After 1. Cxb10 Cxh1 2. Cxd10 Kxd10 3. Rxh1: its cousin, Black to move. */
export const ANTI_COUSIN: Board = {
  a1: { color: 'red', role: 'chariot' },
  a10: { color: 'black', role: 'chariot' },
  a4: { color: 'red', role: 'soldier' },
  a7: { color: 'black', role: 'soldier' },
  b1: { color: 'red', role: 'horse' },
  b8: { color: 'black', role: 'cannon' },
  c1: { color: 'red', role: 'elephant' },
  c10: { color: 'black', role: 'elephant' },
  c4: { color: 'red', role: 'soldier' },
  c7: { color: 'black', role: 'soldier' },
  d1: { color: 'red', role: 'advisor' },
  d10: { color: 'black', role: 'general' },
  e1: { color: 'red', role: 'general' },
  e4: { color: 'red', role: 'soldier' },
  e7: { color: 'black', role: 'soldier' },
  f1: { color: 'red', role: 'advisor' },
  f10: { color: 'black', role: 'advisor' },
  g1: { color: 'red', role: 'elephant' },
  g10: { color: 'black', role: 'elephant' },
  g4: { color: 'red', role: 'soldier' },
  g7: { color: 'black', role: 'soldier' },
  h1: { color: 'red', role: 'chariot' },
  h10: { color: 'black', role: 'horse' },
  h3: { color: 'red', role: 'cannon' },
  i10: { color: 'black', role: 'chariot' },
  i4: { color: 'red', role: 'soldier' },
  i7: { color: 'black', role: 'soldier' },
};
/** The 2M self-play game at ply 35: nothing left that can ever capture. */
export const ANTI_DEAD: Board = {
  c10: { color: 'black', role: 'elephant' },
  d10: { color: 'black', role: 'advisor' },
  e1: { color: 'red', role: 'general' },
  e10: { color: 'black', role: 'general' },
  e2: { color: 'red', role: 'advisor' },
  e9: { color: 'black', role: 'advisor' },
};

export const ANTI_XIANGQI_DECISION = () =>
  xqSvg(
    PAIR_W,
    FIGURE_H,
    xqBoardSvg({
      state: xqVisionDemoState('anti-after-1', ANTI_AFTER_1),
      x: PAIR_GAP_X / 2,
      y: 0,
      label: 'AFTER 1. Cxb10: BLACK MUST CAPTURE',
      perspective: 'red',
      arrows: [
        { from: 'a10' as XiangqiSquare, to: 'b10' as XiangqiSquare },
        { from: 'h8' as XiangqiSquare, to: 'h1' as XiangqiSquare },
      ],
    }),
  );

export const ANTI_XIANGQI_SURVIVORS = () =>
  xqSvg(
    PAIR_W,
    FIGURE_H,
    [
      xqBoardSvg({
        state: xqVisionDemoState('anti-survivor', ANTI_SURVIVOR),
        x: 0,
        y: 0,
        label: '2. Rxh1 Rxb10: RED TO MOVE',
        perspective: 'red',
      }),
      xqBoardSvg({
        state: xqVisionDemoState('anti-cousin', ANTI_COUSIN),
        x: PAIR_GAP_X,
        y: 0,
        label: '2. Cxd10 Kxd10 3. Rxh1: BLACK TO MOVE',
        perspective: 'red',
      }),
    ].join(''),
  );

export const ANTI_XIANGQI_DEAD = () =>
  xqSvg(
    PAIR_W,
    FIGURE_H,
    xqBoardSvg({
      state: xqVisionDemoState('anti-dead', ANTI_DEAD),
      x: PAIR_GAP_X / 2,
      y: 0,
      label: 'PLY 35 OF THE 2M GAME: A DEAD BOARD',
      perspective: 'red',
      zones: true,
    }),
  );

// The card: both generals in their discs, upside down. In this game they are
// ordinary pieces and everyone is trying to lose.
const THUMB_W = 160;
const THUMB_H = 100;
const THUMB_SIZE = 74;

export const ANTI_XIANGQI_THUMBNAIL = () => {
  const gap = Math.round(THUMB_SIZE * 0.06);
  const x0 = (THUMB_W - (THUMB_SIZE * 2 + gap)) / 2;
  const y = (THUMB_H - THUMB_SIZE) / 2;
  const disc = (color: 'red' | 'black', x: number) =>
    `<g transform="rotate(180 ${x + THUMB_SIZE / 2} ${y + THUMB_SIZE / 2})">${renderXiangqiPieceGlyphed({ role: 'general', color }, activeXiangqiPieceSet, { x, y, size: THUMB_SIZE })}</g>`;
  return [
    `<svg class="xq-article-svg" viewBox="0 0 ${THUMB_W} ${THUMB_H}" role="img" aria-label="Anti Xiangqi" xmlns="http://www.w3.org/2000/svg">`,
    disc('red', x0),
    disc('black', x0 + THUMB_SIZE + gap),
    '</svg>',
  ].join('');
};
