// Generated by scripts/gen-anti-diagrams.mts in this repository (--site).
// Do not hand-edit: the positions are replayed through the anti-xiangqi rule
// kernel there (scripts/variant-lab/lab/variants/anti-xiangqi.ts on
// packages/game/src/xiangqi-rule-kernel.ts) and asserted before they are
// written out, so a rules change redraws these boards instead of leaving them
// quietly wrong. Drawn with the shared xiangqi diagram toolkit so they follow
// the reader's board and piece pickers like every other xiangqi figure.

import type { XiangqiPiece, XiangqiSquare } from '@mistboard/game';
import {
  activeXiangqiPieceSet,
  XQ_BOARD_H,
  XQ_BOARD_W,
  xqBoardSvg,
  xqSvg,
  xqVisionDemoState,
} from './articles/diagrams.js';
import { renderXiangqiPieceGlyphed } from './xiangqi-piece-sets.js';

type Board = Partial<Record<XiangqiSquare, XiangqiPiece>>;

const PAIR_W = XQ_BOARD_W * 2 + 28;
const PAIR_GAP_X = XQ_BOARD_W + 28;
const FIGURE_H = XQ_BOARD_H + 34;

/** The array. Every stepper below replays from here. */
export const ANTI_START: Board = {
  a1: { color: 'red', role: 'chariot' },
  a10: { color: 'black', role: 'chariot' },
  a4: { color: 'red', role: 'soldier' },
  a7: { color: 'black', role: 'soldier' },
  b1: { color: 'red', role: 'horse' },
  b10: { color: 'black', role: 'horse' },
  b3: { color: 'red', role: 'cannon' },
  b8: { color: 'black', role: 'cannon' },
  c1: { color: 'red', role: 'elephant' },
  c10: { color: 'black', role: 'elephant' },
  c4: { color: 'red', role: 'soldier' },
  c7: { color: 'black', role: 'soldier' },
  d1: { color: 'red', role: 'advisor' },
  d10: { color: 'black', role: 'advisor' },
  e1: { color: 'red', role: 'general' },
  e10: { color: 'black', role: 'general' },
  e4: { color: 'red', role: 'soldier' },
  e7: { color: 'black', role: 'soldier' },
  f1: { color: 'red', role: 'advisor' },
  f10: { color: 'black', role: 'advisor' },
  g1: { color: 'red', role: 'elephant' },
  g10: { color: 'black', role: 'elephant' },
  g4: { color: 'red', role: 'soldier' },
  g7: { color: 'black', role: 'soldier' },
  h1: { color: 'red', role: 'horse' },
  h10: { color: 'black', role: 'horse' },
  h3: { color: 'red', role: 'cannon' },
  h8: { color: 'black', role: 'cannon' },
  i1: { color: 'red', role: 'chariot' },
  i10: { color: 'black', role: 'chariot' },
  i4: { color: 'red', role: 'soldier' },
  i7: { color: 'black', role: 'soldier' },
};
/** After 1. Cxb10 Cxh1 2. Rxh1 Rxb10: the ending both sides reach, Red to move. */
export const ANTI_SURVIVOR: Board = {
  a1: { color: 'red', role: 'chariot' },
  a4: { color: 'red', role: 'soldier' },
  a7: { color: 'black', role: 'soldier' },
  b1: { color: 'red', role: 'horse' },
  b10: { color: 'black', role: 'chariot' },
  b8: { color: 'black', role: 'cannon' },
  c1: { color: 'red', role: 'elephant' },
  c10: { color: 'black', role: 'elephant' },
  c4: { color: 'red', role: 'soldier' },
  c7: { color: 'black', role: 'soldier' },
  d1: { color: 'red', role: 'advisor' },
  d10: { color: 'black', role: 'advisor' },
  e1: { color: 'red', role: 'general' },
  e10: { color: 'black', role: 'general' },
  e4: { color: 'red', role: 'soldier' },
  e7: { color: 'black', role: 'soldier' },
  f1: { color: 'red', role: 'advisor' },
  f10: { color: 'black', role: 'advisor' },
  g1: { color: 'red', role: 'elephant' },
  g10: { color: 'black', role: 'elephant' },
  g4: { color: 'red', role: 'soldier' },
  g7: { color: 'black', role: 'soldier' },
  h1: { color: 'red', role: 'chariot' },
  h10: { color: 'black', role: 'horse' },
  h3: { color: 'red', role: 'cannon' },
  i10: { color: 'black', role: 'chariot' },
  i4: { color: 'red', role: 'soldier' },
  i7: { color: 'black', role: 'soldier' },
};
/** After 1. Cxb10 Cxh1 2. Cxd10 Kxd10 3. Rxh1: its cousin, Black to move. */
export const ANTI_COUSIN: Board = {
  a1: { color: 'red', role: 'chariot' },
  a10: { color: 'black', role: 'chariot' },
  a4: { color: 'red', role: 'soldier' },
  a7: { color: 'black', role: 'soldier' },
  b1: { color: 'red', role: 'horse' },
  b8: { color: 'black', role: 'cannon' },
  c1: { color: 'red', role: 'elephant' },
  c10: { color: 'black', role: 'elephant' },
  c4: { color: 'red', role: 'soldier' },
  c7: { color: 'black', role: 'soldier' },
  d1: { color: 'red', role: 'advisor' },
  d10: { color: 'black', role: 'general' },
  e1: { color: 'red', role: 'general' },
  e4: { color: 'red', role: 'soldier' },
  e7: { color: 'black', role: 'soldier' },
  f1: { color: 'red', role: 'advisor' },
  f10: { color: 'black', role: 'advisor' },
  g1: { color: 'red', role: 'elephant' },
  g10: { color: 'black', role: 'elephant' },
  g4: { color: 'red', role: 'soldier' },
  g7: { color: 'black', role: 'soldier' },
  h1: { color: 'red', role: 'chariot' },
  h10: { color: 'black', role: 'horse' },
  h3: { color: 'red', role: 'cannon' },
  i10: { color: 'black', role: 'chariot' },
  i4: { color: 'red', role: 'soldier' },
  i7: { color: 'black', role: 'soldier' },
};
/** The 2M self-play game at ply 35: nothing left that can ever capture. */
export const ANTI_DEAD: Board = {
  c10: { color: 'black', role: 'elephant' },
  d10: { color: 'black', role: 'advisor' },
  e1: { color: 'red', role: 'general' },
  e10: { color: 'black', role: 'general' },
  e2: { color: 'red', role: 'advisor' },
  e9: { color: 'black', role: 'advisor' },
};

// ── Steppers ──────────────────────────────────────────────────────────────
// A line is [from, to, narrative] per ply. Nothing in this game moves more
// than one piece, so a frame is the previous board with one piece moved; the
// generator checked that against the kernel at every ply. A narrative is the
// game's note on that ply, or plain move notation where there is none.
type Line = ReadonlyArray<readonly [string, string, string]>;

/** The 2M self-play game, mirrored into the 1. Cxb10 frame: dead at ply 35, drawn at 44. */
export const ANTI_GAME_2M: Line = [
  [
    'b3',
    'b10',
    'Cannon takes the horse over Black’s cannon. Red’s only two legal moves are this and its mirror image.',
  ],
  [
    'h8',
    'h1',
    'Black declines the chariot recapture, a proven loss, and fires the other cannon down the h-file with Red’s h3 cannon as the screen. The only move that holds.',
  ],
  [
    'i1',
    'h1',
    'The chariot takes the cannon. Continuing with 2. Cxd10, the other cannon capture, would also hold.',
  ],
  [
    'a10',
    'b10',
    'Black’s only legal move. The forced part is over: fourteen pieces each, Red to move, no capture on the board.',
  ],
  [
    'h3',
    'b3',
    'The first free move of the game. Red puts its last cannon on b3, where it screens Black’s b8 cannon onto the b1 horse: an offer Black cannot refuse.',
  ],
  ['b8', 'b1', 'Only legal move.'],
  [
    'a1',
    'b1',
    'The same exchange on the other wing: chariot takes cannon, and Rxb3 will be forced in reply.',
  ],
  ['b10', 'b3', '4... Rxb3 (b10→b3)'],
  [
    'h1',
    'h10',
    'Both chariots are now loose on the back ranks with nothing but captures available. For the next fourteen plies each chariot has only captures to make, and the two sides shed material in step.',
  ],
  ['b3', 'b1', '5... Rxb1 (b3→b1)'],
  ['h10', 'g10', '6. Rxg10 (h10→g10)'],
  ['b1', 'c1', '6... Rxc1 (b1→c1)'],
  ['g10', 'g7', '7. Rxg7 (g10→g7)'],
  ['c1', 'c4', '7... Rxc4 (c1→c4)'],
  ['g7', 'e7', '8. Rxe7 (g7→e7)'],
  ['c4', 'e4', '8... Rxe4 (c4→e4)'],
  ['e7', 'c7', '9. Rxc7 (e7→c7)'],
  ['e4', 'g4', '9... Rxg4 (e4→g4)'],
  ['c7', 'i7', '10. Rxi7 (c7→i7)'],
  ['g4', 'i4', '10... Rxi4 (g4→i4)'],
  ['i7', 'a7', '11. Rxa7 (i7→a7)'],
  ['i4', 'a4', '11... Rxa4 (i4→a4)'],
  [
    'a7',
    'a4',
    'The last capture of the feast. Five pieces each: general, two advisors, an elephant, one chariot.',
  ],
  ['f10', 'e9', '12... Afe9 (f10→e9)'],
  ['a4', 'b4', '13. Rb4 (a4→b4)'],
  ['i10', 'i8', '13... Ri8 (i10→i8)'],
  [
    'g1',
    'i3',
    'Red pulls the lever. The elephant steps to i3, on Black’s chariot’s file, where Black has no other capture: Rxi3 is compelled.',
  ],
  ['i8', 'i3', '14... Rxi3 (i8→i3)'],
  ['b4', 'b2', '15. Rb2 (b4→b2)'],
  ['i3', 'i8', '15... Ri8 (i3→i8)'],
  [
    'b2',
    'i2',
    'The chariot itself: Ri2, and Black must take it. Red now has nothing that can leave the palace.',
  ],
  ['i8', 'i2', '16... Rxi2 (i8→i2)'],
  [
    'f1',
    'e2',
    'The advisor steps into the chariot’s path. Black must take, and Red’s other advisor must take back.',
  ],
  ['i2', 'e2', '17... Rxe2 (i2→e2)'],
  [
    'd1',
    'e2',
    'Red: general and one advisor. Black: general, two advisors, an elephant. Nothing on the board can ever capture anything again.',
  ],
  ['c10', 'e8', '18... Ee8 (c10→e8)'],
  ['e2', 'f1', '19. Af1 (e2→f1)'],
  ['e9', 'd8', '19... Ad8 (e9→d8)'],
  ['f1', 'e2', '20. Ae2 (f1→e2)'],
  ['d8', 'e9', '20... Ade9 (d8→e9)'],
  ['e2', 'f1', '21. Af1 (e2→f1)'],
  ['e9', 'd8', '21... Ad8 (e9→d8)'],
  ['f1', 'e2', '22. Ae2 (f1→e2)'],
  [
    'd8',
    'e9',
    'Third occurrence of the position: draw by repetition. Red has fewer pieces and no way to lose them; Black has no way to make Red take anything.',
  ],
];
/** The 5M self-play game, mirrored the same way: the soldier war, drawn at ply 131. */
export const ANTI_GAME_5M: Line = [
  ['b3', 'b10', '1. Cxb10 (b3→b10)'],
  ['h8', 'h1', '1... Cxh1 (h8→h1)'],
  ['i1', 'h1', '2. Rxh1 (i1→h1)'],
  ['a10', 'b10', 'The same four forced plies as every game.'],
  ['h3', 'b3', '3. Cb3 (h3→b3)'],
  ['b8', 'b1', '3... Cxb1 (b8→b1)'],
  ['h1', 'h10', '4. Rxh10 (h1→h10)'],
  ['i10', 'h10', '4... Rxh10 (i10→h10)'],
  ['a1', 'b1', '5. Rxb1 (a1→b1)'],
  ['b10', 'b3', '5... Rxb3 (b10→b3)'],
  [
    'b1',
    'b3',
    'The chariots take each other’s cannons and Red’s chariot is taken in turn: eleven pieces each, and the game becomes a soldier war.',
  ],
  ['h10', 'i10', '6... Ri10 (h10→i10)'],
  ['f1', 'e2', '7. Afe2 (f1→e2)'],
  ['f10', 'e9', '7... Afe9 (f10→e9)'],
  [
    'i4',
    'i5',
    'Red offers a soldier on i5. Black answers with a soldier on i6: now Red’s soldier must take it, and Black’s chariot must take back.',
  ],
  ['i7', 'i6', '8... Pi6 (i7→i6)'],
  ['i5', 'i6', '9. Pxi6 (i5→i6)'],
  [
    'i10',
    'i6',
    'Two soldiers off in two compelled captures. This is the trade the rest of the game is made of: a soldier steps into another’s path, the capture is compelled, and the capturer is taken in turn.',
  ],
  ['b3', 'a3', '10. Ra3 (b3→a3)'],
  ['i6', 'i8', '10... Ri8 (i6→i8)'],
  ['g4', 'g5', '11. Pg5 (g4→g5)'],
  ['a7', 'a6', '11... Pa6 (a7→a6)'],
  ['e4', 'e5', '12. Pe5 (e4→e5)'],
  ['a6', 'a5', '12... Pa5 (a6→a5)'],
  ['a4', 'a5', '13. Pxa5 (a4→a5)'],
  ['i8', 'c8', '13... Rc8 (i8→c8)'],
  ['a5', 'a6', '14. Pa6 (a5→a6)'],
  ['g10', 'e8', '14... Ege8 (g10→e8)'],
  ['a3', 'c3', '15. Rc3 (a3→c3)'],
  ['e7', 'e6', '15... Pe6 (e7→e6)'],
  ['e5', 'e6', '16. Pxe6 (e5→e6)'],
  ['c8', 'c9', '16... Rc9 (c8→c9)'],
  ['a6', 'b6', '17. Pb6 (a6→b6)'],
  ['e9', 'f8', '17... Af8 (e9→f8)'],
  ['g5', 'g6', '18. Pg6 (g5→g6)'],
  ['g7', 'g6', '18... Pxg6 (g7→g6)'],
  ['b6', 'c6', '19. Pc6 (b6→c6)'],
  [
    'e8',
    'c6',
    'A soldier taken by a soldier, then a soldier taken by an elephant. Material keeps coming off in pairs, and every capture is one the taker could not refuse.',
  ],
  ['c1', 'e3', '20. Ece3 (c1→e3)'],
  ['c10', 'e8', '20... Ece8 (c10→e8)'],
  ['c3', 'c2', '21. Rc2 (c3→c2)'],
  ['c6', 'a8', '21... Ea8 (c6→a8)'],
  ['e2', 'f3', '22. Af3 (e2→f3)'],
  ['c9', 'f9', '22... Rf9 (c9→f9)'],
  ['d1', 'e2', '23. Ade2 (d1→e2)'],
  ['c7', 'c6', '23... Pc6 (c7→c6)'],
  ['c4', 'c5', '24. Pc5 (c4→c5)'],
  ['c6', 'c5', '24... Pxc5 (c6→c5)'],
  ['e3', 'c5', '25. Exc5 (e3→c5)'],
  ['g6', 'g5', '25... Pg5 (g6→g5)'],
  ['c2', 'c1', '26. Rc1 (c2→c1)'],
  ['a8', 'c6', '26... Eac6 (a8→c6)'],
  ['c1', 'c2', '27. Rc2 (c1→c2)'],
  ['f9', 'c9', '27... Rc9 (f9→c9)'],
  ['e2', 'd3', '28. Ad3 (e2→d3)'],
  ['d10', 'e9', '28... Ade9 (d10→e9)'],
  ['e1', 'e2', '29. Ke2 (e1→e2)'],
  ['e8', 'g6', '29... Eg6 (e8→g6)'],
  ['c2', 'c1', '30. Rc1 (c2→c1)'],
  ['e10', 'd10', '30... Kd10 (e10→d10)'],
  ['c1', 'c2', '31. Rc2 (c1→c2)'],
  ['d10', 'd9', '31... Kd9 (d10→d9)'],
  ['c2', 'c3', '32. Rc3 (c2→c3)'],
  ['g5', 'f5', '32... Pf5 (g5→f5)'],
  ['e2', 'e3', '33. Ke3 (e2→e3)'],
  ['g6', 'e8', '33... Ege8 (g6→e8)'],
  ['f3', 'e2', '34. Afe2 (f3→e2)'],
  ['f5', 'g5', '34... Pg5 (f5→g5)'],
  ['c3', 'c1', '35. Rc1 (c3→c1)'],
  ['c9', 'c10', '35... Rc10 (c9→c10)'],
  ['c1', 'c2', '36. Rc2 (c1→c2)'],
  ['g5', 'h5', '36... Ph5 (g5→h5)'],
  ['c2', 'c1', '37. Rc1 (c2→c1)'],
  ['c10', 'c8', '37... Rc8 (c10→c8)'],
  ['c1', 'c3', '38. Rc3 (c1→c3)'],
  ['e8', 'g6', '38... Eg6 (e8→g6)'],
  ['c3', 'c1', '39. Rc1 (c3→c1)'],
  ['h5', 'g5', '39... Pg5 (h5→g5)'],
  ['c1', 'c2', '40. Rc2 (c1→c2)'],
  ['c8', 'b8', '40... Rb8 (c8→b8)'],
  ['c2', 'c1', '41. Rc1 (c2→c1)'],
  ['b8', 'c8', '41... Rc8 (b8→c8)'],
  ['c1', 'd1', '42. Rd1 (c1→d1)'],
  ['g5', 'f5', '42... Pf5 (g5→f5)'],
  ['g1', 'i3', '43. Ei3 (g1→i3)'],
  ['f5', 'e5', '43... Pe5 (f5→e5)'],
  ['e6', 'e7', '44. Pe7 (e6→e7)'],
  ['g6', 'e8', '44... Ege8 (g6→e8)'],
  [
    'e7',
    'e8',
    'Black stepped an elephant into the path of Red’s last soldier, giving it up so the soldier lands on e8, where the chariot must take it. Red has no soldiers left.',
  ],
  ['c8', 'e8', '45... Rxe8 (c8→e8)'],
  ['i3', 'g5', '46. Eg5 (i3→g5)'],
  ['e8', 'c8', '46... Rc8 (e8→c8)'],
  ['e3', 'f3', '47. Kf3 (e3→f3)'],
  ['c8', 'c7', '47... Rc7 (c8→c7)'],
  ['g5', 'e3', '48. Ege3 (g5→e3)'],
  ['c7', 'e7', '48... Re7 (c7→e7)'],
  ['d1', 'c1', '49. Rc1 (d1→c1)'],
  ['c6', 'a8', '49... Ea8 (c6→a8)'],
  ['c1', 'c2', '50. Rc2 (c1→c2)'],
  ['e7', 'e6', '50... Re6 (e7→e6)'],
  ['c2', 'c1', '51. Rc1 (c2→c1)'],
  ['e6', 'e7', '51... Re7 (e6→e7)'],
  ['c1', 'i1', '52. Ri1 (c1→i1)'],
  ['a8', 'c6', '52... Ec6 (a8→c6)'],
  ['i1', 'd1', '53. Rd1 (i1→d1)'],
  ['e9', 'f10', '53... Af10 (e9→f10)'],
  ['f3', 'f2', '54. Kf2 (f3→f2)'],
  ['f10', 'e9', '54... Afe9 (f10→e9)'],
  ['f2', 'f3', '55. Kf3 (f2→f3)'],
  ['d9', 'd8', '55... Kd8 (d9→d8)'],
  ['d1', 'f1', '56. Rf1 (d1→f1)'],
  ['e7', 'c7', '56... Rc7 (e7→c7)'],
  ['f1', 'g1', '57. Rg1 (f1→g1)'],
  ['c7', 'c9', '57... Rc9 (c7→c9)'],
  ['g1', 'd1', '58. Rd1 (g1→d1)'],
  ['c9', 'c7', '58... Rc7 (c9→c7)'],
  ['e3', 'g5', '59. Eg5 (e3→g5)'],
  ['e5', 'e4', '59... Pe4 (e5→e4)'],
  ['f3', 'e3', '60. Ke3 (f3→e3)'],
  [
    'e4',
    'e3',
    'Red walks its general into the soldier’s path and Black must take it. Under these rules that is progress for Red; the elephant takes the soldier back, and no soldiers remain.',
  ],
  ['c5', 'e3', '61. Ecxe3 (c5→e3)'],
  [
    'c7',
    'c10',
    'From here nothing can be forced. Black’s chariot sits on the c-file behind its own elephant, on lines none of Red’s remaining pieces can reach; Red’s advisors and elephants cannot leave their half; and either chariot could be thrown away at will. Five pieces each, and the board is as dead as the palace-only one.',
  ],
  ['e3', 'c5', '62. Ec5 (e3→c5)'],
  ['c10', 'c7', '62... Rc7 (c10→c7)'],
  ['g5', 'e3', '63. Ege3 (g5→e3)'],
  ['c7', 'c10', '63... Rc10 (c7→c10)'],
  ['e3', 'g5', '64. Eg5 (e3→g5)'],
  ['c10', 'c7', '64... Rc7 (c10→c7)'],
  ['c5', 'e3', '65. Ece3 (c5→e3)'],
  ['c7', 'c10', '65... Rc10 (c7→c10)'],
  [
    'e3',
    'c5',
    'Third occurrence of the position: draw by repetition, five pieces each, both sides shuffling an elephant and a chariot.',
  ],
];
/** The main line of the certificate that 1...Rxb10 loses (1,864 positions in all). */
export const ANTI_PROOF_LINE: Line = [
  ['b3', 'b10', '1. Cxb10 (b3→b10)'],
  [
    'a10',
    'b10',
    'The natural recapture. From here Red wins by force; the certificate covers 1,864 positions.',
  ],
  ['h3', 'h10', '2. Cxh10 (h3→h10)'],
  ['i10', 'h10', '2... Rxh10 (i10→h10)'],
  [
    'a1',
    'a2',
    'Red’s first free move is quiet: the chariot steps to a2. Black has 42 legal replies and the certificate answers each one. This is the main line.',
  ],
  ['h10', 'h9', '3... Rh9 (h10→h9)'],
  [
    'a2',
    'b2',
    'The chariot to b2, with the b8 cannon now screened onto the b1 horse. Black has exactly one legal move.',
  ],
  ['b8', 'b1', '4... Cxb1 (b8→b1)'],
  ['b2', 'b1', 'Red must take the cannon.'],
  ['b10', 'b1', 'Black must take the chariot: the whole b-file is open.'],
  ['e1', 'e2', 'A quiet move that leaves Black’s chariot exactly one capture, the elephant on c1.'],
  ['b1', 'c1', '6... Rxc1 (b1→c1)'],
  ['g1', 'i3', '7. Ei3 (g1→i3)'],
  ['c1', 'c4', 'The elephant steps to i3, into the chariot’s reach; two replies, both covered.'],
  ['a4', 'a5', '8. Pa5 (a4→a5)'],
  ['c4', 'e4', '8... Rxe4 (c4→e4)'],
  ['e2', 'f2', '9. Kf2 (e2→f2)'],
  ['e4', 'g4', '9... Rxg4 (e4→g4)'],
  ['d1', 'e2', '10. Ade2 (d1→e2)'],
  ['g4', 'i4', '10... Rxi4 (g4→i4)'],
  ['i3', 'g5', '11. Eg5 (i3→g5)'],
  ['i4', 'i1', '11... Rxi1 (i4→i1)'],
  ['e2', 'f3', '12. Af3 (e2→f3)'],
  ['i1', 'h1', '12... Rxh1 (i1→h1)'],
  ['f2', 'e2', '13. Ke2 (f2→e2)'],
  ['h1', 'f1', '13... Rxf1 (h1→f1)'],
  ['e2', 'f2', '14. Kf2 (e2→f2)'],
  ['f1', 'f2', '14... Rxf2 (f1→f2)'],
  ['f3', 'e2', '15. Ae2 (f3→e2)'],
  ['f2', 'e2', '15... Rxe2 (f2→e2)'],
  ['a5', 'a6', '16. Pa6 (a5→a6)'],
  ['a7', 'a6', '16... Pxa6 (a7→a6)'],
  ['g5', 'e3', '17. Ee3 (g5→e3)'],
  [
    'e2',
    'e3',
    'Red has no pieces left and has won. Black could not decline a single capture along the way.',
  ],
];

const SINGLE_H = XQ_BOARD_H + 8;

function antiFrame(id: string, board: Board, from?: string, to?: string): () => string {
  return () =>
    xqSvg(
      XQ_BOARD_W,
      SINGLE_H,
      xqBoardSvg({
        state: xqVisionDemoState(id, board),
        x: 0,
        y: -24,
        label: '',
        perspective: 'red',
        arrows: from && to ? [{ from: from as XiangqiSquare, to: to as XiangqiSquare }] : undefined,
      }),
    );
}

/** One stepper frame per ply, opening on the array. */
export function antiSteps(
  id: string,
  line: Line,
  start?: string,
): Array<{ svg: () => string; narrative?: string }> {
  let board: Board = { ...ANTI_START };
  const steps: Array<{ svg: () => string; narrative?: string }> = [
    { svg: antiFrame(`${id}-0`, board), narrative: start },
  ];
  line.forEach(([from, to, narrative], i) => {
    const next: Board = { ...board };
    next[to as XiangqiSquare] = next[from as XiangqiSquare];
    delete next[from as XiangqiSquare];
    board = next;
    steps.push({ svg: antiFrame(`${id}-${i + 1}`, next, from, to), narrative });
  });
  return steps;
}

/** The four forks of the opening chain, an arrow on every capture the side to move has. */
export const ANTI_XIANGQI_FORK_FRAMES: Array<() => string> = [
  () =>
    xqSvg(
      XQ_BOARD_W,
      FIGURE_H,
      xqBoardSvg({
        state: xqVisionDemoState('anti-fork-0', {
          a1: { color: 'red', role: 'chariot' },
          a10: { color: 'black', role: 'chariot' },
          a4: { color: 'red', role: 'soldier' },
          a7: { color: 'black', role: 'soldier' },
          b1: { color: 'red', role: 'horse' },
          b10: { color: 'red', role: 'cannon' },
          b8: { color: 'black', role: 'cannon' },
          c1: { color: 'red', role: 'elephant' },
          c10: { color: 'black', role: 'elephant' },
          c4: { color: 'red', role: 'soldier' },
          c7: { color: 'black', role: 'soldier' },
          d1: { color: 'red', role: 'advisor' },
          d10: { color: 'black', role: 'advisor' },
          e1: { color: 'red', role: 'general' },
          e10: { color: 'black', role: 'general' },
          e4: { color: 'red', role: 'soldier' },
          e7: { color: 'black', role: 'soldier' },
          f1: { color: 'red', role: 'advisor' },
          f10: { color: 'black', role: 'advisor' },
          g1: { color: 'red', role: 'elephant' },
          g10: { color: 'black', role: 'elephant' },
          g4: { color: 'red', role: 'soldier' },
          g7: { color: 'black', role: 'soldier' },
          h1: { color: 'red', role: 'horse' },
          h10: { color: 'black', role: 'horse' },
          h3: { color: 'red', role: 'cannon' },
          h8: { color: 'black', role: 'cannon' },
          i1: { color: 'red', role: 'chariot' },
          i10: { color: 'black', role: 'chariot' },
          i4: { color: 'red', role: 'soldier' },
          i7: { color: 'black', role: 'soldier' },
        }),
        x: 0,
        y: 0,
        label: 'FORK A: BLACK TO MOVE',
        perspective: 'red',
        arrows: [
          { from: 'h8' as XiangqiSquare, to: 'h1' as XiangqiSquare },
          { from: 'a10' as XiangqiSquare, to: 'b10' as XiangqiSquare },
        ],
      }),
    ),
  () =>
    xqSvg(
      XQ_BOARD_W,
      FIGURE_H,
      xqBoardSvg({
        state: xqVisionDemoState('anti-fork-1', {
          a1: { color: 'red', role: 'chariot' },
          a10: { color: 'black', role: 'chariot' },
          a4: { color: 'red', role: 'soldier' },
          a7: { color: 'black', role: 'soldier' },
          b1: { color: 'red', role: 'horse' },
          b10: { color: 'red', role: 'cannon' },
          b8: { color: 'black', role: 'cannon' },
          c1: { color: 'red', role: 'elephant' },
          c10: { color: 'black', role: 'elephant' },
          c4: { color: 'red', role: 'soldier' },
          c7: { color: 'black', role: 'soldier' },
          d1: { color: 'red', role: 'advisor' },
          d10: { color: 'black', role: 'advisor' },
          e1: { color: 'red', role: 'general' },
          e10: { color: 'black', role: 'general' },
          e4: { color: 'red', role: 'soldier' },
          e7: { color: 'black', role: 'soldier' },
          f1: { color: 'red', role: 'advisor' },
          f10: { color: 'black', role: 'advisor' },
          g1: { color: 'red', role: 'elephant' },
          g10: { color: 'black', role: 'elephant' },
          g4: { color: 'red', role: 'soldier' },
          g7: { color: 'black', role: 'soldier' },
          h1: { color: 'black', role: 'cannon' },
          h10: { color: 'black', role: 'horse' },
          h3: { color: 'red', role: 'cannon' },
          i1: { color: 'red', role: 'chariot' },
          i10: { color: 'black', role: 'chariot' },
          i4: { color: 'red', role: 'soldier' },
          i7: { color: 'black', role: 'soldier' },
        }),
        x: 0,
        y: 0,
        label: 'FORK B: RED TO MOVE',
        perspective: 'red',
        arrows: [
          { from: 'i1' as XiangqiSquare, to: 'h1' as XiangqiSquare },
          { from: 'b10' as XiangqiSquare, to: 'd10' as XiangqiSquare },
        ],
      }),
    ),
  () =>
    xqSvg(
      XQ_BOARD_W,
      FIGURE_H,
      xqBoardSvg({
        state: xqVisionDemoState('anti-fork-2', {
          a1: { color: 'red', role: 'chariot' },
          a10: { color: 'black', role: 'chariot' },
          a4: { color: 'red', role: 'soldier' },
          a7: { color: 'black', role: 'soldier' },
          b1: { color: 'red', role: 'horse' },
          b8: { color: 'black', role: 'cannon' },
          c1: { color: 'red', role: 'elephant' },
          c10: { color: 'black', role: 'elephant' },
          c4: { color: 'red', role: 'soldier' },
          c7: { color: 'black', role: 'soldier' },
          d1: { color: 'red', role: 'advisor' },
          d10: { color: 'red', role: 'cannon' },
          e1: { color: 'red', role: 'general' },
          e10: { color: 'black', role: 'general' },
          e4: { color: 'red', role: 'soldier' },
          e7: { color: 'black', role: 'soldier' },
          f1: { color: 'red', role: 'advisor' },
          f10: { color: 'black', role: 'advisor' },
          g1: { color: 'red', role: 'elephant' },
          g10: { color: 'black', role: 'elephant' },
          g4: { color: 'red', role: 'soldier' },
          g7: { color: 'black', role: 'soldier' },
          h1: { color: 'black', role: 'cannon' },
          h10: { color: 'black', role: 'horse' },
          h3: { color: 'red', role: 'cannon' },
          i1: { color: 'red', role: 'chariot' },
          i10: { color: 'black', role: 'chariot' },
          i4: { color: 'red', role: 'soldier' },
          i7: { color: 'black', role: 'soldier' },
        }),
        x: 0,
        y: 0,
        label: 'FORK C: BLACK TO MOVE',
        perspective: 'red',
        arrows: [
          { from: 'h1' as XiangqiSquare, to: 'f1' as XiangqiSquare },
          { from: 'e10' as XiangqiSquare, to: 'd10' as XiangqiSquare },
        ],
      }),
    ),
  () =>
    xqSvg(
      XQ_BOARD_W,
      FIGURE_H,
      xqBoardSvg({
        state: xqVisionDemoState('anti-fork-3', {
          a1: { color: 'red', role: 'chariot' },
          a10: { color: 'black', role: 'chariot' },
          a4: { color: 'red', role: 'soldier' },
          a7: { color: 'black', role: 'soldier' },
          b1: { color: 'red', role: 'horse' },
          b8: { color: 'black', role: 'cannon' },
          c1: { color: 'red', role: 'elephant' },
          c10: { color: 'black', role: 'elephant' },
          c4: { color: 'red', role: 'soldier' },
          c7: { color: 'black', role: 'soldier' },
          d1: { color: 'red', role: 'advisor' },
          d10: { color: 'red', role: 'cannon' },
          e1: { color: 'red', role: 'general' },
          e10: { color: 'black', role: 'general' },
          e4: { color: 'red', role: 'soldier' },
          e7: { color: 'black', role: 'soldier' },
          f1: { color: 'black', role: 'cannon' },
          f10: { color: 'black', role: 'advisor' },
          g1: { color: 'red', role: 'elephant' },
          g10: { color: 'black', role: 'elephant' },
          g4: { color: 'red', role: 'soldier' },
          g7: { color: 'black', role: 'soldier' },
          h10: { color: 'black', role: 'horse' },
          h3: { color: 'red', role: 'cannon' },
          i1: { color: 'red', role: 'chariot' },
          i10: { color: 'black', role: 'chariot' },
          i4: { color: 'red', role: 'soldier' },
          i7: { color: 'black', role: 'soldier' },
        }),
        x: 0,
        y: 0,
        label: 'FORK D: RED TO MOVE',
        perspective: 'red',
        arrows: [
          { from: 'e1' as XiangqiSquare, to: 'f1' as XiangqiSquare },
          { from: 'd10' as XiangqiSquare, to: 'f10' as XiangqiSquare },
          { from: 'd10' as XiangqiSquare, to: 'a10' as XiangqiSquare },
        ],
      }),
    ),
];

/** Fork, capture, value with best play, endings below it, proven endings below it. */
export const ANTI_XIANGQI_FORK_ROWS: string[][] = [
  ['Fork A', '1... Cxh1', 'Draw', '82', '62'],
  ['Fork A', '1... Rxb10', 'Red wins', '1', '1'],
  ['Fork B', '2. Rxh1', 'Draw', '1', '0'],
  ['Fork B', '2. Cxd10', 'Draw', '81', '62'],
  ['Fork C', '2... Cxf1', 'Red wins', '80', '62'],
  ['Fork C', '2... Kxd10', 'Draw', '1', '0'],
  ['Fork D', '3. Kxf1', 'Red wins', '1', '0'],
  ['Fork D', '3. Cxf10', 'Black wins', '58', '44'],
  ['Fork D', '3. Cxa10', 'Draw', '21', '18'],
];

/** Ending ply, side to move first, endings, Red wins, Black wins, stalls (100k sweep). */
export const ANTI_XIANGQI_SWEEP_ROWS: string[][] = [
  ['4', 'Red', '2', '1', '0', '1'],
  ['5', 'Black', '1', '0', '0', '1'],
  ['6 to 12', 'Alternating', '14', '8', '6', '0'],
  ['14', 'Red', '36', '36', '0', '0'],
  ['15', 'Black', '5', '0', '4', '1'],
  ['16', 'Red', '15', '8', '1', '6'],
  ['17', 'Black', '6', '0', '6', '0'],
  ['18', 'Red', '4', '0', '0', '4'],
];

export const ANTI_XIANGQI_SURVIVORS = () =>
  xqSvg(
    PAIR_W,
    FIGURE_H,
    [
      xqBoardSvg({
        state: xqVisionDemoState('anti-survivor', ANTI_SURVIVOR),
        x: 0,
        y: 0,
        label: '2. Rxh1 Rxb10: RED TO MOVE',
        perspective: 'red',
      }),
      xqBoardSvg({
        state: xqVisionDemoState('anti-cousin', ANTI_COUSIN),
        x: PAIR_GAP_X,
        y: 0,
        label: '2. Cxd10 Kxd10 3. Rxh1: BLACK TO MOVE',
        perspective: 'red',
      }),
    ].join(''),
  );

export const ANTI_XIANGQI_DEAD = () =>
  xqSvg(
    PAIR_W,
    FIGURE_H,
    xqBoardSvg({
      state: xqVisionDemoState('anti-dead', ANTI_DEAD),
      x: PAIR_GAP_X / 2,
      y: 0,
      label: 'PLY 35 OF THE 2M GAME: A DEAD BOARD',
      perspective: 'red',
      zones: true,
    }),
  );

// The card: both generals in their discs, upside down. In this game they are
// ordinary pieces and everyone is trying to lose.
const THUMB_W = 160;
const THUMB_H = 100;
const THUMB_SIZE = 74;

export const ANTI_XIANGQI_THUMBNAIL = () => {
  const gap = Math.round(THUMB_SIZE * 0.06);
  const x0 = (THUMB_W - (THUMB_SIZE * 2 + gap)) / 2;
  const y = (THUMB_H - THUMB_SIZE) / 2;
  const disc = (color: 'red' | 'black', x: number) =>
    `<g transform="rotate(180 ${x + THUMB_SIZE / 2} ${y + THUMB_SIZE / 2})">${renderXiangqiPieceGlyphed({ role: 'general', color }, activeXiangqiPieceSet, { x, y, size: THUMB_SIZE })}</g>`;
  return [
    `<svg class="xq-article-svg" viewBox="0 0 ${THUMB_W} ${THUMB_H}" role="img" aria-label="Anti Xiangqi" xmlns="http://www.w3.org/2000/svg">`,
    disc('red', x0),
    disc('black', x0 + THUMB_SIZE + gap),
    '</svg>',
  ].join('');
};
