// Precomputed engine analysis for article boards whose game is not in the
// broadcast archive (2026-10-08). A board with `boardId` reads the archive's
// stored analysis; every other game record on an article reads one of these
// files instead, so every game board on the site draws the same chart from the
// same engine pass (pikafish-xiangqi-analysis@5, the archive's own settings).
//
// The files live in ./articles/analysis/<key>.json, written by
// scripts/article-chart-analysis.mjs. The key is a hash of the record itself
// (start position + moves), not an id on the spec, for two reasons: the player
// pages are regenerated by a script that would drop a hand-added id, and a
// record that changes gets a new key, so a stale series can never be drawn over
// a different game. The coverage test (article-replay-analysis.test.ts) fails
// when an article game has neither a board id nor a file.
//
// The glob is lazy: each file is its own chunk, fetched only when its board
// nears the viewport. What ships with the article code is the list of keys,
// which is also how a board knows, before any fetch, whether it has a chart.

import type { XiangqiGameAnalysisResponse } from './review/game-analysis.js';

type AnalysisLoader = () => Promise<XiangqiGameAnalysisResponse>;

const FILES = import.meta.glob<XiangqiGameAnalysisResponse>('./articles/analysis/*.json', {
  import: 'default',
});

const LOADERS = new Map<string, AnalysisLoader>(
  Object.entries(FILES).map(([path, load]) => [
    path.slice(path.lastIndexOf('/') + 1, -'.json'.length),
    load,
  ]),
);

/** The record a key is computed from: start position (if any) and the moves. */
export type ArticleAnalysisRecord = { iccs: string; startFen?: string };

/**
 * A short, stable hash of the record (cyrb53, 14 hex digits). Whitespace in the
 * move list is normalised so a reflowed spec keeps its key; a different move or
 * start position is a different key.
 */
export function articleAnalysisKey(record: ArticleAnalysisRecord): string {
  const moves = record.iccs.trim().split(/\s+/).filter(Boolean).join(' ');
  const text = `${record.startFen?.trim() ?? ''}|${moves}`;
  let h1 = 0xdeadbeef;
  let h2 = 0x41c6ce57;
  for (let i = 0; i < text.length; i += 1) {
    const ch = text.charCodeAt(i);
    h1 = Math.imul(h1 ^ ch, 2654435761);
    h2 = Math.imul(h2 ^ ch, 1597334677);
  }
  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507) ^ Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  h2 = Math.imul(h2 ^ (h2 >>> 16), 2246822507) ^ Math.imul(h1 ^ (h1 >>> 13), 3266489909);
  const value = 4294967296 * (2097151 & h2) + (h1 >>> 0);
  return value.toString(16).padStart(14, '0');
}

/** The lazy loader for this record's precomputed analysis, or null when there is none. */
export function articleAnalysisLoader(record: ArticleAnalysisRecord): AnalysisLoader | null {
  return LOADERS.get(articleAnalysisKey(record)) ?? null;
}

/** Every key that has a file, for the coverage test. */
export function articleAnalysisKeys(): string[] {
  return [...LOADERS.keys()];
}
