// Generated by scripts/gen-benedict-diagrams.mts in this repository (--site).
// Do not hand-edit: every position is played through the Benedict Xiangqi rule
// kernel (packages/game/src/variants-benedict-xiangqi.ts) and asserted there
// before it is written out, so a rules change redraws these boards instead of
// leaving them quietly wrong. Drawn with the shared xiangqi diagram toolkit so
// they follow the reader's board and piece pickers like every other figure.

import type { XiangqiPiece, XiangqiSquare } from '@mistboard/game';
import {
  activeXiangqiPieceSet,
  XQ_BOARD_H,
  XQ_BOARD_W,
  xqBoardSvg,
  xqSvg,
  xqVisionDemoState,
} from './articles/diagrams.js';
import { renderXiangqiPieceGlyphed } from './xiangqi-piece-sets.js';

type Board = Partial<Record<XiangqiSquare, XiangqiPiece>>;
/** A frame: the kernel's board, the move that led to it, the squares it converted. */
type Frame = { board: Board; from?: string; to?: string; marks: string[] };

/** The starting array. */
export const BENEDICT_START: Board = {
  a1: { color: 'red', role: 'chariot' },
  a10: { color: 'black', role: 'chariot' },
  a4: { color: 'red', role: 'soldier' },
  a7: { color: 'black', role: 'soldier' },
  b1: { color: 'red', role: 'horse' },
  b10: { color: 'black', role: 'horse' },
  b3: { color: 'red', role: 'cannon' },
  b8: { color: 'black', role: 'cannon' },
  c1: { color: 'red', role: 'elephant' },
  c10: { color: 'black', role: 'elephant' },
  c4: { color: 'red', role: 'soldier' },
  c7: { color: 'black', role: 'soldier' },
  d1: { color: 'red', role: 'advisor' },
  d10: { color: 'black', role: 'advisor' },
  e1: { color: 'red', role: 'general' },
  e10: { color: 'black', role: 'general' },
  e4: { color: 'red', role: 'soldier' },
  e7: { color: 'black', role: 'soldier' },
  f1: { color: 'red', role: 'advisor' },
  f10: { color: 'black', role: 'advisor' },
  g1: { color: 'red', role: 'elephant' },
  g10: { color: 'black', role: 'elephant' },
  g4: { color: 'red', role: 'soldier' },
  g7: { color: 'black', role: 'soldier' },
  h1: { color: 'red', role: 'horse' },
  h10: { color: 'black', role: 'horse' },
  h3: { color: 'red', role: 'cannon' },
  h8: { color: 'black', role: 'cannon' },
  i1: { color: 'red', role: 'chariot' },
  i10: { color: 'black', role: 'chariot' },
  i4: { color: 'red', role: 'soldier' },
  i7: { color: 'black', role: 'soldier' },
};

/** The rule on a demo board: d1d4 converts both soldiers on the fourth rank. */
export const BENEDICT_RULE: Frame[] = [
  {
    board: {
      a4: { color: 'black', role: 'soldier' },
      d1: { color: 'red', role: 'chariot' },
      e10: { color: 'black', role: 'general' },
      f1: { color: 'red', role: 'general' },
      g4: { color: 'black', role: 'soldier' },
    },
    marks: [],
  },
  {
    board: {
      a4: { color: 'red', role: 'soldier' },
      d4: { color: 'red', role: 'chariot' },
      e10: { color: 'black', role: 'general' },
      f1: { color: 'red', role: 'general' },
      g4: { color: 'red', role: 'soldier' },
    },
    from: 'd1',
    to: 'd4',
    marks: ['a4', 'g4'],
  },
];

/** From the array: b3b5, h8h5, b5e5 wins (the ring on the general it bears on). */
export const BENEDICT_THREAT: Frame[] = [
  {
    board: {
      a1: { color: 'red', role: 'chariot' },
      a10: { color: 'black', role: 'chariot' },
      a4: { color: 'red', role: 'soldier' },
      a7: { color: 'black', role: 'soldier' },
      b1: { color: 'red', role: 'horse' },
      b10: { color: 'black', role: 'horse' },
      b3: { color: 'red', role: 'cannon' },
      b8: { color: 'black', role: 'cannon' },
      c1: { color: 'red', role: 'elephant' },
      c10: { color: 'black', role: 'elephant' },
      c4: { color: 'red', role: 'soldier' },
      c7: { color: 'black', role: 'soldier' },
      d1: { color: 'red', role: 'advisor' },
      d10: { color: 'black', role: 'advisor' },
      e1: { color: 'red', role: 'general' },
      e10: { color: 'black', role: 'general' },
      e4: { color: 'red', role: 'soldier' },
      e7: { color: 'black', role: 'soldier' },
      f1: { color: 'red', role: 'advisor' },
      f10: { color: 'black', role: 'advisor' },
      g1: { color: 'red', role: 'elephant' },
      g10: { color: 'black', role: 'elephant' },
      g4: { color: 'red', role: 'soldier' },
      g7: { color: 'black', role: 'soldier' },
      h1: { color: 'red', role: 'horse' },
      h10: { color: 'black', role: 'horse' },
      h3: { color: 'red', role: 'cannon' },
      h8: { color: 'black', role: 'cannon' },
      i1: { color: 'red', role: 'chariot' },
      i10: { color: 'black', role: 'chariot' },
      i4: { color: 'red', role: 'soldier' },
      i7: { color: 'black', role: 'soldier' },
    },
    marks: [],
  },
  {
    board: {
      a1: { color: 'red', role: 'chariot' },
      a10: { color: 'black', role: 'chariot' },
      a4: { color: 'red', role: 'soldier' },
      a7: { color: 'black', role: 'soldier' },
      b1: { color: 'red', role: 'horse' },
      b10: { color: 'red', role: 'horse' },
      b5: { color: 'red', role: 'cannon' },
      b8: { color: 'black', role: 'cannon' },
      c1: { color: 'red', role: 'elephant' },
      c10: { color: 'black', role: 'elephant' },
      c4: { color: 'red', role: 'soldier' },
      c7: { color: 'black', role: 'soldier' },
      d1: { color: 'red', role: 'advisor' },
      d10: { color: 'black', role: 'advisor' },
      e1: { color: 'red', role: 'general' },
      e10: { color: 'black', role: 'general' },
      e4: { color: 'red', role: 'soldier' },
      e7: { color: 'black', role: 'soldier' },
      f1: { color: 'red', role: 'advisor' },
      f10: { color: 'black', role: 'advisor' },
      g1: { color: 'red', role: 'elephant' },
      g10: { color: 'black', role: 'elephant' },
      g4: { color: 'red', role: 'soldier' },
      g7: { color: 'black', role: 'soldier' },
      h1: { color: 'red', role: 'horse' },
      h10: { color: 'black', role: 'horse' },
      h3: { color: 'red', role: 'cannon' },
      h8: { color: 'black', role: 'cannon' },
      i1: { color: 'red', role: 'chariot' },
      i10: { color: 'black', role: 'chariot' },
      i4: { color: 'red', role: 'soldier' },
      i7: { color: 'black', role: 'soldier' },
    },
    from: 'b3',
    to: 'b5',
    marks: ['b10'],
  },
  {
    board: {
      a1: { color: 'red', role: 'chariot' },
      a10: { color: 'black', role: 'chariot' },
      a4: { color: 'red', role: 'soldier' },
      a7: { color: 'black', role: 'soldier' },
      b1: { color: 'red', role: 'horse' },
      b10: { color: 'red', role: 'horse' },
      b5: { color: 'red', role: 'cannon' },
      b8: { color: 'black', role: 'cannon' },
      c1: { color: 'red', role: 'elephant' },
      c10: { color: 'black', role: 'elephant' },
      c4: { color: 'red', role: 'soldier' },
      c7: { color: 'black', role: 'soldier' },
      d1: { color: 'red', role: 'advisor' },
      d10: { color: 'black', role: 'advisor' },
      e1: { color: 'red', role: 'general' },
      e10: { color: 'black', role: 'general' },
      e4: { color: 'red', role: 'soldier' },
      e7: { color: 'black', role: 'soldier' },
      f1: { color: 'red', role: 'advisor' },
      f10: { color: 'black', role: 'advisor' },
      g1: { color: 'red', role: 'elephant' },
      g10: { color: 'black', role: 'elephant' },
      g4: { color: 'red', role: 'soldier' },
      g7: { color: 'black', role: 'soldier' },
      h1: { color: 'black', role: 'horse' },
      h10: { color: 'black', role: 'horse' },
      h3: { color: 'red', role: 'cannon' },
      h5: { color: 'black', role: 'cannon' },
      i1: { color: 'red', role: 'chariot' },
      i10: { color: 'black', role: 'chariot' },
      i4: { color: 'red', role: 'soldier' },
      i7: { color: 'black', role: 'soldier' },
    },
    from: 'h8',
    to: 'h5',
    marks: ['h1'],
  },
  {
    board: {
      a1: { color: 'red', role: 'chariot' },
      a10: { color: 'black', role: 'chariot' },
      a4: { color: 'red', role: 'soldier' },
      a7: { color: 'black', role: 'soldier' },
      b1: { color: 'red', role: 'horse' },
      b10: { color: 'red', role: 'horse' },
      b8: { color: 'black', role: 'cannon' },
      c1: { color: 'red', role: 'elephant' },
      c10: { color: 'black', role: 'elephant' },
      c4: { color: 'red', role: 'soldier' },
      c7: { color: 'black', role: 'soldier' },
      d1: { color: 'red', role: 'advisor' },
      d10: { color: 'black', role: 'advisor' },
      e1: { color: 'red', role: 'general' },
      e10: { color: 'black', role: 'general' },
      e4: { color: 'red', role: 'soldier' },
      e5: { color: 'red', role: 'cannon' },
      e7: { color: 'black', role: 'soldier' },
      f1: { color: 'red', role: 'advisor' },
      f10: { color: 'black', role: 'advisor' },
      g1: { color: 'red', role: 'elephant' },
      g10: { color: 'black', role: 'elephant' },
      g4: { color: 'red', role: 'soldier' },
      g7: { color: 'black', role: 'soldier' },
      h1: { color: 'black', role: 'horse' },
      h10: { color: 'black', role: 'horse' },
      h3: { color: 'red', role: 'cannon' },
      h5: { color: 'black', role: 'cannon' },
      i1: { color: 'red', role: 'chariot' },
      i10: { color: 'black', role: 'chariot' },
      i4: { color: 'red', role: 'soldier' },
      i7: { color: 'black', role: 'soldier' },
    },
    from: 'b5',
    to: 'e5',
    marks: ['e10'],
  },
];

function benedictFrame(id: string, frame: Frame): () => string {
  return () =>
    xqSvg(
      XQ_BOARD_W,
      XQ_BOARD_H + 8,
      xqBoardSvg({
        state: xqVisionDemoState(id, frame.board),
        x: 0,
        y: -24,
        label: '',
        perspective: 'red',
        arrows:
          frame.from && frame.to
            ? [{ from: frame.from as XiangqiSquare, to: frame.to as XiangqiSquare }]
            : undefined,
        dots: frame.marks.map((square) => ({ square: square as XiangqiSquare, capture: true })),
      }),
    );
}

/** Stepper steps: the move that led to each frame names its row of the score
 *  sheet, and notes[i] is the note under it (notes[0] describes the start). */
export function benedictSteps(
  id: string,
  frames: Frame[],
  notes: ReadonlyArray<string | undefined>,
): Array<{ svg: () => string; narrative?: string; move?: string }> {
  return frames.map((frame, i) => ({
    svg: benedictFrame(`${id}-${i}`, frame),
    ...(notes[i] ? { narrative: notes[i] } : {}),
    ...(frame.from && frame.to ? { move: `${frame.from}${frame.to}` } : {}),
  }));
}

/** The four first moves closest to even (45.8%, 50.0%, 54.2%, 54.2%), cropped to
 *  Red's half, the river and Black's soldier rank. */
export const BENEDICT_PIE_FRAMES: Array<() => string> = [
  ['b3', 'b4'],
  ['b3', 'b7'],
  ['d1', 'e2'],
  ['e4', 'e5'],
].map(
  ([from, to], i) =>
    () =>
      xqSvg(
        XQ_BOARD_W,
        XQ_BOARD_H + 28,
        xqBoardSvg({
          state: xqVisionDemoState(`benedict-pie-${i}`, BENEDICT_START),
          x: 0,
          y: 0,
          label: '',
          perspective: 'red',
          arrows: [{ from: from as XiangqiSquare, to: to as XiangqiSquare }],
        }),
      ).replace(/viewBox="0 0 ([\d.]+) [\d.]+"/, (_, w) => `viewBox="0 131 ${w} 216"`),
);

/** Red's 42 first moves and Red's score after each, three move/score pairs a
 *  row, reading down each pair of columns from the lowest score. */
export const BENEDICT_OPENING_ROWS: string[][] = [
  ['c1a3', '0.0%', 'h1g3', '25.0%', 'a4a5', '41.7%'],
  ['e1e2', '0.0%', 'a1a3', '27.1%', 'g4g5', '43.8%'],
  ['g1i3', '0.0%', 'b3b2', '27.1%', 'b3b4', '45.8%'],
  ['b3a3', '4.2%', 'h3h2', '29.2%', 'b3b7', '50.0%'],
  ['b3c3', '8.3%', 'b3d3', '29.2%', 'd1e2', '54.2%'],
  ['h1i3', '12.5%', 'i4i5', '29.2%', 'e4e5', '54.2%'],
  ['h3f3', '16.7%', 'b3f3', '33.3%', 'a1a2', '58.3%'],
  ['b3g3', '18.8%', 'b1a3', '35.4%', 'h3h7', '60.4%'],
  ['h3c3', '20.8%', 'c1e3', '35.4%', 'h3h4', '60.4%'],
  ['i1i2', '20.8%', 'b3e3', '35.4%', 'b3b6', '70.8%'],
  ['h3g3', '22.9%', 'c4c5', '35.4%', 'f1e2', '72.9%'],
  ['i1i3', '25.0%', 'h3e3', '37.5%', 'h3h5', '79.2%'],
  ['h3i3', '25.0%', 'h3d3', '39.6%', 'b3b5', '87.5%'],
  ['g1e3', '25.0%', 'b1c3', '41.7%', 'h3h6', '91.7%'],
];

// The card: a black horse and the red horse it becomes.
const THUMB_W = 160;
const THUMB_H = 100;
const THUMB_SIZE = 62;

export const BENEDICT_XIANGQI_THUMBNAIL = () => {
  const gap = 28;
  const x0 = (THUMB_W - (THUMB_SIZE * 2 + gap)) / 2;
  const y = (THUMB_H - THUMB_SIZE) / 2;
  const mid = THUMB_H / 2;
  const ax = x0 + THUMB_SIZE + 6;
  const bx = x0 + THUMB_SIZE + gap - 6;
  return [
    `<svg class="xq-article-svg" viewBox="0 0 ${THUMB_W} ${THUMB_H}" role="img" aria-label="Benedict Xiangqi" xmlns="http://www.w3.org/2000/svg">`,
    renderXiangqiPieceGlyphed({ role: 'horse', color: 'black' }, activeXiangqiPieceSet, {
      x: x0,
      y,
      size: THUMB_SIZE,
    }),
    `<path d="M${ax} ${mid}H${bx}M${bx - 6} ${mid - 6}L${bx} ${mid}L${bx - 6} ${mid + 6}" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" opacity="0.7"/>`,
    renderXiangqiPieceGlyphed({ role: 'horse', color: 'red' }, activeXiangqiPieceSet, {
      x: x0 + THUMB_SIZE + gap,
      y,
      size: THUMB_SIZE,
    }),
    '</svg>',
  ].join('');
};

/** The English templates the games card's records name (benedict-xiangqi-games.ts). */
export const BENEDICT_GAME_SET_STRINGS: Record<string, string> = {
  game: 'Game',
  red: 'Red',
  black: 'Black',
  'group-won': 'First mover won (%1)',
  'group-lost': 'First mover lost (%1)',
  label: 'Game %1: %2 first, %3 plies',
  'result-won': '%1 moved first and won in %2 plies.',
  'result-lost': '%1 moved first and lost in %2 plies.',
  'red-wins': 'Red wins',
  'black-wins': 'Black wins',
  'seat-engine': 'Engine, 2M nodes',
};
