// Generated by scripts/gen-horde-diagrams.mts in this repository (--blog).
// Do not hand-edit: the positions are replayed through the horde-xiangqi rule
// kernel there (scripts/variant-lab/lab/variants/horde-xiangqi.ts on
// packages/game/src/xiangqi-rule-kernel.ts) and asserted before they are
// written out, so a rules change redraws these boards instead of leaving them
// quietly wrong. Drawn with the shared xiangqi diagram toolkit so they follow
// the reader's board and piece pickers like every other xiangqi figure.

import type { XiangqiPiece, XiangqiSquare } from '@mistboard/game';
import {
  activeXiangqiPieceSet,
  XQ_BOARD_H,
  XQ_BOARD_W,
  xqBoardSvg,
  xqSvg,
  xqVisionDemoState,
} from './articles/diagrams.js';
import { renderXiangqiPieceGlyphed } from './xiangqi-piece-sets.js';

type Board = Partial<Record<XiangqiSquare, XiangqiPiece>>;

const PAIR_W = XQ_BOARD_W * 2 + 28;
const PAIR_GAP_X = XQ_BOARD_W + 28;
const FIGURE_H = XQ_BOARD_H + 34;

/** The parent's array: 36 standard soldiers on ranks 1 to 4. */
export const HORDE_SOLID36: Board = {
  a1: { color: 'red', role: 'soldier' },
  a10: { color: 'black', role: 'chariot' },
  a2: { color: 'red', role: 'soldier' },
  a3: { color: 'red', role: 'soldier' },
  a4: { color: 'red', role: 'soldier' },
  a7: { color: 'black', role: 'soldier' },
  b1: { color: 'red', role: 'soldier' },
  b10: { color: 'black', role: 'horse' },
  b2: { color: 'red', role: 'soldier' },
  b3: { color: 'red', role: 'soldier' },
  b4: { color: 'red', role: 'soldier' },
  b8: { color: 'black', role: 'cannon' },
  c1: { color: 'red', role: 'soldier' },
  c10: { color: 'black', role: 'elephant' },
  c2: { color: 'red', role: 'soldier' },
  c3: { color: 'red', role: 'soldier' },
  c4: { color: 'red', role: 'soldier' },
  c7: { color: 'black', role: 'soldier' },
  d1: { color: 'red', role: 'soldier' },
  d10: { color: 'black', role: 'advisor' },
  d2: { color: 'red', role: 'soldier' },
  d3: { color: 'red', role: 'soldier' },
  d4: { color: 'red', role: 'soldier' },
  e1: { color: 'red', role: 'soldier' },
  e10: { color: 'black', role: 'general' },
  e2: { color: 'red', role: 'soldier' },
  e3: { color: 'red', role: 'soldier' },
  e4: { color: 'red', role: 'soldier' },
  e7: { color: 'black', role: 'soldier' },
  f1: { color: 'red', role: 'soldier' },
  f10: { color: 'black', role: 'advisor' },
  f2: { color: 'red', role: 'soldier' },
  f3: { color: 'red', role: 'soldier' },
  f4: { color: 'red', role: 'soldier' },
  g1: { color: 'red', role: 'soldier' },
  g10: { color: 'black', role: 'elephant' },
  g2: { color: 'red', role: 'soldier' },
  g3: { color: 'red', role: 'soldier' },
  g4: { color: 'red', role: 'soldier' },
  g7: { color: 'black', role: 'soldier' },
  h1: { color: 'red', role: 'soldier' },
  h10: { color: 'black', role: 'horse' },
  h2: { color: 'red', role: 'soldier' },
  h3: { color: 'red', role: 'soldier' },
  h4: { color: 'red', role: 'soldier' },
  h8: { color: 'black', role: 'cannon' },
  i1: { color: 'red', role: 'soldier' },
  i10: { color: 'black', role: 'chariot' },
  i2: { color: 'red', role: 'soldier' },
  i3: { color: 'red', role: 'soldier' },
  i4: { color: 'red', role: 'soldier' },
  i7: { color: 'black', role: 'soldier' },
};
/** 36 veterans on ranks 2 to 5, the array the horde wins four times in five. */
export const HORDE_FORWARD36: Board = {
  a10: { color: 'black', role: 'chariot' },
  a2: { color: 'red', role: 'soldier' },
  a3: { color: 'red', role: 'soldier' },
  a4: { color: 'red', role: 'soldier' },
  a5: { color: 'red', role: 'soldier' },
  a7: { color: 'black', role: 'soldier' },
  b10: { color: 'black', role: 'horse' },
  b2: { color: 'red', role: 'soldier' },
  b3: { color: 'red', role: 'soldier' },
  b4: { color: 'red', role: 'soldier' },
  b5: { color: 'red', role: 'soldier' },
  b8: { color: 'black', role: 'cannon' },
  c10: { color: 'black', role: 'elephant' },
  c2: { color: 'red', role: 'soldier' },
  c3: { color: 'red', role: 'soldier' },
  c4: { color: 'red', role: 'soldier' },
  c5: { color: 'red', role: 'soldier' },
  c7: { color: 'black', role: 'soldier' },
  d10: { color: 'black', role: 'advisor' },
  d2: { color: 'red', role: 'soldier' },
  d3: { color: 'red', role: 'soldier' },
  d4: { color: 'red', role: 'soldier' },
  d5: { color: 'red', role: 'soldier' },
  e10: { color: 'black', role: 'general' },
  e2: { color: 'red', role: 'soldier' },
  e3: { color: 'red', role: 'soldier' },
  e4: { color: 'red', role: 'soldier' },
  e5: { color: 'red', role: 'soldier' },
  e7: { color: 'black', role: 'soldier' },
  f10: { color: 'black', role: 'advisor' },
  f2: { color: 'red', role: 'soldier' },
  f3: { color: 'red', role: 'soldier' },
  f4: { color: 'red', role: 'soldier' },
  f5: { color: 'red', role: 'soldier' },
  g10: { color: 'black', role: 'elephant' },
  g2: { color: 'red', role: 'soldier' },
  g3: { color: 'red', role: 'soldier' },
  g4: { color: 'red', role: 'soldier' },
  g5: { color: 'red', role: 'soldier' },
  g7: { color: 'black', role: 'soldier' },
  h10: { color: 'black', role: 'horse' },
  h2: { color: 'red', role: 'soldier' },
  h3: { color: 'red', role: 'soldier' },
  h4: { color: 'red', role: 'soldier' },
  h5: { color: 'red', role: 'soldier' },
  h8: { color: 'black', role: 'cannon' },
  i10: { color: 'black', role: 'chariot' },
  i2: { color: 'red', role: 'soldier' },
  i3: { color: 'red', role: 'soldier' },
  i4: { color: 'red', role: 'soldier' },
  i5: { color: 'red', role: 'soldier' },
  i7: { color: 'black', role: 'soldier' },
};
/** The solid36 million-node game before Black's 25th: the f-file is open. */
export const HORDE_BEFORE_DROP: Board = {
  a1: { color: 'red', role: 'soldier' },
  a10: { color: 'black', role: 'chariot' },
  a2: { color: 'red', role: 'soldier' },
  a3: { color: 'red', role: 'soldier' },
  a4: { color: 'red', role: 'soldier' },
  a6: { color: 'black', role: 'soldier' },
  b1: { color: 'red', role: 'soldier' },
  b2: { color: 'red', role: 'soldier' },
  b3: { color: 'red', role: 'soldier' },
  b7: { color: 'black', role: 'cannon' },
  c1: { color: 'red', role: 'soldier' },
  c2: { color: 'red', role: 'soldier' },
  c3: { color: 'red', role: 'soldier' },
  c4: { color: 'red', role: 'soldier' },
  c8: { color: 'black', role: 'horse' },
  d3: { color: 'red', role: 'soldier' },
  d4: { color: 'red', role: 'soldier' },
  d5: { color: 'red', role: 'soldier' },
  e1: { color: 'red', role: 'soldier' },
  e10: { color: 'black', role: 'general' },
  e2: { color: 'red', role: 'soldier' },
  e3: { color: 'red', role: 'soldier' },
  e6: { color: 'red', role: 'soldier' },
  e8: { color: 'black', role: 'elephant' },
  f1: { color: 'red', role: 'soldier' },
  f10: { color: 'black', role: 'advisor' },
  f5: { color: 'black', role: 'chariot' },
  f8: { color: 'black', role: 'advisor' },
  f9: { color: 'black', role: 'cannon' },
  g1: { color: 'red', role: 'soldier' },
  g10: { color: 'black', role: 'elephant' },
  g2: { color: 'red', role: 'soldier' },
  g3: { color: 'red', role: 'soldier' },
  g4: { color: 'red', role: 'soldier' },
  g6: { color: 'black', role: 'soldier' },
  h1: { color: 'red', role: 'soldier' },
  h2: { color: 'red', role: 'soldier' },
  h3: { color: 'red', role: 'soldier' },
  h6: { color: 'red', role: 'soldier' },
  i1: { color: 'red', role: 'soldier' },
  i2: { color: 'red', role: 'soldier' },
  i3: { color: 'red', role: 'soldier' },
  i4: { color: 'red', role: 'soldier' },
  i6: { color: 'black', role: 'soldier' },
};
/** Fifteen moves later: 11 soldiers gone from behind. */
export const HORDE_AFTER_DROP: Board = {
  a1: { color: 'red', role: 'soldier' },
  a2: { color: 'red', role: 'soldier' },
  a3: { color: 'red', role: 'soldier' },
  a4: { color: 'red', role: 'soldier' },
  a6: { color: 'black', role: 'soldier' },
  b1: { color: 'red', role: 'soldier' },
  b3: { color: 'red', role: 'soldier' },
  b4: { color: 'red', role: 'soldier' },
  b7: { color: 'black', role: 'cannon' },
  c1: { color: 'red', role: 'soldier' },
  c2: { color: 'red', role: 'soldier' },
  c3: { color: 'red', role: 'soldier' },
  c4: { color: 'red', role: 'soldier' },
  d3: { color: 'black', role: 'chariot' },
  d5: { color: 'red', role: 'soldier' },
  e10: { color: 'black', role: 'general' },
  e6: { color: 'black', role: 'chariot' },
  e8: { color: 'black', role: 'elephant' },
  e9: { color: 'black', role: 'advisor' },
  f10: { color: 'black', role: 'advisor' },
  f9: { color: 'black', role: 'cannon' },
  g10: { color: 'black', role: 'elephant' },
  g4: { color: 'red', role: 'soldier' },
  h1: { color: 'red', role: 'soldier' },
  h3: { color: 'red', role: 'soldier' },
  h4: { color: 'red', role: 'soldier' },
  i2: { color: 'red', role: 'soldier' },
  i3: { color: 'red', role: 'soldier' },
  i4: { color: 'red', role: 'soldier' },
  i5: { color: 'red', role: 'soldier' },
};
/** Ply 435 of the forward36 veteran game: the bare general has no move and is not in check. */
export const HORDE_SMOTHER: Board = {
  a8: { color: 'red', role: 'soldier' },
  b8: { color: 'red', role: 'soldier' },
  c9: { color: 'red', role: 'soldier' },
  d6: { color: 'red', role: 'soldier' },
  d7: { color: 'red', role: 'soldier' },
  d9: { color: 'red', role: 'soldier' },
  e2: { color: 'red', role: 'soldier' },
  e4: { color: 'red', role: 'soldier' },
  e5: { color: 'red', role: 'soldier' },
  e9: { color: 'red', role: 'soldier' },
  f10: { color: 'black', role: 'general' },
  f8: { color: 'red', role: 'soldier' },
  g8: { color: 'red', role: 'soldier' },
  h8: { color: 'red', role: 'soldier' },
  i8: { color: 'red', role: 'soldier' },
};

export const HORDE_XIANGQI_START = () =>
  xqSvg(
    PAIR_W,
    FIGURE_H,
    [
      xqBoardSvg({
        state: xqVisionDemoState('horde-solid36', HORDE_SOLID36),
        x: 0,
        y: 0,
        label: '36 STANDARD SOLDIERS, RANKS 1-4',
        perspective: 'red',
      }),
      xqBoardSvg({
        state: xqVisionDemoState('horde-forward36', HORDE_FORWARD36),
        x: PAIR_GAP_X,
        y: 0,
        label: '36 VETERANS, RANKS 2-5',
        perspective: 'red',
        veteranSoldiers: true,
      }),
    ].join(''),
  );

export const HORDE_XIANGQI_CHARIOT = () =>
  xqSvg(
    PAIR_W,
    FIGURE_H,
    [
      xqBoardSvg({
        state: xqVisionDemoState('horde-before-drop', HORDE_BEFORE_DROP),
        x: 0,
        y: 0,
        label: 'MOVE 25: THE f-FILE IS OPEN',
        perspective: 'red',
        arrows: [{ from: 'f5' as XiangqiSquare, to: 'f1' as XiangqiSquare }],
      }),
      xqBoardSvg({
        state: xqVisionDemoState('horde-after-drop', HORDE_AFTER_DROP),
        x: PAIR_GAP_X,
        y: 0,
        label: '15 MOVES LATER: 11 SOLDIERS GONE',
        perspective: 'red',
      }),
    ].join(''),
  );

export const HORDE_XIANGQI_SMOTHER = () =>
  xqSvg(
    PAIR_W,
    FIGURE_H,
    xqBoardSvg({
      state: xqVisionDemoState('horde-smother', HORDE_SMOTHER),
      x: PAIR_GAP_X / 2,
      y: 0,
      label: 'PLY 435: NO MOVE, NO CHECK, RED WINS',
      perspective: 'red',
      veteranSoldiers: true,
    }),
  );

// The card: a block of veteran soldiers and the one piece that beats it.
const THUMB_W = 160;
const THUMB_H = 100;
const SOLDIER = 40;
const CHARIOT = 74;

export const HORDE_XIANGQI_THUMBNAIL = () => {
  const gap = Math.round(SOLDIER * 0.1);
  const blockW = SOLDIER * 2 + gap;
  const between = Math.round(CHARIOT * 0.22);
  const x0 = (THUMB_W - (blockW + between + CHARIOT)) / 2;
  const y0 = (THUMB_H - blockW) / 2;
  const parts = [
    `<svg class="xq-article-svg" viewBox="0 0 ${THUMB_W} ${THUMB_H}" role="img" aria-label="Horde Xiangqi" xmlns="http://www.w3.org/2000/svg">`,
  ];
  for (let r = 0; r < 2; r += 1)
    for (let c = 0; c < 2; c += 1)
      parts.push(
        renderXiangqiPieceGlyphed({ role: 'soldier', color: 'red' }, activeXiangqiPieceSet, {
          x: x0 + c * (SOLDIER + gap),
          y: y0 + r * (SOLDIER + gap),
          size: SOLDIER,
          crossed: true,
        }),
      );
  parts.push(
    renderXiangqiPieceGlyphed({ role: 'chariot', color: 'black' }, activeXiangqiPieceSet, {
      x: x0 + blockW + between,
      y: (THUMB_H - CHARIOT) / 2,
      size: CHARIOT,
    }),
    '</svg>',
  );
  return parts.join('');
};
