import {
  BENEDICT_GAME_SET_STRINGS,
  BENEDICT_OPENING_ROWS,
  BENEDICT_PIE_FRAMES,
  BENEDICT_RULE,
  BENEDICT_THREAT,
  BENEDICT_XIANGQI_THUMBNAIL,
  benedictSteps,
} from '../../benedict-xiangqi-article-diagrams.js';
import type { Article, ArticleBlock } from '../types.js';

// Every board here is generated by scripts/gen-benedict-diagrams.mts --site
// from the Benedict Xiangqi rule kernel (packages/game/src/variants-benedict-xiangqi.ts):
// the two steppers, the four pie-rule openings, the opening table's move list
// and all 54 games. The evidence repository holds the engine and the harness.
const EVIDENCE = 'https://github.com/brianhliou/benedict-xiangqi';

const PIE_CAPTIONS = [
  'b3b4, 45.8%. The cannon steps up one square, short of the fifth rank that does the damage.',
  'b3b7, 50.0%. The cannon goes all the way in, converting now and giving up the standing threat.',
  'd1e2, 54.2%. An advisor develops into the middle of the palace.',
  'e4e5, 54.2%. The central soldier: the one quiet developing move that is not a blunder.',
];

export const benedictXiangqiArticle: Article = {
  slug: 'benedict-xiangqi',
  kind: 'article',
  publisher: 'mistboard',
  boardFamily: 'xiangqi',
  title: 'Benedict Xiangqi: The First Mover Wins 78%',
  cardTitle: 'Benedict Xiangqi Is Unfair',
  seoTitle: 'Benedict Xiangqi: Benedict Chess on the Xiangqi Board, Measured',
  summary:
    'We put Benedict Chess’s rule on the xiangqi board: nothing is captured, and every enemy piece your moved piece attacks joins you. The game has no endgame and no draws, and the first mover wins 78% of engine games, nearly all of it from one cannon move. The pie rule looks like the repair.',
  showSummaryOnPage: false,
  status: 'published',
  publishedAt: '2026-10-08',
  audience:
    'Chess variant players who know Benedict Chess, and xiangqi players curious what a conversion rule does to cannons, palaces and the opening.',
  thumbnail: { kind: 'svg', svg: BENEDICT_XIANGQI_THUMBNAIL },
  intro: [
    {
      kind: 'paragraph',
      text: 'Benedict Chess has no captures. When you move a piece, every enemy piece it attacks from its new square changes color and joins you, and you win by turning the enemy king. W. D. Troyka invented it and named it for Benedict Arnold, who changed sides. We put the same rule on the xiangqi board and measured the result with an engine of our own.',
    },
    {
      kind: 'paragraph',
      text: 'Conversion games already exist, and several sit one rule away from this one. Desertion Chess converts a piece by moving next to it, and keeps captures. Andernach Chess turns the capturing piece. Cleopatra Chess is Troyka’s rule for a single piece. Banqi and jieqi, xiangqi’s own flipping games, turn a piece over to reveal what it is, which says nothing about whose it is. Benedict Xiangqi takes Troyka’s rule whole, for every piece, on the xiangqi board.',
    },
    {
      kind: 'paragraph',
      text: 'The port forced four design decisions with no default answer. Then the measurement found the game unfair: the first mover wins 78% of engine games, and nearly all of that comes from one cannon move on move one. Mistboard has no Benedict Xiangqi play page. This page holds the design and the measurement.',
    },
  ],
  sections: [
    {
      heading: 'The rule',
      blocks: [
        {
          kind: 'paragraph',
          text: 'Move a piece. Every enemy piece it attacks from where it lands joins you. Nothing is ever captured, so all 32 pieces stay on the board for the whole game, and a move that attacks the enemy general wins.',
        },
        {
          kind: 'raw-svg-stepper',
          steps: benedictSteps('benedict-rule', BENEDICT_RULE, [
            'Red to move. The chariot on d1 attacks nothing. Two black soldiers stand on the fourth rank, where it is going.',
            'Both soldiers change sides. Nothing was captured and nothing left the board, so Red is two pieces up and Black two down from one move.',
          ]),
          caption: 'The rule on a demo board. The rings mark the pieces the move converted.',
        } as ArticleBlock,
        {
          kind: 'paragraph',
          text: 'A standing attack does nothing. Only the piece that moved converts, so a chariot already bearing on a piece has to move again to take it. Threats are made by moving.',
        },
      ],
    },
    {
      heading: 'What it does to xiangqi',
      blocks: [
        {
          kind: 'paragraph',
          text: '**No endgame, ever.** There are no trades and nothing simplifies, and an endgame tablebase cannot exist because the material never shrinks. Xiangqi endgame theory, which is most of xiangqi theory, does not transfer at all.',
        },
        {
          kind: 'paragraph',
          text: '**Cannons never weaken.** A xiangqi cannon needs a screen to capture, so in xiangqi it weakens as the board empties. Here the board never empties, and a cannon is as dangerous late in the game as on move 3.',
        },
        {
          kind: 'paragraph',
          text: '**Advisors and elephants defend nothing.** They exist to guard against captures, and there are no captures. They still block lines and screen for cannons, but everything they were designed to do is gone.',
        },
        {
          kind: 'paragraph',
          text: '**Games are short and nobody draws.** Half of the 54 engine games below were over by ply 28. None of them was drawn, and none of 6,000 games of uniformly random legal moves was either. With no material to trade and no endgame to grind, every game reaches a decision.',
        },
        {
          kind: 'paragraph',
          text: '**About 28% of legal moves lose on the spot.** That is the mean over the 1,696 positions in the engine games. The median position has 10% of its moves losing, and a minority of very sharp positions carries the mean. The share climbs from 24% in the first fifth of a game to 37% in the last, so there is no quiet opening phase to develop in.',
        },
      ],
    },
    {
      heading: 'Designing it: four decisions',
      blocks: [
        {
          kind: 'paragraph',
          text: '**The generals still may never face.** Xiangqi forbids the two generals from standing on one file with nothing between them, and we kept it. The alternative is to make the flying general a win, and it breaks: only the piece that moved converts, so unblocking the file wins nothing, and the generals end up facing each other while play carries on until someone shuffles a general along the file to claim it.',
        },
        {
          kind: 'paragraph',
          text: 'Keeping the prohibition costs nothing and adds something xiangqi does not have. A piece pinned on the generals’ file cannot be removed, because nothing here removes anything, and converting it does not release it, since a conversion recolors in place. You can win the piece and still be unable to move it until a general steps off the file.',
        },
        {
          kind: 'paragraph',
          text: '**Advisors and elephants are bound to the region they stand in, whoever owns them.** A converted advisor stands inside the enemy palace. Bound to its owner’s palace it would be frozen there for good; bound to the palace it stands in, it keeps playing and attacks from inside. From the starting array the two readings agree, because every advisor starts in its own palace.',
        },
        {
          kind: 'paragraph',
          text: '**Soldiers are bound to their owner.** A soldier’s forward direction has to follow whoever owns it now, or a converted soldier marches away from its new side forever. Getting these two rules backwards breaks the game quietly.',
        },
        {
          kind: 'paragraph',
          text: '**Draws need a progress clock.** With no captures, nearly every move can be undone, and three-fold repetition alone is not enough. The clock resets on the only two events that cannot be undone: a conversion, or a soldier move.',
        },
      ],
    },
    {
      heading: 'How we tested it',
      blocks: [
        {
          kind: 'paragraph',
          text: 'No existing engine plays this. Pikafish and Fairy-Stockfish encode capture rules, and Fairy-Stockfish’s one conversion mechanism flips pieces enclosed by a drop, Reversi-style, which is a different rule. So we wrote one in Rust: alpha-beta search with a transposition table, principal variation search, late move reductions, and a quiescence search over conversions. Its piece values were fitted by logistic regression on self-play outcomes, and they beat our hand-picked values head to head.',
        },
        {
          kind: 'paragraph',
          text: 'We do not quote the fitted values. An earlier fit on a quarter of the data had several values whose signs later reversed, which is more noise than a table of piece values can carry. The ordering survived: advisors and elephants come out close to worthless, which follows anyway from there being nothing to defend against.',
        },
        {
          kind: 'paragraph',
          text: 'The rules were checked before anything was measured. All 54 engine games below replay through Mistboard’s TypeScript rule kernel with the same conversions and the same number of legal moves at every one of their 1,696 positions, and every board on this page is played through that kernel. Three results do not depend on how well the engine plays.',
        },
        {
          kind: 'table',
          headers: ['Test', 'Result'],
          rows: [
            [
              'Uniformly random legal moves, 6,000 games',
              '54.5% for the first mover, no draws',
            ],
            [
              'Proof search from the starting array, 20.8 billion nodes',
              'No forced win within 13 plies',
            ],
            [
              'Legal moves that lose on the spot, 1,696 positions',
              'Mean 28%, median 10%',
            ],
          ],
          keyColumn: true,
          wrap: true,
        } as ArticleBlock,
        {
          kind: 'paragraph',
          text: 'Random play already favors the first mover. 54.5% over 6,000 games is about seven standard errors above even, so a tempo is worth something before either side plays well.',
        },
        {
          kind: 'paragraph',
          text: 'The proof needs care, because an ordinary search cannot make one. Late move reductions search later moves shallower, so a normal search that finds no win has only shown that it did not look everywhere. With reductions and quiescence turned off, and the question asked as a yes or no at the mate threshold, the search proves there is no forced win within 13 plies. That took 20.8 billion nodes and about half an hour.',
        },
        {
          kind: 'paragraph',
          text: 'We also checked whether the 78% moves when the engine gets stronger. It barely moves between 300,000 and 2 million nodes a move, a sevenfold range.',
        },
        {
          kind: 'paragraph',
          text: 'Stability alone is not enough. An earlier version of this measurement varied its games with a six-ply random opening book, got 52.7%, and held it across a tenfold range of engine strength. It was stable because the book spent the very tempo being measured: six random plies throw the advantage away before either engine plays a move. A broken thermometer reads room temperature in every room. The 78% uses no book and takes its variety from evaluation jitter.',
        },
      ],
    },
    {
      heading: 'One cannon move decides it',
      blocks: [
        {
          kind: 'paragraph',
          text: 'The first mover wins 78% of engine games, measured from the starting array with no opening book and the two colors taking the first move in turn. Then we measured each of Red’s 42 legal first moves on its own, and the diagnosis changed shape.',
        },
        {
          kind: 'table',
          headers: ['Move', 'Red scores', 'Move', 'Red scores', 'Move', 'Red scores'],
          rows: BENEDICT_OPENING_ROWS,
          compact: true,
          caption:
            'All 42 legal first moves, 24 engine games each at 300,000 nodes a move. Read down each pair of columns, lowest score first.',
        } as ArticleBlock,
        {
          kind: 'paragraph',
          text: 'The two best are the same idea, a cannon lifted to the fifth or sixth rank: h3h6 scores 91.7% and b3b5 87.5%. The three that score nothing are two elephant moves to the edge of the board, c1a3 and g1i3, and the general stepping up the middle, e1e2. Red’s first move is worth anywhere from nothing to 92%, so the 78% measures an engine that always finds the strong opening.',
        },
        {
          kind: 'raw-svg-stepper',
          steps: benedictSteps('benedict-threat', BENEDICT_THREAT, [
            'The starting array, Red to move.',
            'The cannon fires up the b-file over Black’s own cannon and turns the horse on b10. It also threatens b5e5, with Black’s soldier on e7 as the screen and the general behind it. 32 of Black’s 38 replies lose at once, and b5e5 wins against every one of them.',
            'Black answers in kind and turns the horse on h1. It looks reasonable, and it is one of the 32.',
            'The cannon fires over the soldier on e7 at the general on e10, and the game is over.',
          ]),
          result: 'Red wins',
          caption:
            'From the starting array. The rings mark what each move converted, and on the last move the general it attacks.',
        } as ArticleBlock,
        {
          kind: 'paragraph',
          text: 'A xiangqi cannon needs exactly one piece between it and its target, and Black’s starting position supplies that piece in the right place for free. The threat exists because the xiangqi starting array happens to sit where Benedict’s rule can use it.',
        },
      ],
    },
    {
      heading: 'Every game the engine played',
      blocks: [
        {
          kind: 'paragraph',
          text: 'All 54 games from the strongest setting, 2 million nodes a move, uncurated. Red moved first in 36 and won 33; Black moved first in 18 and won 13. The first mover won 46, and the eight it lost are the ones worth opening.',
        },
        {
          kind: 'step-game-set',
          load: () => import('../../benedict-xiangqi-games.js'),
          strings: BENEDICT_GAME_SET_STRINGS,
          caption:
            'All 54 games, each replayed through the rule kernel. The rings mark the pieces each move converted, and on the last move the general it attacks. The arrow keys step through the game on the board.',
        } as ArticleBlock,
      ],
    },
    {
      heading: 'The pie rule',
      blocks: [
        {
          kind: 'paragraph',
          text: 'The spread across those 42 openings is what makes the game recoverable, and the repair already exists. The pie rule divides a cake the way two children do: one cuts, the other picks. Red plays a first move, then Black chooses whether to stay Black or take over Red’s position. Playing the strongest opening becomes pointless when Black can simply take it.',
        },
        {
          kind: 'paragraph',
          text: 'So Red is pushed toward the move closest to even, and four of the 42 sit there. Two are the cannon declining its own best square, and two are the quietest developing moves on the board.',
        },
        {
          kind: 'svg-row',
          items: BENEDICT_PIE_FRAMES.map((svg, i) => ({ svg, caption: PIE_CAPTIONS[i] })),
          caption: 'The four first moves closest to even, with what Red scores after each.',
        } as ArticleBlock,
        {
          kind: 'paragraph',
          text: 'Held to one of those, the game lands near 50%, because Red can no longer use the advantage. Hex is a proven first-player win at every board size and is played competitively, because of the swap.',
        },
        {
          kind: 'paragraph',
          text: 'Those four numbers come from 24 games each: too few to rank them against each other, and enough to say the spread from 0% to 92% is real. Confirming that one of them holds near 50% over a proper sample is the open work.',
        },
        {
          kind: 'paragraph',
          text: 'The pie rule fixes fairness and leaves the sharpness alone. The losing-move share is a property of the rules, so it does not move. The contest becomes even and stays sharp, and whether people want to play that is a question win rates cannot answer.',
        },
      ],
    },
    {
      heading: 'Where it stands',
      blocks: [
        {
          kind: 'paragraph',
          text: 'It is not shippable as a competitive game. No rated ladder survives the first mover winning three games in four.',
        },
        {
          kind: 'paragraph',
          text: 'Unfair does not mean unplayable. Losing chess is a proven first-player win and is played every day, because the proof runs down lines no human finds, and Hex is played behind the swap. What is different here is depth. This 78% rests on one move you can say in a sentence, lift a cannon to the fifth rank, and an engine finds it every time. A proven win nobody can reach is a curiosity. A win you can memorize is the game.',
        },
        {
          kind: 'paragraph',
          text: 'Two repairs beyond the pie rule are untested. Marking the general and giving the defender one move to answer would blunt the cannon threat directly. Or the starting array could move its central soldiers, since the threat exists only because Black’s soldier stands where a cannon needs its screen.',
        },
        { kind: 'sub-heading', text: 'Does Red have a forced win?' },
        {
          kind: 'paragraph',
          text: 'Everything above is a win rate, a statement about two particular engines. Whether the game is a first-player win under perfect play has an answer that does not depend on how well anything plays. What we have is a lower bound, no forced win within 13 plies. That rules out a cheap one, and half of the engine games were over by ply 28.',
        },
        {
          kind: 'paragraph',
          text: 'Two things make the question harder than it looks. Material is conserved, so there is no endgame database to build and nothing for a forward search to meet in the middle. Strategy stealing does not apply either: pieces move and never accumulate, so a first player cannot make an arbitrary move and then discard it. What helps is that games are short and always decisive, a shallow and sharply terminal tree, which is the shape proof-number search is good at.',
        },
        {
          kind: 'paragraph',
          text: 'The next rung is 14 plies. The proof splits across Red’s 42 first moves and runs them in parallel at almost no loss, because with no forced win no branch ever cuts off another. Splitting two plies deep gives 1,740 independent jobs, enough for a cluster. Proof-number search, which spends its effort on the narrowest part of the proof tree, is how Mark Watkins solved losing chess, and we have not implemented it yet.',
        },
        {
          kind: 'paragraph',
          text: 'A weak solution, or an ultra-weak one by an argument we have not thought of, would settle the pie rule question too: a proven first-player win is exactly the case the swap was invented for. The engine, the test harness, the 54 games and the full opening table are in one repository.',
        },
        {
          kind: 'cta',
          buttons: [
            { label: 'Check the numbers', href: EVIDENCE, emphasis: 'primary', external: true },
            { label: 'Learn xiangqi', href: '/rules/xiangqi', emphasis: 'secondary' },
          ],
        } as ArticleBlock,
      ],
    },
  ],
};
