import type { XiangqiReplaySpec } from '../../xiangqi-replay.js';
import type { Article } from '../types.js';

// GENERATED by scripts/player-page-article.mjs from docs-private/players/cao-yanlei/draft.md.
// Edit the draft and regenerate; an edit here is lost on the next run. Facts
// and their sources: facts.md beside the draft. Board specs: specs/<key>.json
// there (annotated-game-to-spec.mjs over deep annotate-game.mjs runs), with
// reviewed positives from positives.json and line verdicts from
// scripts/data/article-line-evals.json. Baked, not fetched: the page must not
// depend on a study still existing.

const G_M_139841: XiangqiReplaySpec = {
  "iccs": "h2e2 h9g7 g3g4 c6c5 h0g2 b9c7 i0h0 i9h9 b0a2 c9e7 h0h6 d9e8 b2d2 h7i7 h6h9 g7h9 a0b0 b7a7 g2f4 a9d9 f0e1 a7a3 b0b3 a3a4 b3b6 h9g7 b6c6 d9d4 f4g6 i7i3 g0i2 i3c3 c6b6 a4c4 b6b0 d4d3 a2c3 d3c3 c0a2 c4d4 b0b7 c3e3 e2f2 c7d9 b7b4 d4d6 g6f4 g7h5 g4g5 h5g3 f4g2 e3e5 b4b6 d6d4 g5g6 g3e4 e0f0 e5g5 d2e2 e4g3 e2b2 g5g6 b6a6 d4f4 f2c2 d9b8 a6a9 e8d9 a9a8 b8d7 b2b9 d9e8 a8c8 e8f7 c8d8 d7e5 b9b6 g6g5 d8d6 e5f3 c2f2 f3d2 f2e2 g3e2 b6e6 e7c9 d6d2 g5g2 a2c0 g2i2 c0e2 i2i0 f0f1 i0i3 f1f0 i3f3 f0e0 f3e3 e6f6 f4e4 f6f1 c9e7 e0f0 i6i5 e2c0 e3h3 f1f5 h3h0 f0f1 h0h5 f5f6 h5f5 d2f2 f5f2 e1f2 c5c4 f6a6 i5i4 a6a3 i4h4 f2e1 h4h3 c0e2 c4d4 f1f0 h3g3 e2c0 e7c5 a3b3 e4e8 b3a3 e8f8 f0e0 g3f3 c0e2 d4d3 a3b3 g9i7 b3a3 i7g5 a3b3 e9e8 b3a3 e8e7 a3b3 f3e3 e2g0 f8g8 g0i2 e3e2 e1f0 d3d2 b3b4 d2d1 b4g4 g8e8 f0e1 e2e1 d0e1 d1e1 e0d0 e8d8 g4b4 f7e8 b4b7 e7f7 i2g4 d8d9",
  "red": "Lại Lý Huynh",
  "black": "Cao Yanlei",
  "event": "2026 Chunqiu Daye Cup ten-game match",
  "resultText": "0-1",
  "annotations": {
    "byPly": {
      "27": {
        "glyph": "?!",
        "note": "inaccuracy: 6.1 win% given up, eval +0.00 after. The engine wanted the line in the sibling branch.",
        "line": "f4g6 i7h7 e2g2 d9d4 g0e2 a4g4 b6c6 c7d9 d2b2 d9b8 c6b6 b8d7 b6c6 g4g3 b2b9 d7b8 c6c8 h7h8 c8c9 d4d9 g6f4 e7c9 f4e6 b8c6 e6g7 h8g8 g2i2 c6a7",
        "lineEval": "⩲"
      },
      "31": {
        "glyph": "?!",
        "note": "inaccuracy: 5.2 win% given up, eval -0.59 after. The engine wanted the line in the sibling branch.",
        "line": "g6e7 g9e7 c6c7 d4g4 g0i2 g4g3 d2d3 g3e3 d3i3 g7f5 i3i4 a4h4 a2b4 e3i3 b4d5 i3i2 e1f0 h4h0 f0e1 i2i4 e2e7 e8d9 c0e2 h0h7 c7c6 f5e7 d5e7 f9e8 c6e6 h7f7 e7c8 e9f9",
        "lineEval": "="
      },
      "32": {
        "glyph": "!!",
        "note": "Brilliant: a piece offered and not recovered, confirmed along the engine's own line."
      },
      "49": {
        "glyph": "?",
        "note": "mistake: 10.9 win% given up, eval -2.25 after. The engine wanted the line in the sibling branch.",
        "line": "f4d5 e3d3 b4b6 d3d5 d2d6 a6a5 i2g0 i6i5 d6c6 h5f4 c6c8 d5h5 c8a8 h5h0 f2c2 h0g0 e1f0 e8d7 a8a9 e9e8 b6c6 e8f8 c2d2 f9e8 a9a8 f8f9 a8a9 f9f8 c6b6 f4d5",
        "lineEval": "∓"
      },
      "51": {
        "glyph": "?!",
        "note": "inaccuracy: 5.1 win% given up, eval -3.08 after. The engine wanted the line in the sibling branch.",
        "line": "f4d5 e3d3 d5f4 d3e3 a2c0 e3e4 b4b6 d6d4 f4g2 e4e5 i2g0 g3e4 g0e2 e4g5 b6a6 e5e3 a6a4 d4d5 f2f0 e3h3 a4g4 d5e5 f0g0 d9c7 g2h4 h3h0 e0f0 i6i5 h4i2 h0i0 d2a2 e5f5",
        "lineEval": "∓"
      },
      "59": {
        "glyph": "?!",
        "note": "inaccuracy: 7.9 win% given up, eval -4.07 after. The engine wanted the line in the sibling branch.",
        "line": "d2b2 g5g6 b6b4 e4f2 b4d4 g6f6 d4f4 f6f4 g2f4 f2d1 b2b6 i6i5 b6b5 d9c7 b5i5 d1c3 a2c0 e6e5 f4d3 e5e4 d3e5 c7e6 i2g4 a6a5 c0e2 a5a4 i5i4 e6g5 i4h4 c3d5 h4h5 d5e3",
        "lineEval": "−+"
      },
      "75": {
        "glyph": "?!",
        "note": "inaccuracy: 5.5 win% given up, eval -4.73 after. The engine wanted the line in the sibling branch.",
        "line": "a2c4 f4f3 i2g0 c5c4 c8c9 e9e8 c9c8 e8e9 c8c4 e6e5 c4f4 f3b3 f4f7 b3b0 f0f1 d7c5 f7f9 e9e8 f9f8 e8e9 e1d2 b0g0 f8f9 e9e8 f9f8 e8e9 c2c3 g3h5",
        "lineEval": "−+"
      },
      "84": {
        "glyph": "??",
        "note": "blunder: 17.9 win% given up, eval -2.63 after. The engine wanted the line in the sibling branch.",
        "line": "d2e4 b6e6 f9e8 d6d3 g3e2 e6e2 g5g2 a2c0 g2i2 d3e3 e4f6 e3b3 f4e4 b3e3 i2i0 f0f1 e4d4 e3e5 i0h0 e5c5 f6e4 c5c4 e4g3 e2g2 d4d5 c4c3 g3e4 c3e3",
        "lineEval": "−+"
      },
      "153": {
        "glyph": "?!",
        "note": "inaccuracy: 8.3 win% given up, eval #-17 after. The engine wanted the line in the sibling branch.",
        "line": "b3h3 d2d1 h3h7 f7e8 h7g7 e7d7 f0e1 e2e1 d0e1 d7e7 g7g6 d1e1 e0d0 e8d7 g6d6 g8b8 d6d3 e7f7 i2g4",
        "lineEval": "−+"
      }
    }
  }
};

const G_M_139842: XiangqiReplaySpec = {
  "iccs": "b0c2 c6c5 b2a2 b9c7 a0b0 a9b9 g3g4 b7b3 h2h4 h9g7 h0g2 g9e7 c3c4 g6g5 g4g5 c5c4 g5g6 h7h5 c0e2 c4c3 g6g7 i9g9 h4h3 c7d5 i0i1 g9g7 i1d1 b9b5 c2e1 g7g3 h3h1 d5f4 d1d4 f4h3 h1f1 b5f5",
  "red": "Cao Yanlei",
  "black": "Lại Lý Huynh",
  "event": "2026 Chunqiu Daye Cup ten-game match",
  "resultText": "0-1",
  "annotations": {
    "byPly": {
      "17": {
        "glyph": "?!",
        "note": "inaccuracy: 5.5 win% given up, eval -0.67 after. The engine wanted the line in the sibling branch.",
        "line": "h4g4 g7e8 i0h0 h7f7 h0h7 f7f3 g2f4 c4c3 c2a1 f3f2 e3e4 b9b5 f4e2 f2a2 e2c3 b5g5 b0b3 g5g4 c0a2 g4g3 a2c0 i9g9 c3b1 g3g0 b1d2 g9g3 h7h3 g3h3 b3h3 g0g1 a1b3 g1g4",
        "lineEval": "="
      },
      "25": {
        "glyph": "?!",
        "note": "inaccuracy: 7.2 win% given up, eval -1.77 after. The engine wanted the line in the sibling branch.",
        "line": "d0e1 b3b2 b0d0 b9b5 g2f4 d5f4 h3c3 b5b3 d0d4 f4g2 i0i2 g9g7 c3d3 g2e3 c2e3 b2i2 a2i2 e6e5 e3g4 e5e4 d4d6 f9e8 i2g2 h5g5 g2g5 g7g5 d3d5",
        "lineEval": "∓"
      },
      "29": {
        "glyph": "?",
        "note": "mistake: 12.9 win% given up, eval -3.66 after. The engine wanted the line in the sibling branch.",
        "line": "d0e1 g7g2 b0d0 g2g3 d1d5 b5d5 d0d5 g3h3 c2b0 b3e3 d5d6 h3f3 b0d1 e3i3 a2a6 f9e8 d1b2 c3b3 b2c0 f3e3 c0d2 i3i0 d6d4 e3e2",
        "lineEval": "∓"
      },
      "31": {
        "glyph": "?!",
        "note": "inaccuracy: 6.5 win% given up, eval -5.28 after. The engine wanted the line in the sibling branch.",
        "line": "d1d4 g3h3 b0c0 b3b0 c0b0 b5b0 d4d5 h5g5 d5d6 h3g3 d6e6 b0b1 e6d6 b1b5 a3a4 b5f5 g2i1 g3e3 a2a3 e3e4 i1h3 g5g8 d6c6 f5c5 c6g6 g8b8 g6b6 b8g8 a3a6",
        "lineEval": "−+"
      }
    }
  }
};

const G_M_139844: XiangqiReplaySpec = {
  "iccs": "h2e2 h7e7 h0g2 h9g7 i0h0 i9i8 b0c2 i8d8 g3g4 b9c7 c3c4 a9a8 g2f4 d8d1 b2b4 c6c5 c4c5 a8f8 f4g6 f8f6 g4g5 e6e5 b4h4 e5e4 a0b0 e4e3 c2e3 d1d3 b0b7 d3e3 f0e1 e3e2 g0e2 e7b7 h4e4 c9a7 c5c6",
  "red": "Cao Yanlei",
  "black": "Lại Lý Huynh",
  "event": "2026 Chunqiu Daye Cup ten-game match",
  "resultText": "1-0",
  "annotations": {
    "byPly": {
      "22": {
        "glyph": "?!",
        "note": "inaccuracy: 7.5 win% given up, eval +1.51 after. The engine wanted the line in the sibling branch.",
        "line": "d1g1 b4b6 e6e5 c5c6 f6c6 g6e5 c6e6 e5f3 g1c1 e2e6 g7e6 c0e2 c1c2 f0e1 c2c3 a0c0 c3e3 f3h4 c7d5 h4f5 e3e5 b6i6 e6g5 i6i5 e7f7 e1f2 d5e3 f5g3 g5h7 i5i4 h7g5 d0e1",
        "lineEval": "±"
      },
      "24": {
        "glyph": "?",
        "note": "mistake: 14.5 win% given up, eval +2.96 after. The engine wanted the line in the sibling branch.",
        "line": "c7e6 c5c6 e6c5 a0b0 b7b1 f0e1 c5d3 h4d4 d1c1 e2e5 d9e8 h0h2 b1b2 c2b4 c1c4 h2d2 c4b4 d2d3 b2e2 c0e2 b4b0 d4h4 f6c6 h4h6 c6c7 d3d6 c7b7 g5h5 b0b5 d6c6 c9a7",
        "lineEval": "±"
      }
    }
  }
};

const G_M_140016: XiangqiReplaySpec = {
  "iccs": "c3c4 h7e7 h0g2 h9g7 i0h0 i9h9 b0c2 b9a7 c0e2 h9h5 g3g4 b7d7 h2i2 h5h0 g2h0 a9b9 a0b0 b9b5 h0g2 g6g5 g4g5 b5g5 g2f4 a6a5 d0e1 f9e8 b0d0 a7b5 b2b0 g5f5 d0d5 f5d5 f4d5 d7d6 c2b4 b5d4 b4c6 e7e3 b0b4 e3d3 b4d4 d6d4 d5f4 d4e4 c6a5 g9e7 a5b7 d3d7 b7d6 e4e3 c4c5 d7d8 c5c6 e8d7 d6c4 e3e4 c6d6 d8g8 e0d0 g8d8 i2f2 e4e5 d0e0 d8g8 c4e3 d9e8 d6e6 g8i8 f4g6 e5g5 e6d6 i8i3 e3f5 g7i8 f2f4 i3i5 f5d4 i5h5 f4e4 h5h7 d4e6 g5h5 e6f4 h5h6 g6e5 e9f9 e4b4 i8g7 a3a4 e7g5 b4b3 c9e7 b3g3 g7h9 a4a5 h6h5 a5b5 h5h6 b5c5 h6f6",
  "red": "Cao Yanlei",
  "black": "Li Hanlin",
  "event": "2026 Baizuishan Cup",
  "resultText": "1-0",
  "annotations": {
    "byPly": {
      "54": {
        "glyph": "?!",
        "note": "inaccuracy: 5.0 win% given up, eval +1.66 after. The engine wanted the line in the sibling branch.",
        "line": "e3c3 a3a4 g7f5 i2i6 f5d4 e1d2 d4c6 f4e6 c6b4 e2c4 e8d7 d6e4 c3e3 e6g7 b4c2 g7f5 d8e8 f5e3 c2d4 a4a5 e8e4 f0e1 e4e6 e0d0 e6d6 e3d5 d4f3 i6e6 e9f9 g0e2 d9e8",
        "lineEval": "±"
      },
      "64": {
        "glyph": "?!",
        "note": "inaccuracy: 8.5 win% given up, eval +2.19 after. The engine wanted the line in the sibling branch.",
        "line": "e5f5 f2g2 d8f8 f4d5 e6e5 d5c3 d7e8 c4e5 f8i8 c3a4 i8i3 a4b6 i3i4 e5f3 f5f8 f3h4 i4i1 g2g6 i1g1 h4f5 e7g5 f5g3 i6i5 b6c4 c9e7 a3a4 i5i4 g6f6 i4i3 a4a5",
        "lineEval": "±"
      },
      "92": {
        "glyph": "?!",
        "note": "inaccuracy: 8.3 win% given up, eval +3.27 after. The engine wanted the line in the sibling branch.",
        "line": "h6h5 e5c4 h7h6 b3b7 g5e7 c4e3 h5g5 b7b9 c9a7 f4e6 h6f6 e6d4 g5i5 b9b7 a7c9 e3f5 g7h5 b7b5 i5f5 b5h5 f5g5 h5h3 i6i5 h3b3 e7g9 d4f3 g5g6 f3g5 f6f5 b3f3 f5e5 e0d0",
        "lineEval": "±"
      },
      "93": {
        "glyph": "?!",
        "note": "inaccuracy: 5.5 win% given up, eval +2.49 after. The engine wanted the line in the sibling branch.",
        "line": "d6d7 h6h5 e5g6 h5h4 d7d8 f9e9 f4d5 h4e4 d8e8 g7e8 g6e5 e8g9 b3g3 e9d9 a4a5 i6i5 e5g6 h7g7 d5e7 g5e7 g3g7 e7c9 g6i5 g9f7 i5g4 e4e7 g7g6 f7g5 g6d6 g5e4 d6d1 d9e9",
        "lineEval": "+−"
      },
      "96": {
        "glyph": "??",
        "note": "blunder: 22.9 win% given up, eval +6.07 after. The engine wanted the line in the sibling branch.",
        "line": "i6i5 d6e6 h7f7 e6e7 g5e7 f4g6 h9i7 g6h8 i7g8 e5g4 e7g5 g3g5 i5i4 h8g6 g8i7 g5f5 f9e9 g4h6 i7g6 h6i4 f7f8 a5b5 e8f7 f5d5 g6f4 d5d6 f4e6 i4h6 e6g5",
        "lineEval": "±"
      },
      "97": {
        "glyph": "??",
        "note": "blunder: 57.4 win% given up, eval -1.93 after. The engine wanted the line in the sibling branch.",
        "line": "g3f3 f9e9 f4h5 h7h6 f3e3 h9g7 h5g3 i6i5 e5d7 e9f9 d7b8 e7c9 e3b3 g5e7 b3b1 f9e9 b8a6 h6h9 g3e4 h9h3 e4f6 h3b3 f6g8 e9f9 e1f2 b3e3 e0d0 i5i4",
        "lineEval": "+−"
      },
      "98": {
        "glyph": "??",
        "note": "blunder: 41.8 win% given up, eval +2.95 after. The engine wanted the line in the sibling branch.",
        "line": "h5e5 d6e6 e5f5 e6f6 h7h1 g3a3 h9i7 b5b6 h1h6 b6b7 h6h1 b7c7 i6i5 f4d5 e7c5 a3f3 f9e9 d5c3 i7g8 c3a4 f5e5 f6e6 g8h6 f3f4 h1h5 a4b6 h6f5",
        "lineEval": "∓"
      }
    }
  }
};

const G_M_140458: XiangqiReplaySpec = {
  "iccs": "h2d2 h9g7 g3g4 i9h9 h0g2 h7i7 b0c2 c6c5 b2b6 g9e7 c0e2 b9a7 i0i1 a9a8 b6g6 b7c7 a0b0 c5c4 e2c4 a8d8 d2d6 h9h5 i1d1 a6a5 b0b6 g7h9 c2e1 i7g7 g2f4 h9f8 e1g2 f8g6 f4g6 c7c3 c4e2 h5c5 b6b0 a7b5 d1d3 c5f5 g2f4 d8d6 b0b5 c3e3 f0e1 d6d3 b5f5 e3e4 f5f7 d3g3 g0i2 g3h3 i2g0 h3g3 g0i2 g3h3 i2g0 g7g8 f7f8 g8g9 f4e6 d9e8 e6c7 h3h6 f8f6 g9i9 f6e6 e4b4 g6e7",
  "red": "Zhao Panwei",
  "black": "Cao Yanlei",
  "event": "2026 Chunqiu Daye Cup arena",
  "resultText": "1-0",
  "annotations": {
    "byPly": {
      "25": {
        "glyph": "?!",
        "note": "inaccuracy: 5.3 win% given up, eval -0.77 after. The engine wanted the line in the sibling branch.",
        "line": "b0b1 a7b5 d6c6 d8d1 b1d1 h5c5 d1d8 c7b7 d8c8 d9e8 c8b8 b7a7 d0e1 i6i5 c4e2 e6e5 b8b6 c5c3 c6f6 b5d4 c2a1 a5a4 a1c0 a7a3 c0b2 a3e3 g2e3 c3e3 b2c4 e3c3 b6d6 e5e4",
        "lineEval": "⩱"
      },
      "68": {
        "glyph": "??",
        "note": "blunder: 42.7 win% given up, eval +6.90 after. The engine wanted the line in the sibling branch.",
        "line": "i9i3 e6e4 h6g6 e4e6 g6e6 c7e6 i3b3 e1f0 b3b0 d0e1 i6i5 e6d4 b0b6 d4c6 e8d7 c6e5 f9e8 e5c4 b6b4 e0d0 i5i4 c4b6 i4h4 d0e0 e9d9 b6c4 c9a7 c4b6 a7c9",
        "lineEval": "="
      }
    }
  }
};

const G_M_143937: XiangqiReplaySpec = {
  "iccs": "c3c4 b7c7 g0e2 b9a7 b0c2 a9b9 c2d4 h7e7 d4e6 c7c8 b2a2 b9b5 h0g2 b5e5 e6c7 h9g7 i0h0 i9h9 a0b0 c6c5 b0b5 a6a5 b5a5 e7e3 g2e3 e5e3 a2a1 f9e8 a5a6 c5c4 a6g6 h9h7 a1e1 e3f3 h2h6 g9e7 e1h1 h7i7 h1g1 g7h9 h6h8 e8f9 g6d6 i7f7 d0e1 f3g3 g1g0 f7f3 h0h5 a7b9 c7d5 b9a7 d5f6 d9e8 f6e4 f3f4 e4f6 c8c6 f6d5 f4f8 d5b6 c4b4 i3i4 c6c3 h8h6 c3b3 h6e6 b3b0 c0a2 b0b6 d6b6 f8f6 h5h9 a7b9 h9h4 b9c7 e6c6",
  "red": "Cao Yanlei",
  "black": "Meng Chen",
  "event": "2026 League, stage one",
  "resultText": "1-0",
  "annotations": {
    "byPly": {
      "24": {
        "glyph": "?",
        "note": "mistake: 10.7 win% given up, eval +1.38 after. The engine wanted the line in the sibling branch.",
        "line": "h9h5 h2h4 f9e8 a3a4 c5c4 h4g4 e7e3 d0e1 e5a5 a4a5 h5h0 g2h0 g7i8 h0g2 e3e5 g2e3 c4d4 g4h4 a7c6 a5b5 d4d3 e3g4 i8g7 h4h3 e5h5 g4f6 c8d8",
        "lineEval": "⩲"
      },
      "32": {
        "glyph": "?!",
        "note": "inaccuracy: 5.1 win% given up, eval +1.86 after. The engine wanted the line in the sibling branch.",
        "line": "g7i8 c7d5 e3e5 d5b6 c8c0 d0e1 e5e2 h2h8 c0c3 a1a7 c9a7 h0h4 a7c9 g6i6 e2b2 b6c4 b2b0 e1d0 c3c0 e0e1 b0b1 e1e2 b1c1 c4d6 c0f0 i6i8 c1c3 d6c8 c3c8 h8c8",
        "lineEval": "±"
      },
      "34": {
        "glyph": "?!",
        "note": "inaccuracy: 6.6 win% given up, eval +2.31 after. The engine wanted the line in the sibling branch.",
        "line": "e3d3 h2h6 g7f9 e2g0 c9e7 c0a2 d3d7 c7a6 c8b8 e1e2 c4d4 d0e1 d4e4 h0h4 d7d4 a6c7 d4d7 c7a8 e4e3 e2c2 b8c8 c2c4 d7b7 c4e4 b7b0 e1d0",
        "lineEval": "±"
      },
      "42": {
        "glyph": "?",
        "note": "mistake: 12.4 win% given up, eval +3.62 after. The engine wanted the line in the sibling branch.",
        "line": "h9f8 g6g4 c4d4 h8g8 e8f9 g8c8 a7c8 g4d4 f3f1 g1g2 e7c5 c7a6 i7d7 d4c4 c9a7 a6b4 f1f2 g2g1 f2f1 g1g2 c8d6 c4c3 f1f2 g2g0 f2f4 b4d5 f4f5",
        "lineEval": "±"
      },
      "45": {
        "glyph": "?!",
        "note": "inaccuracy: 9.0 win% given up, eval +2.92 after. The engine wanted the line in the sibling branch.",
        "line": "g1e1 c4d4 d6d4 a7b9 c7d5 b9a7 e2c4 f3e3 c4a2 e3e5 d5b6 c8c6 d4d6 f9e8 e1e2 e5f5 d0e1 f7f6 h0h6 f6h6 d6h6 h9f8 h8i8",
        "lineEval": "+−"
      },
      "47": {
        "glyph": "?",
        "note": "mistake: 10.2 win% given up, eval +1.87 after. The engine wanted the line in the sibling branch.",
        "line": "g1i1 c4c3 i1i6 g3d3 d6d3 c3d3 h0h3 d3e3 i3i4 f7f3 h3h6 e3e2 c0e2 f3f8 i6i8 f8f7 i8i5 c8e8 h6d6 e8c8 a3a4 f9e8 i5i9 e7g9 d6g6 f7c7 g6g9 e8f9 g9f9 e9e8 f9h9",
        "lineEval": "±"
      },
      "48": {
        "glyph": "?",
        "note": "mistake: 11.1 win% given up, eval +3.38 after. The engine wanted the line in the sibling branch.",
        "line": "h9f8 a3a4 e7g5 c7a8 c8h8 h0h8 f8d7 a4a5 f9e8 a5a6 a7c8 d6c6 c8e7 c6c4 e7d5 a8c9 d7c9 c4c9 d5f4 c9c2 g5e7 c2d2 g3i3 g0g4 i3d3 d2c2 i6i5 a6b6 i5i4 b6b7 d3f3",
        "lineEval": "±"
      },
      "50": {
        "glyph": "?!",
        "note": "inaccuracy: 5.3 win% given up, eval +4.38 after. The engine wanted the line in the sibling branch.",
        "line": "h9f8 d6d8 f3f6 h8i8 f6c6 d8f8 c6c7 i8i9 g3g9 i9h9 d9e8 f8f3 c7c5 h5h7 c8c7 h7h8 c7c8 h8h7 c4c3 f3g3 g9h9 h7h9 c8b8",
        "lineEval": "+−"
      },
      "53": {
        "glyph": "?",
        "note": "mistake: 10.4 win% given up, eval +2.76 after. The engine wanted the line in the sibling branch.",
        "line": "d5b6 g3g8 h8c8 a7c8 b6c8 g8c8 h5h9 f3g3 g0h0 d9e8 h0h8 g3h3 h8c8 h3h9 a3a4 c4c3 c8a8 e8d9 a8a9 f9e8 d6i6 h9h4 a4a5 h4h5 a5a6 c3c2 i6i9 e8f9",
        "lineEval": "+−"
      },
      "58": {
        "glyph": "?!",
        "note": "inaccuracy: 8.5 win% given up, eval +4.11 after. The engine wanted the line in the sibling branch.",
        "line": "h9f8 h5h3 g3g1 h8i8 f8h7 f6d5 f4f7 d6d8 e7g9 i8h8 c8c5 h3h4 c5c6 a3a4 h7g5 h8h6 g5e6 d8d6 e6d4 h4g4 d4f3 g4c4 f7d7 h6e6",
        "lineEval": "±"
      },
      "59": {
        "glyph": "?!",
        "note": "inaccuracy: 5.2 win% given up, eval +3.24 after. The engine wanted the line in the sibling branch.",
        "line": "h8i8 c6f6 i8i9 f6f5 h5h9 f5i5 h9h4 i5i9 h4f4 a7b5 d6b6 i9i3 b6b5 i3a3 f4c4 e8d9 g0h0 g3h3 h0i0 f9e8 c0a2 h3i3 i0h0 i3h3 h0i0 a3a7",
        "lineEval": "+−"
      },
      "60": {
        "glyph": "?!",
        "note": "inaccuracy: 5.8 win% given up, eval +4.21 after. The engine wanted the line in the sibling branch.",
        "line": "f4f1 g0h0 h9f8 h0h4 g3g9 d5b6 c4d4 d6d4 c6e6 h4e4 e8d9 h8h7 g9g7 h7e7 c9e7 d4a4 f9e8 a4a7 g7h7 h5h7 f8h7 a7e7 h7g5 b6d5 f1f3 e4d4",
        "lineEval": "+−"
      },
      "75": {
        "glyph": "?!",
        "note": "inaccuracy: 7.5 win% given up, eval +3.40 after. The engine wanted the line in the sibling branch.",
        "line": "b6c6 c9a7 h9h7 b9d8 c6c3 g3g0 h7e7 f6e6 e7e6 d8e6 e2g0 e6c5 a2c4 b4a4 a3a4 c5a4 c3a3 a4b6 a3a7 e8d9 a7e7 f9e8 e7e6 b6c4 e6i6 e8f9 g0e2 c4b2",
        "lineEval": "+−"
      }
    }
  }
};

export const caoYanleiArticle: Article = {
  slug: "cao-yanlei",
  kind: 'article',
  publisher: 'mistboard',
  boardFamily: 'xiangqi',
  title: "Cao Yanlei 曹岩磊",
  seoTitle: "Cao Yanlei 曹岩磊: games, results, and analysis",
  summary: "Beat the world champion 12 to 8 in a ten-game match in January, then the rest of his season through the first stage of China's top league. Six games on the board, all 75 analysed.",
  showSummaryOnPage: false,
  status: "published",
  publishedAt: "2026-09-25",
  updatedAt: "2026-09-25",
  thumbnail: {
    kind: 'image',
    src: "/article-thumbs/cao-yanlei-2024-face.jpg",
    alt: "Cao Yanlei at the board.",
  },
  audience: "English-speaking xiangqi players who have never had a way to follow the Chinese pro circuit.",
  readNext: ["yin-sheng"],
  intro: [
    {
      kind: 'image-figure',
      src: "/article-thumbs/cao-yanlei-2024.jpg",
      alt: "Cao Yanlei in a dark suit and white shirt, looking down at the pieces during a tournament game.",
      caption: "Cao Yanlei at the board. Photo: 象棋字典 via Sohu.",
    },
    {
      kind: 'paragraph',
      text: "Cao Yanlei 曹岩磊 was abandoned in Sanmenxia, in Henan, before his first birthday. The couple who took him in raised him as their grandson, and the grandfather taught him xiangqi at four. He died before the boy turned six. At thirteen Cao was the youngest national master in China. Around 2011 Macau signed him, and for most of his twenties he played for Macau, often against the mainland's best: three World Championship bronzes, and in 2019 the world masters title, won against Wang Tianyi in the final. The Chinese press calls him the master of the sacrifice.",
    },
    {
      kind: 'paragraph',
      text: "He is registered to Hubei now and plays the league for Shanghai Jiahong. In January 2025 the Chinese Xiangqi Association's [match-fixing ruling](/blog/xiangqi-match-fixing) named him among the 41 people involved and gave him its lightest penalty, a public criticism, with no ban. This page is his 2026 so far.",
    },
  ],
  sections: [
    {
      heading: "2026 so far",
      blocks: [
        {
          kind: 'paragraph',
          text: "Ten events, from a ten-game match against the world champion in January to the first stage of China's top league in September. I ran all 75 games through the same engine analysis Mistboard gives your own games.",
        },
        {
          kind: 'table',
          headers: ["Event","Dates","W","D","L"],
          rows: [["Match vs Lại","Jan 3–5","3","6","1"],["Baizuishan Cup","Jan 6–7","7","3","0"],["Team championship","Mar 28–Apr 2","5","4","0"],["Chunqiu Daye arena","Apr 4–6","3","9","4"],["Xintai Cup","May 14","1","1","1"],["Gaogang Cup","Jun 4","0","1","1"],["Shanghai qualifying","Aug 9","1","0","1"],["League qualifier","Aug 17–19","4","1","0"],["Gulin open","Aug 23","1","0","1"],["League, stage one","Sep 14–18","4","11","1"]],
          highlightRows: [0],
          compact: true,
          caption: "His 2026 record by event.",
        },
      ],
    },
    {
      heading: "How he plays",
      blocks: [
        {
          kind: 'paragraph',
          text: "**He fights.** Watching him win the Wuyang Cup last year, the veteran Lü Qin told 羊城晚报 that Cao's style is combative and he never picks the safe line. Cao said much the same: he likes to attack, and to keep varying his play.",
        },
        {
          kind: 'paragraph',
          text: "**He plays for the win with red.** Most of his wins come with the red pieces, and he opens with the central cannon, the most direct move in the game, almost as often as with the quiet soldier push. Yin Sheng did not play the central cannon once in his unbeaten month. With black he is happy to draw.",
        },
        {
          kind: 'paragraph',
          text: "**Zhao Panwei is the problem.** Sixteen games against him this year, and one win. Half of all Cao's losses came against Zhao. Against everyone else he loses about one game in twelve.",
        },
        {
          kind: 'paragraph',
          text: "**The sacrifices are rarer than the name.** The engine confirms a real one, a piece offered and never won back, in six of his 75 games, about the same rate as Yin Sheng's unbeaten month. One is in the long match win with black below, a cannon left hanging on move 16. The oddest came against Zhao Panwei in April: he offered the same horse twice in four moves, and the game was drawn.",
        },
      ],
    },
    {
      heading: "The ten-game match",
      blocks: [
        {
          kind: 'paragraph',
          text: "The two had met before. In November 2016, at the Han Xin Cup in Sydney, Cao, playing for Macau, beat Lại Lý Huynh of Vietnam in the final, the first final of that event without a mainland Chinese player in it. Nine years later Lại became the first world champion from outside China, beating Yin Sheng in the final in Shanghai. So when a tea company booked the two of them into a room in Zhengzhou this January for ten rapid games over three evenings, Tuổi Trẻ in Vietnam billed it as China's revenge.",
        },
        {
          kind: 'paragraph',
          text: "The first evening was three draws. On the second Cao won twice, and this is the longer of the two, his only win of the match with black. Lại's soldier push on move 25 is the loose move, and Cao takes almost sixty more to collect.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_139841, startPly: 49, perspective: 'black' },
          caption: "Lại Lý Huynh vs Cao Yanlei, 4 January 2026. The board opens after red's 25th move, with Cao to play as black.",
        },
        {
          kind: 'paragraph',
          text: "Lại hit back on the last evening, and fast. Cao retreated a horse on move 15, the only real mistake of the game, and resigned three moves later. The Chinese sites filed it under 弃子速胜, a quick win with a sacrifice. For once the sacrifice was not Cao's.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_139842, startPly: 29, perspective: 'red' },
          caption: "Cao Yanlei vs Lại Lý Huynh, 5 January 2026. The board opens just after red's 15th move, with Lại to play.",
        },
        {
          kind: 'paragraph',
          text: "That left Cao needing a draw from the last game. He won it in 19 moves: Lại pushed his central soldier on move 12, and seven moves later he resigned.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_139844, startPly: 24, perspective: 'red' },
          caption: "Cao Yanlei vs Lại Lý Huynh, 5 January 2026, the last game. The board opens after black's 12th, with red to move.",
        },
      ],
    },
    {
      heading: "The Baizuishan Cup",
      blocks: [
        {
          kind: 'paragraph',
          text: "The next day he went straight into an open and won seven of his ten games. The game against Li Hanlin is the strange one. Cao had been better for most of it when Li's cannon went forward on move 48 and left him lost. With the win on the board, Cao slid a soldier sideways instead, and suddenly Li was better. Li gave it straight back with his next move and resigned. The board opens on the move Cao missed.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_140016, startPly: 96, perspective: 'red' },
          caption: "Cao Yanlei vs Li Hanlin, 7 January 2026. Red to move, and one move keeps the win.",
        },
      ],
    },
    {
      heading: "The Chunqiu Daye arena",
      blocks: [
        {
          kind: 'paragraph',
          text: "King of the hill: three players, one holding the arena, and each challenge is a single 20-minute game, then five-minute games until somebody wins. Everyone has four lives. In April Cao beat Zhao Panwei once and He Wenzhe twice, then lost to Zhao four times in a row, and his first season was over. In this one the position is level until Cao's cannon slides across on move 34. Zhao's reply ends it.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_140458, startPly: 67, perspective: 'black' },
          caption: "Zhao Panwei vs Cao Yanlei, 5 April 2026. The board opens after red's 34th, with black to find the move that holds.",
        },
      ],
    },
    {
      heading: "The league",
      blocks: [
        {
          kind: 'paragraph',
          text: "In August he topped the qualifier for China's top league, level with Hong Kong's Feng Jiajun, and took Shanghai Jiahong up with him. His one draw there was against Yin Sheng on the first day.",
        },
        {
          kind: 'paragraph',
          text: "At stage one in September he was second in the individual table after nine rounds, behind Wang Yubo, and lost one game in sixteen. On the last day he beat Meng Chen, the man who knocked him out of the 2023 national championship in the quarter-final. Meng's cannon raid on move 12 gave the game away, though it took Cao until move 39 to finish it.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_143937, startPly: 24, perspective: 'red' },
          caption: "Cao Yanlei vs Meng Chen, 17 September 2026. The board opens after black's 12th, with red to move.",
        },
      ],
    },
    {
      heading: "What's next",
      blocks: [
        {
          kind: 'paragraph',
          text: "The league's second stage is in October, and the national championship runs from November 21 to 29 in Changchun. He reached the quarter-final in 2023 and went out in the last sixteen in December. The association's ranking at the end of last year had him third in China.",
        },
      ],
    },
    {
      heading: "All 75 games",
      blocks: [
        {
          kind: 'paragraph',
          text: "Every game of the year is in a Mistboard study, with the engine's judgments and lines on each one, and 71 of the 75 are in the broadcast archive with the site's analysis. Sources: game records from dpxq.com, which may not hold every game of an event; analysis by Pikafish through Mistboard's review pipeline, September 2026.",
        },
        {
          kind: 'cta',
          buttons: [{"label":"Open the study","href":"/study/OI2crC9X","emphasis":"primary"},{"label":"The broadcast archive","href":"/broadcast/xiangqi","emphasis":"secondary"}],
          layout: "single-row",
        },
      ],
    },
  ],
};
