import type { XiangqiReplaySpec } from '../../xiangqi-replay.js';
import type { Article } from '../types.js';

// GENERATED by scripts/player-page-article.mjs from docs-private/players/lai-ly-huynh/draft.md.
// Edit the draft and regenerate; an edit here is lost on the next run. Facts
// and their sources: facts.md beside the draft. Board specs: specs/<key>.json
// there (annotated-game-to-spec.mjs over deep annotate-game.mjs runs), with
// reviewed positives from positives.json and line verdicts from
// scripts/data/article-line-evals.json. Baked, not fetched: the page must not
// depend on a study still existing.

const G_M_135652: XiangqiReplaySpec = {
  "iccs": "c3c4 b7c7 b0c2 c6c5 c2d4 c5c4 d4e6 g9e7 h0g2 h9f8 e6f4 b9a7 b2f2 f8d7 f4d5 c7c8 a0b0 a9b9 b0b9 c8c0 d0e1 a7b9 d5f6 i9i8 h2i2 h7g7 i0h0 d7c5 h0h6 g7g3 g0e2 c0b0 a3a4 b0b6 e2c4 b9c7 i2i6 c7d5 h6h9 d9e8 f6d5 i8i6 h9h3 b6b3 h3h4 g6g5 f2c2 i6d6 c2c5 d6d5 c5c8 d5d3 h4e4 b3b2 e4f4 d3e3 f4f2 b2b5 f2e2 e3b3 c8a8 b5d5 e2e4 d5d9 c4e2 b3b0 e1d0 g3a3 a8c8 a3a0 c8c0 a0c0 e2c0 b0c0 i3i4 c0c6 i4i5 d9d5 e4e5 d5c5 g2e3 c5c0 d0e1 c0b0 e0d0 b0b8 i5h5 e8d7 e5b5 b8d8 e1d2 c6e6 e3c4 g5g4 a4a5 a6a5 b5a5 g4f4 a5f5 d7e8 d2e1 e6e4 c4b6 e4b4 f5f6 b4b0 d0d1 b0b2 d1d0 e8d7 d0e0 b2b0 e1d0 b0d0 e0e1 d0d4 h5h6 f9e8 h6h7 d4d1 e1e0 d1d0 e0e1 d0f0 h7g7 f4f3 f6h6 f3f2 h6h9 e8f9 b6d7 f0f1 e1e0 f2e2",
  "red": "Mingjian Li",
  "black": "Lại Lý Huynh",
  "event": "2025 World Xiangqi Championship, round 3",
  "resultText": "0-1",
  "annotations": {
    "byPly": {
      "39": {
        "glyph": "??",
        "note": "blunder: 18.5 win% given up, eval -2.16 after. The engine wanted the line in the sibling branch.",
        "line": "i6g6 d5f6 g6b6 f6d7 b6e6 c5e6 h6e6 i8g8 e6d6 d9e8 f2d2 g3h3 d6h6 g8g3 d2d3 g3g2 d3h3 g2h2 i3i4 d7e5 h6e6 e5c4 e6e4 c4d6 e4d4 d6f5 d4f4 f5g7 h3h4 h2h3 i4i5 h3e3",
        "lineEval": "="
      },
      "119": {
        "glyph": "?!",
        "note": "inaccuracy: 6.2 win% given up, eval -6.33 after. The engine wanted the line in the sibling branch.",
        "line": "h6g6 d4e4 e1f1 f4g4 f6f3 e4b4 b6c8 b4b8 f3c3 b8b5 c8a9 b5g5 c3c9 e8d9 c9c2 g5g6 f1e1 d8e8 e1d1 g4g3 a9b7 g6b6 c2i2 e8f8 i2f2 b6b1 d1d0 b1c1",
        "lineEval": "−+"
      }
    }
  }
};

const G_M_135792: XiangqiReplaySpec = {
  "iccs": "h2f2 h9g7 c3c4 b7e7 b0c2 b9c7 h0g2 a9b9 a0b0 i9h9 i0h0 b9b5 h0h4 h7i7 h4h9 g7h9 c0e2 g6g5 b2a2 b5f5 d0e1 e7g7 b0d0 g7g3 d0d4 h9g7 a3a4 f5b5 a2a0 g7f5 d4h4 i7e7 a0c0 f5e3 c2e3 e7e3 g2h0 b5b0 c0d0 e3a3 f2f3 a3a0 f3c3 g3e3 h0g2 b0c0 c3b3 e3e5 b3e3 c0c4 d0d4 c4c0 d4d0 c0c3 d0d2 c6c5 e0d0 c9e7 h4d4 d9e8 d4d6 c3c0 d0d1 e5d5",
  "red": "Chong Heung Ming",
  "black": "Lại Lý Huynh",
  "event": "2025 World Xiangqi Championship, round 7",
  "resultText": "0-1",
  "annotations": {
    "byPly": {
      "33": {
        "glyph": "??",
        "note": "blunder: 19.8 win% given up, eval -3.04 after. The engine wanted the line in the sibling branch.",
        "line": "h4f4 e7f7 f4h4 f7f2 e1f2 b5b2 h4f4 b2c2 f4f5 g3g0 e2g0 c2c0 e0e1 c0a0 f5g5 c9e7 g5g6 a0a3 g2f4 a3e3 g0e2 e3e5 g6f6 d9e8 e1e0 e5e4 f2e1 c6c5 c4c5 e7c5 f4h5 g9e7",
        "lineEval": "⩱"
      },
      "34": {
        "glyph": "!",
        "note": "Great: the only move that punishes the error before it, and every alternative is at least a mistake worse."
      },
      "43": {
        "glyph": "?!",
        "note": "inaccuracy: 5.6 win% given up, eval -4.96 after. The engine wanted the line in the sibling branch.",
        "line": "h4f4 c9e7 h0i2 g3h3 f4h4 b0b3 e2c0 a0d0 h4h3 d0d1 f3c3 c7a8 e1d0 a8b6 i2g1 c6c5 c4c5 b6a4 c3c4 b3h3 g1h3 a4c5 h3f4 d1d4 f4d3 d9e8 d3c1 c5a4 e0e1",
        "lineEval": "−+"
      },
      "44": {
        "glyph": "!",
        "note": "Great: the only move that punishes the error before it, and every alternative is at least a mistake worse."
      },
      "56": {
        "glyph": "?!",
        "note": "inaccuracy: 5.1 win% given up, eval -4.04 after. The engine wanted the line in the sibling branch.",
        "line": "g9e7 h4b4 f9e8 b4b1 c6c5 b1a1 a0b0 a1a0 b0b2 a0b0 b2e2 g0e2 e5e2 e1d0 e2f2 e3e7 c9e7 g2f4 g5g4 b0b7 g4f4 b7c7 e9f9 c7b7 c3e3 f0e1 f2g2 b7e7",
        "lineEval": "−+"
      },
      "57": {
        "glyph": "?!",
        "note": "inaccuracy: 9.0 win% given up, eval -6.15 after. The engine wanted the line in the sibling branch.",
        "line": "e3e6 c3c0 d2d0 c7e6 h4e4 c0c4 d0d4 e5e2 g0e2 c4d4 e4e6 f9e8 g2e3 d4b4 e0d0 b4f4 d0e0 i6i5 e3d5 f4b4 e1f2 c9e7 d5f6 e8f7 e6b6 b4b0 e0e1 b0f0 f6e4 f0d0 b6b4",
        "lineEval": "−+"
      }
    }
  }
};

const G_M_135534: XiangqiReplaySpec = {
  "iccs": "c3c4 b7c7 b0a2 g6g5 h2e2 h9g7 h0g2 i9h9 i0h0 h7h3 b2b4 a9a8 g3g4 g5g4 b4g4 g9e7 a0b0 b9a7 b0b7 c7c4 g4e4 f9e8 e4e7 c9e7 g2f4 h3a3 h0h9 g7h9 b7e7 h9f8 e7g7 a8b8 g7g8 b8b3 g8f8 b3e3 f4d5 e3e5 f8f4 c6c5 f4g4 a7c8 d0e1 a3f3 d5c3 c4c0 c3e4 f3e3 g4g3 e5e4 a2c3 e4e5 e0d0 e3e1 f0e1 c0c2 g3g9 e8f9 g9g4 d9e8 g4b4 c8d6 b4b9 e8d9 b9b6 d6e8 b6a6 c5c4 c3a4 e8c7 a6d6 f9e8 a4b6 e5b5 e1f0 c4c3 d0e0 e9f9 e2d2 c2c0 d2a2 c3c2 a2a9 f9f8 a9c9 c0f0 c9c8 f8f9 c8c9 f9f8 c9c8 f8f9 c8c9 f9f8 c9c2 f0f6 b6d7 e8d7 d6e6 f6f7 e6c6 b5e5 e0d0 i6i5",
  "red": "Yin Sheng",
  "black": "Lại Lý Huynh",
  "event": "2025 World Xiangqi Championship, final",
  "resultText": "0-1",
  "annotations": {
    "byPly": {
      "22": {
        "glyph": "?",
        "note": "mistake: 11.2 win% given up, eval +1.27 after. The engine wanted the line in the sibling branch.",
        "line": "a8e8 a3a4 g7f5 b7b5 c4c5 b5b4 e8g8 e4g4 c5e5 b4f4 c6c5 f0e1 h3h4 g2h4 h9h4 h0h4 f5h4 e2e5 h4g2 f4f6 e6e5 c0e2 g2i3 g4g6 i3h5 f6a6 h5i3",
        "lineEval": "="
      },
      "26": {
        "glyph": "?!",
        "note": "inaccuracy: 7.1 win% given up, eval +2.36 after. The engine wanted the line in the sibling branch.",
        "line": "h3h7 f4g6 a8d8 h0h4 c4c5 b7a7 d8d3 h4h3 c5e5 g6e5 e6e5 a7c7 c6c5 a2c1 d3d6 c7c5 h7i7 h3h9 g7h9 c5e5 h9g7 e5e4 d6d5 e4h4 d5h5 h4h5 g7h5 e2e7 e8d7 c1d3 i7i3 d3c5",
        "lineEval": "±"
      },
      "31": {
        "glyph": "??",
        "note": "blunder: 19.4 win% given up, eval +0.34 after. The engine wanted the line in the sibling branch.",
        "line": "e2f2 c4c5 e7g7 e8f9 f0e1 a8e8 f2h2 f8h9 g7h7 h9f8 h7g7 e8b8 g7g8 c5f5 h2h9 e9e8 h9h8 e8e9 f4d5 b8b7 g8f8 b7h7 h8i8 h7i7 a2c3 a3a5 e3e4 e6e5 f8f5 i7i8 e4e5 i8d8",
        "lineEval": "±"
      },
      "40": {
        "glyph": "?!",
        "note": "inaccuracy: 9.4 win% given up, eval +1.61 after. The engine wanted the line in the sibling branch.",
        "line": "e5d5 f4c4 d5f5 c4e4 e9f9 d0e1 a6a5 e4e6 a7b5 e6e3 a3a4 e2f2 f9e9 f2h2 a4d4 e3g3 d4e4 c0e2 e9f9 g3e3 e4d4 a2b4 d4d7 b4c2 d7c7 h2f2 f9e9 e3g3 c7c2 f2c2 b5d4 g3d3",
        "lineEval": "⩲"
      },
      "41": {
        "glyph": "?!",
        "note": "inaccuracy: 8.5 win% given up, eval +0.64 after. The engine wanted the line in the sibling branch.",
        "line": "d5e7 e5g5 f4h4 e9f9 d0e1 a7c8 h4h9 f9f8 h9h8 f8f9 e7g8 a3e3 h8h3 g5g8 h3e3 g8g6 a2b4 c4f4 e3f3 f4f7 b4c6 c8d6 c6d8 e6e5",
        "lineEval": "±"
      },
      "49": {
        "glyph": "?!",
        "note": "inaccuracy: 9.2 win% given up, eval -0.27 after. The engine wanted the line in the sibling branch.",
        "line": "e4g5 c8d6 g5i6 d6c4 a2c3 e5f5 g4g6 e6e5 i6h4 f5f2 g6g3 f2f9 e0d0 c0c2 h4g2 e3f3 i3i4 a6a5 g3g4 f3d3 g2f4 d3e3 f4d5 f9f3 g4g9 e8f9 g9g6 f9e8 g6g5 c2b2 c3d1 b2b5",
        "lineEval": "⩲"
      },
      "54": {
        "glyph": "!!",
        "note": "Brilliant: a piece offered and not recovered, confirmed along the engine's own line."
      },
      "56": {
        "glyph": "?",
        "note": "mistake: 10.6 win% given up, eval +0.97 after. The engine wanted the line in the sibling branch.",
        "line": "c5c4 c3d1 c8d6 d1e3 d6e4 g3g9 e8f9 e3c4 e5d5 d0e0 d9e8 g9g4 e9d9 e2d2 e4d2 e1d2 e6e5 g0e2 c0c3 g4g5 d5d2 g5e5 d2d0 e0e1 d0d1 e1e0 c3f3 e5e6 d1d4 c4d6 d4d5 d6c8",
        "lineEval": "⩱"
      },
      "63": {
        "glyph": "?!",
        "note": "inaccuracy: 9.6 win% given up, eval -0.16 after. The engine wanted the line in the sibling branch.",
        "line": "b4b6 c5c4 c3a4 c4b4 b6d6 b4a4 d6c6 c2b2 c6c9 e8d9 c9d9 e9e8 d9d8 e8e9 d8b8 b2b4 b8b6 f9e8 b6b9 e8d9 b9d9 e9e8 d9d4 b4b5 d4a4 e5e3 a4a3 e3e4 a3a6 e8f8 a6d6 b5h5",
        "lineEval": "±"
      },
      "71": {
        "glyph": "?",
        "note": "mistake: 14.4 win% given up, eval -1.80 after. The engine wanted the line in the sibling branch.",
        "line": "a4b6 c7a6 b6d7 e9e8 d7e5 c4d4 e5c6 d4e4 c6d4 a6b4 d4e6 c2a2 e6g7 e8f8 g7e6 f8e8 e6g5 e4d4 g5i6 d4d3 i6g7 e8e7 d0e0 a2a0 e2h2 d9e8 g0e2 e8f7 g7f5 e7e8 i3i4 e8e9",
        "lineEval": "="
      },
      "72": {
        "glyph": "!",
        "note": "Great: the only move that punishes the error before it, and every alternative is at least a mistake worse."
      },
      "74": {
        "glyph": "??",
        "note": "blunder: 16.8 win% given up, eval -0.24 after. The engine wanted the line in the sibling branch.",
        "line": "e5e4 d6d2 c2c3 d0e0 e4d4 e0f0 c3f3 d2a2 f3f6 b6c8 e9f9 f0e0 d4d8 e2f2 f9e9 c8a9 d8b8 f2c2 c7b9 e1d0 c4c3 c2h2 c3d3 h2h1",
        "lineEval": "∓"
      },
      "75": {
        "glyph": "??",
        "note": "blunder: 26.7 win% given up, eval -3.58 after. The engine wanted the line in the sibling branch.",
        "line": "e2f2 e9f9 f2f0 c2b2 e1f2 e8f7 d6c6 b2b0 f0f1 b0b6 c6c7 d9e8 c7c9 f9f8 f1f0 c4d4 c9c6 b6b9 c6b6 b9d9 d0e0 b5e5 f2e1 e5f5 b6d6 f5f1 d6d4 e6e5 d4d6",
        "lineEval": "⩱"
      },
      "93": {
        "glyph": "?",
        "note": "mistake: 14.5 win% given up, eval #-1 after. The engine wanted the line in the sibling branch.",
        "line": "d6d4 b5b0 e0e1 b0b6 d4f4 e8f7 c8c2 c7d5 f4d4 b6b1 e1e0 b1b0 e0e1 b0b5 c2d2 d5b4 d4d9 f9f8 d2f2 b5f5 d9d8 f8f9 d8d9 f9f8 d9d2 f5f3 e1e0 b4d3 d2d3 f3f2 d3d8 f7e8",
        "lineEval": "−+"
      },
      "94": {
        "glyph": "?",
        "note": "mistake: 13.0 win% given up, eval -5.14 after. The engine wanted the line in the sibling branch.",
        "line": "f9f8",
        "lineEval": "−+"
      }
    }
  }
};

const G_M_139842: XiangqiReplaySpec = {
  "iccs": "b0c2 c6c5 b2a2 b9c7 a0b0 a9b9 g3g4 b7b3 h2h4 h9g7 h0g2 g9e7 c3c4 g6g5 g4g5 c5c4 g5g6 h7h5 c0e2 c4c3 g6g7 i9g9 h4h3 c7d5 i0i1 g9g7 i1d1 b9b5 c2e1 g7g3 h3h1 d5f4 d1d4 f4h3 h1f1 b5f5",
  "red": "Cao Yanlei",
  "black": "Lại Lý Huynh",
  "event": "2026 ten-game match, game 8",
  "resultText": "0-1",
  "annotations": {
    "byPly": {
      "17": {
        "glyph": "?!",
        "note": "inaccuracy: 5.5 win% given up, eval -0.67 after. The engine wanted the line in the sibling branch.",
        "line": "h4g4 g7e8 i0h0 h7f7 h0h7 f7f3 g2f4 c4c3 c2a1 f3f2 e3e4 b9b5 f4e2 f2a2 e2c3 b5g5 b0b3 g5g4 c0a2 g4g3 a2c0 i9g9 c3b1 g3g0 b1d2 g9g3 h7h3 g3h3 b3h3 g0g1 a1b3 g1g4",
        "lineEval": "="
      },
      "25": {
        "glyph": "?!",
        "note": "inaccuracy: 7.2 win% given up, eval -1.77 after. The engine wanted the line in the sibling branch.",
        "line": "d0e1 b3b2 b0d0 b9b5 g2f4 d5f4 h3c3 b5b3 d0d4 f4g2 i0i2 g9g7 c3d3 g2e3 c2e3 b2i2 a2i2 e6e5 e3g4 e5e4 d4d6 f9e8 i2g2 h5g5 g2g5 g7g5 d3d5",
        "lineEval": "∓"
      },
      "29": {
        "glyph": "?",
        "note": "mistake: 12.9 win% given up, eval -3.66 after. The engine wanted the line in the sibling branch.",
        "line": "d0e1 g7g2 b0d0 g2g3 d1d5 b5d5 d0d5 g3h3 c2b0 b3e3 d5d6 h3f3 b0d1 e3i3 a2a6 f9e8 d1b2 c3b3 b2c0 f3e3 c0d2 i3i0 d6d4 e3e2",
        "lineEval": "∓"
      },
      "30": {
        "glyph": "!",
        "note": "Great: the only move that punishes the error before it, and every alternative is at least a mistake worse."
      },
      "31": {
        "glyph": "?!",
        "note": "inaccuracy: 6.5 win% given up, eval -5.28 after. The engine wanted the line in the sibling branch.",
        "line": "d1d4 g3h3 b0c0 b3b0 c0b0 b5b0 d4d5 h5g5 d5d6 h3g3 d6e6 b0b1 e6d6 b1b5 a3a4 b5f5 g2i1 g3e3 a2a3 e3e4 i1h3 g5g8 d6c6 f5c5 c6g6 g8b8 g6b6 b8g8 a3a6",
        "lineEval": "−+"
      },
      "32": {
        "glyph": "!",
        "note": "Great: the only move that punishes the error before it, and every alternative is at least a mistake worse."
      }
    }
  }
};

const G_M_140313: XiangqiReplaySpec = {
  "iccs": "h2d2 g6g5 h0g2 h9g7 i0h0 i9h9 h0h4 h7i7 h4f4 b7d7 b0a2 b9c7 a3a4 c6c5 a2b4 g9e7 a0a1 a9a8 d2d6 f9e8 d6c6 h9f9 g3g4 g5g4 f4g4 g7f5 c3c4 c9a7 c4c5 a7c5 g2f4 d7d8 a1h1 f5d4 f4d5 d4b3 d0e1 i7f7 d5c7 f7c7 b4d5 d8d6 g4b4 c7d7 b4b3 d7d5 c6e6 d5f5 b3b7 d6c6 b7c7 a8b8 b2f2 c6c0 f2f9 c0c7 h1h9 f5f8 f9d9 f8f9 d9f9 b8b0 e1d0 e9d9 f9f2 d9d8 f2d2 b0b3 e3e4 c7a7 h9h5 a7a4 h5d5 e8d7 d5c5 b3d3 c5c8 d8d9 d0e1",
  "red": "Lại Lý Huynh",
  "black": "Zhao Panwei",
  "event": "2026 Five Rams Cup, semi-final",
  "resultText": "1-0",
  "annotations": {
    "byPly": {
      "19": {
        "glyph": "?!",
        "note": "inaccuracy: 5.7 win% given up, eval -0.07 after. The engine wanted the line in the sibling branch.",
        "line": "d2c2 f9e8 a1d1 a6a5 b2a2 h9f9 f4f9 g7f9 d1d4 f9g7 a2a5 i7h7 f0e1 h7h5 d4e4 g5g4 g3g4 h5a5 a4a5 a8a5 g2h4 a5a4 h4g6 d7d6 g6i7 d6d8 e4d4 d8a8 c2h2",
        "lineEval": "⩲"
      },
      "20": {
        "glyph": "?!",
        "note": "inaccuracy: 5.5 win% given up, eval +0.53 after. The engine wanted the line in the sibling branch.",
        "line": "c5c4 f4c4 c7d5 a1f1 f9e8 c4c5 c9a7 c5c4 d5b4 c4b4 a8c8 c0e2 c8c3 d6d2 h9f9 f1f9 e8f9 g3g4 g5g4 b4g4 a7c9 g4c4 c3b3 b2c2 i6i5 d2d1 g7i6 d1g1 f9e8 c2c0 d7b7 d0e1",
        "lineEval": "="
      },
      "22": {
        "glyph": "?!",
        "note": "inaccuracy: 5.7 win% given up, eval +1.12 after. The engine wanted the line in the sibling branch.",
        "line": "h9h3 g3g4 h3g3 g0e2 g5g4 f4g4 g3g4 e2g4 e8f9 a1d1 d9e8 d1d4 e7g9 g4e2 c9e7 f0e1 i6i5 d4g4 a6a5 b2a2 i7i8 g4e4 d7d8 c3c4 e6e5 e4g4 c5c4 g4c4 c7e6 a2a5 a8b8 a5i5",
        "lineEval": "⩲"
      },
      "34": {
        "glyph": "??",
        "note": "blunder: 15.4 win% given up, eval +3.85 after. The engine wanted the line in the sibling branch.",
        "line": "a6a5 b4a6 a8a9 a6c5 a9b9 b2f2 b9b6 c6i6 e6e5 i6i5 e7c5 h1h5 i7e7 i5f5 e5e4 f4e2 e4f4 g4f4 d8d5 h5h4 b6e6 f0e1 e6e3 f5c5 f9f4 h4f4 a5a4 f4f5",
        "lineEval": "±"
      },
      "35": {
        "glyph": "?!",
        "note": "inaccuracy: 5.2 win% given up, eval +3.02 after. The engine wanted the line in the sibling branch.",
        "line": "b2f2 d4f3 g4g7 d8d7 g7g3 i7f7 b4d5 a8b8 d5c7 b8b3 h1h3 b3e3 g0e2 f9g9 g3g9 e7g9 c7a8 c5a7 c6i6 d7d2 f2f1 d2d1 i6i9 e8f9",
        "lineEval": "+−"
      },
      "72": {
        "glyph": "?!",
        "note": "inaccuracy: 5.6 win% given up, eval +10.18 after. The engine wanted the line in the sibling branch.",
        "line": "e7g9 h5d5 e8d7 d5d4 b3i3 e4e5 i3a3 d4c4 d8e8 d2e2 e8f8 c4f4 f8e8 e6d6 g9e7 e5e6 a3e3 e6f6 e8e9 f4b4 d7e8 b4b9 e8d9 d0e1 e3e4 b9b4 e4e3 d6i6",
        "lineEval": "+−"
      }
    }
  }
};

export const laiLyHuynhArticle: Article = {
  slug: "lai-ly-huynh",
  kind: 'article',
  publisher: 'mistboard',
  boardFamily: 'xiangqi',
  title: "Lại Lý Huynh 赖理兄",
  seoTitle: "Lại Lý Huynh 赖理兄, the world xiangqi champion: games and analysis",
  summary: "The first world champion from outside China, unbeaten in Shanghai and winner of the final with black. His title run and the year since, five wins on the board, 38 games analysed.",
  showSummaryOnPage: false,
  status: "published",
  publishedAt: "2026-10-02",
  updatedAt: "2026-10-02",
  thumbnail: {
    kind: 'image',
    src: "/article-thumbs/lai-ly-huynh-2026-face.jpg",
    alt: "Lại Lý Huynh at the board.",
  },
  audience: "English-speaking xiangqi players, and Vietnamese fans who want his games in one place with analysis.",
  readNext: ["yin-sheng","cao-yanlei"],
  intro: [
    {
      kind: 'image-figure',
      src: "/article-thumbs/lai-ly-huynh-2026.jpg",
      alt: "Lại Lý Huynh in a white team shirt, arms folded, looking down at the board during a game.",
      caption: "Lại Lý Huynh at the Five Rams Cup, Guangzhou, February 2026. Photo: Vietnam Xiangqi Federation, via Thanh Niên.",
    },
    {
      kind: 'paragraph',
      text: "Lại Lý Huynh 赖理兄 is the world champion. In Shanghai last September he went through the World Xiangqi Championship without losing a game and won the final against China's Yin Sheng with the black pieces, the first player from outside China to take the title. The Chinese press calls him Vietnam's king of xiangqi, 越南棋王. At home his fans call him Nam Phương công tử, the young master from the South.",
    },
    {
      kind: 'paragraph',
      text: "He was born in 1990 in Vĩnh Long, in the Mekong Delta, and learned the game watching his father play. He has won Vietnam's national championship six times and holds the WXF's International Grandmaster title. In 2016 he became the first foreign player in China's top league, for Hangzhou, and in 2023 he won the league with them. In February he was the first wildcard ever to reach the final of the Five Rams Cup, China's invitation event for its national champions.",
    },
    {
      kind: 'paragraph',
      text: "This page is his year as champion: the title run, the year since, and five of his wins on the board. I ran the 38 individual games we hold through the same engine analysis Mistboard gives your own games.",
    },
  ],
  sections: [
    {
      heading: "How he plays",
      blocks: [
        {
          kind: 'paragraph',
          text: "**He wins with black.** Five of his six wins in Shanghai came with the black pieces, the side that moves second, the final among them. Across the 38 individual games we hold he won eight with black and three with red. With red he mostly draws, thirteen of his eighteen red games.",
        },
        {
          kind: 'paragraph',
          text: "**He opens with the Cross-Palace Cannon.** In eleven of his eighteen red games his first move slid a cannon across to the far side of his own palace. It is a quieter start than the central cannon, and it leaves the game to be won later.",
        },
        {
          kind: 'paragraph',
          text: "**He was precise when it counted.** His median accuracy across the nine games in Shanghai was 98. The engine confirms three sacrifices in his year, a piece offered and never won back, and one of them came in the world final.",
        },
        {
          kind: 'paragraph',
          text: "**He learned from China's best.** \"The league gave me a very valuable chance to learn,\" he told 羊城晚报 in February. \"I could play and at the same time study how China's top players play.\" He has trained with engines since 2005.",
        },
      ],
    },
    {
      heading: "The world title",
      blocks: [
        {
          kind: 'paragraph',
          text: "He had been one game from the title before. In Houston in 2023 he reached the final against Meng Chen, drew the slow game and lost the rapid tiebreak. Two years later the championship ran in Shanghai from 22 to 27 September, eight rounds and then a final between the top two. He won five and drew three, against Yin Sheng on the first day, Meng Fanrui and Malaysia's Li Dezhi, and finished level with Yin Sheng on 13 points.",
        },
        {
          kind: 'table',
          headers: ["Round","Opponent","Colour","Result"],
          rows: [["1","Ryan Emmanuel Haris (East Malaysia)","Black","Win"],["2","Yin Sheng (China)","Red","Draw"],["3","Mingjian Li (USA)","Black","Win"],["4","Tony Fung Ga Zen (Hong Kong)","Red","Win"],["5","Calvin Tay Yelin (East Malaysia)","Black","Win"],["6","Meng Fanrui (China)","Red","Draw"],["7","Chong Heung Ming (Philippines)","Black","Win"],["8","Li Dezhi (Malaysia)","Red","Draw"],["Final","Yin Sheng (China)","Black","Win"]],
          highlightRows: [8],
          compact: true,
          caption: "His world championship, round by round.",
        },
        {
          kind: 'paragraph',
          text: "In round three he met the United States' Mingjian Li, who held him level for nineteen moves. Li's chariot push on move 20 let it go. Lại finished at 98 percent accuracy and needed another 47 moves to bring it home.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_135652, startPly: 39, perspective: 'black' },
          caption: "Mingjian Li vs Lại Lý Huynh, 23 September 2025, round 3. The board opens after red's 20th move, with Lại to play as black.",
        },
        {
          kind: 'paragraph',
          text: "In round seven Chong Heung Ming of the Philippines slid his cannon across on move 17. Lại's horse jumped into the centre the same move, the engine's own first choice, and his cannon followed it in. Chong resigned after move 32.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_135792, startPly: 33, perspective: 'black' },
          caption: "Chong Heung Ming vs Lại Lý Huynh, 25 September 2025, round 7. The board opens after red's 17th move, with Lại to play as black.",
        },
        {
          kind: 'paragraph',
          text: "The final was one game, Yin Sheng with red. Yin Sheng pressed early, and by move 27 it was level again. Lại pushed his central cannon into Yin Sheng's camp, a piece offer the engine rates as the best move on the board. Yin Sheng took it, and the engine still called the game level. On move 38 his advisor stepped back. From there Lại's soldier on the third file walked down the board, and Yin Sheng resigned after move 52.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_135534, startPly: 53, perspective: 'black' },
          caption: "Yin Sheng vs Lại Lý Huynh, 27 September 2025, the final. The board opens after red's 27th move, with Lại to play as black.",
        },
        {
          kind: 'paragraph',
          text: "Yin Sheng was born in 2005. A year later he went 31 games without a loss and has [his own page](/blog/yin-sheng). The championship's history, and Lại's earlier games in it, are on the [world championship page](/blog/xiangqi-world-championship).",
        },
      ],
    },
    {
      heading: "The year since",
      blocks: [
        {
          kind: 'paragraph',
          text: "At home the title made him a national figure. In June the state awarded him the First-Class Labour Order, and in April he won the rapid title at the national championship. Most of his games this year, though, were against China's best on their ground, and those are in the table below.",
        },
        {
          kind: 'table',
          headers: ["Event","Dates","W","D","L"],
          rows: [["World Rapid Open, Shanghai","Sep 26, 2025","2","2","2"],["Match vs Cao Yanlei, Zhengzhou","Jan 3–5","1","6","3"],["Dukang arena final, Zhengzhou","Jan 9–10","0","3","4"],["Five Rams Cup, Guangzhou","Feb 25–Mar 1","4","5","1"],["Chunqiu Daye arena","May","0","0","4"],["Vietnam vs Guangdong, Đà Nẵng","Jul","2","7","1"]],
          highlightRows: [3],
          compact: true,
          caption: "The year since the title, events with a complete record.",
        },
        {
          kind: 'paragraph',
          text: "In January a tea company booked him and Cao Yanlei into a room in Zhengzhou for [ten rapid games](/broadcast/xiangqi/2026-chunqiu-dayie-ten-game-match) over three evenings, a rematch of their 2016 Han Xin Cup final in Sydney. Cao won the match 12 to 8, and [his page](/blog/cao-yanlei) tells it from his side. Lại's win was game eight, with black, in 18 moves. Cao's horse stepped back on move 15; Lại's chariot went straight up the file in reply, his horse followed, and Cao resigned three moves later.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_139842, startPly: 29, perspective: 'black' },
          caption: "Cao Yanlei vs Lại Lý Huynh, 5 January 2026, game 8 of the match. The board opens after red's 15th move, with Lại to play as black.",
        },
        {
          kind: 'paragraph',
          text: "The Five Rams Cup in Guangzhou (五羊杯) invites China's national champions. In February it gave its first wildcard to Lại, and he reached the final. In the semi-final he beat Zhao Panwei, the opponent Cao Yanlei found hardest all year, winning the first game with red and drawing the second. Zhao's horse jumped forward on move 17; Lại's horses came forward and Zhao resigned after move 40. Cheng Yudong beat him in the final, a draw and then a loss. The [whole event](/broadcast/xiangqi/2026-wuyang-cup) is in the broadcast archive.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_140313, startPly: 34, perspective: 'red' },
          caption: "Lại Lý Huynh vs Zhao Panwei, 28 February 2026, Five Rams Cup semi-final, game 1. The board opens after black's 17th move, with Lại to move.",
        },
        {
          kind: 'paragraph',
          text: "\"Since I won the world championship, more people in Vietnam follow xiangqi,\" he said in Guangzhou, \"and more of them have started playing.\"",
        },
      ],
    },
    {
      heading: "All 38 games",
      blocks: [
        {
          kind: 'paragraph',
          text: "Every game on this page is in a Mistboard study with the engine's judgments and lines, and 15 of them are in the broadcast archive with the site's analysis. Sources: game records from dpxq.com, which may not hold every game of an event; the round table from the WXF results book; the Five Rams Cup and arena records from VnExpress, and the Vietnam vs Guangdong record from VnExpress and 象棋热情; analysis by Pikafish through Mistboard's review pipeline, October 2026.",
        },
        {
          kind: 'cta',
          buttons: [{"label":"Open the study","href":"/study/lFuIFiQp","emphasis":"primary"},{"label":"His games in the archive","href":"/players/lai-ly-huynh","emphasis":"secondary"}],
          layout: "single-row",
        },
      ],
    },
  ],
};
