import type { XiangqiReplaySpec } from '../../xiangqi-replay.js';
import type { Article } from '../types.js';

// GENERATED by scripts/player-page-article.mjs from docs-private/players/tony-fung-ga-zen/draft.md.
// Edit the draft and regenerate; an edit here is lost on the next run. Facts
// and their sources: facts.md beside the draft. Board specs: specs/<key>.json
// there (annotated-game-to-spec.mjs over deep annotate-game.mjs runs), with
// reviewed positives from positives.json and line verdicts from
// scripts/data/article-line-evals.json. Baked, not fetched: the page must not
// depend on a study still existing.

const G_M_142503: XiangqiReplaySpec = {
  "iccs": "h2e2 b9c7 h0g2 h7f7 i0h0 h9g7 c3c4 i9i8 g3g4 i8d8 b2c2 d8d4 e2f2 d4g4 h0h2 e6e5 c0e2 g4d4 c2c0 b7b1 a0a1 a9b9 h2h1 b1b3 b0c2 b3c3 c0c3 c7e6 c3c6 d4d7 c6g6 g9i7 f2f6 b9b2 a1d1 d7e7 c2d4 f7f8 d4e6 g7e6 d1d6 f8g8 g6e6 e7f7 h1h6 b2b8 e3e4 g8g3 e4e5 g3b3 e5f5 b3b0 e2c0 b0b6 e6e2",
  "red": "Tony Fung Ga Zen",
  "black": "Wang Dayu",
  "event": "2026 China league qualifier, round 1",
  "resultText": "1-0",
  "annotations": {
    "byPly": {
      "26": {
        "glyph": "??",
        "note": "blunder: 32.6 win% given up, eval +4.96 after. The engine wanted the line in the sibling branch.",
        "line": "d4d3 a1d1 b3e3 c2e3 d3e3 g2h4 c7e6 c0c6 f7b7 c6b6 b7a7 d1d6 e6g5 f0e1 b9b7 e2c0 b7f7 g0e2 e3h3 h1h3 g5h3 d6g6 h3f2 e1f2 e5e4 c4c5 a7a8 b6b8 f7b7 b8d8 b7f7 d0e1",
        "lineEval": "⩲"
      }
    }
  }
};

const G_M_142542: XiangqiReplaySpec = {
  "iccs": "h2e2 h7e7 h0g2 h9g7 i0h0 g6g5 c3c4 b9c7 b0c2 b7b3 c2b4 i9i8 a0a1 i8d8 f0e1 b3g3 a1c1 c9a7 g0i2 d9e8 h0h4 d8d6 a3a4 a9d9 e2d2 e7d7 d2d7 d9d7 c0e2 e6e5 b2c2 c6c5 c2d2 d6e6 c4c5 a7c5 c1c5 c7d9 b4c2 d7d6 h4h3 g5g4 e2g4 g7f5 e3e4 d6c6 c5c6 e6c6 c2d4 c6h6 h3h6 f5h6 e4e5 d9b8 g2e3 b8d7 e5d5 d7f6 d2e2 g9e7 d5d6 g3h3 e2e7 e8f7 g4e2 f6e4 e7e5 e9d9 d4c6 h6f5 e3g4 h3h8 e5d5 d9e9 g4e5 f5h6 e5d7 e9e8 d6e6",
  "red": "Tony Fung Ga Zen",
  "black": "Lu Hao",
  "event": "2026 China league qualifier, round 3",
  "resultText": "1-0",
  "annotations": {
    "byPly": {
      "32": {
        "glyph": "??",
        "note": "blunder: 22.6 win% given up, eval +3.14 after. The engine wanted the line in the sibling branch.",
        "line": "c7d9 c2a2 d7c7 a2a6 d6d5 a6a5 d9e7 c4c5 d5c5 c1c5 c6c5 a5e5 c5c4 h4c4 c7c4 e2c4 g3h3 c4e2 h3h5 e3e4 a7c9 e1d2 g7f5 d0e1 f5g3 e5h5 g3h5 e4e5 h5g3 e5e6 e7g8 b4d5",
        "lineEval": "⩲"
      },
      "33": {
        "glyph": "?!",
        "note": "inaccuracy: 6.9 win% given up, eval +2.19 after. The engine wanted the line in the sibling branch.",
        "line": "c2d2 d7e7 c4c5 a7c5 c1c5 g7e6 c5c4 e7f7 h4h3 g3f3 h3h6 e5e4 e3e4 d6d4 e4e5 d4c4 e2c4 e6c5 h6c6 f3c3 d2c2 c7d9 e5d5 f7b7 d5c5 b7b4 g2e3 d9e7 c6e6 c3b3 c4e2 b3b0",
        "lineEval": "+−"
      },
      "34": {
        "glyph": "?",
        "note": "mistake: 11.0 win% given up, eval +3.79 after. The engine wanted the line in the sibling branch.",
        "line": "d6f6 c4c5 a7c5 h4h3 g5g4 c1c5 g7e6 c5c4 f6f3 h3h6 f3f4 i2g4 f4c4 e2c4 g3f3 g2f4 e6g5 h6c6 e5e4 e3e4 f3e3 d2e2 e3b3 e2b2 d7f7 c4e2 f7f4 c6c7 g5e4 b4d5",
        "lineEval": "+−"
      },
      "40": {
        "glyph": "?",
        "note": "mistake: 10.9 win% given up, eval +4.87 after. The engine wanted the line in the sibling branch.",
        "line": "d7d3 c2d4 e6e7 d4c6 e7c7 c5e5 c7c6 e5g5 g7f5 h4f4 f5d6 g5g3 d6c4 d2d9 e9d9 g3g9 c4e5 g9g5 e5d7 f4b4 c6b6 b4b6 d7b6 g5g6 b6a4 g6a6 a4c3 a6i6 d3d5 e2g0 d9e9",
        "lineEval": "+−"
      },
      "72": {
        "glyph": "?!",
        "note": "inaccuracy: 6.4 win% given up, eval +6.14 after. The engine wanted the line in the sibling branch.",
        "line": "h3c3 c6b8 d9e9 b8a6 c3a3 a6b8 e4c5 b8d7 c5d7 d6d7 e9e8 g4f6 a3h3 a4a5 h3h6 a5b5 h6g6 b5c5 e8f8 d7d8 f9e8 i2g4 f8f9 e5e4 g6g7 c5d5 g7g5 e0f0 g5g7 d5e5 f5g3 e4f4",
        "lineEval": "+−"
      },
      "76": {
        "glyph": "?!",
        "note": "inaccuracy: 5.3 win% given up, eval +9.20 after. The engine wanted the line in the sibling branch.",
        "line": "f5h4 e5d7 h8d8 c6d8 f9e8 d7b6 e4d6 d5e5 e9f9 d8e6 f9e9 b6d7 e9d9 d7b8 d9e9 i2g4 h4g6 e5e3 g6e5 b8a6 i6i5 a6c7 e5d3 a4a5 d6e4 e1d2 e4f6",
        "lineEval": "+−"
      }
    }
  }
};

const G_M_140266: XiangqiReplaySpec = {
  "iccs": "h2e2 h9g7 g3g4 i9h9 h0g2 h7i7 b0c2 d9e8 b2a2 b7f7 a0b0 b9c7 i0h0 h9h0 g2h0 c9e7 h0g2 a9d9 e2f2 g6g5 g4g5 e7g5 b0b4 g7f5 f2f7 e8f7 c3c4 g5e7 b4b7 f7e8 c2b4 f5d4 b4a6 c7b9 b7b8 d4f3 a2f2 i7i8 b8b5 b9a7 b5f5 f3g5 g2f4 e8f7 f2e2 d9d6 f5d5 d6d5 f4d5 i8i3 a3a4 f9e8 d0e1 i3i4 d5f4 i4c4 f4e6 g5f3 e1f2 c4h4 e2b2 f3e5 c0e2 e5d3 b2d2 c6c5 e6f4 d3b2 a4a5 c5c4 d2d6 a7c6 a5b5 c6d4 d6b6 b2d1 f0e1 c4c3 b5a5 d1e3 b6h6 d4b3 a5b5 b3c1 e0f0 e3g4 f4d3 c3d3 e2g4 h4h5 e1d2 d3e3 f2e1 e3f3 f0f1 c1b3 e1d0 b3d2 f1e1 d2e4 a6b4 h5e5 e1d1 e4c3 b4c2 c3b5 d0e1 i6i5 d1d0 i5i4 h6a6 i4h4 g4i2 b5c3 a6a1 h4h3 a1c1 c3e4 e1f0 e5d5 d0e0 e4f2 c1f1 f2d3 c2e1 d3e5 e1c2 e5d3 c2e1 d3e1 f0e1 f3e3 e0d0 e7c5 f1f4 e8f9 f4e4 h3g3 d0e0 d5d8 e0d0 e9d9 e4e6 e3d3 e6d6 d9e9 d6d4 g3g2 i2g4 g2g1 g0e2 g1f1 d0e0 d8e8 d4e4 e9d9 e4e6 g9i7 e6e4 e8e5 e1f2 d3d2",
  "red": "Chao Yi-fan",
  "black": "Tony Fung Ga Zen",
  "event": "2026 Five Rams Cup, Hong Kong, Macau and Taiwan qualifier",
  "resultText": "0-1",
  "annotations": {
    "byPly": {
      "79": {
        "glyph": "?!",
        "note": "inaccuracy: 5.6 win% given up, eval -0.77 after. The engine wanted the line in the sibling branch.",
        "line": "f4g6 h4h0 g0i2 d1e3 b6i6 e7g5 g6e5 e3g2 e2g4 d4b5 i6i4 h0h6 a6b4 g9e7 e5f3 h6b6 i2g0 g2i3 g0i2 e9d9 e1d2 b6e6 e0d0 e6f6 f2e1 f6d6 d0e0 d6e6 e1f2 b5d6 e0d0 e6h6",
        "lineEval": "="
      },
      "83": {
        "glyph": "?!",
        "note": "inaccuracy: 8.2 win% given up, eval -1.70 after. The engine wanted the line in the sibling branch.",
        "line": "a6c7 b3a5 c7b5 c3c2 f4g6 h4h0 g0i2 e7c5 h6h9 g9e7 h9h3 e3d5 e0d0 a5b3 g6i7 b3d4 i7g8 e9f9 b5c3 d5f4 e2g4 e8d7 c3e4 i6i5 h3h5 f4g6 h5f5 f7e8 g8f6 f9e9 f5f3 i5i4",
        "lineEval": "⩱"
      },
      "93": {
        "glyph": "?!",
        "note": "inaccuracy: 5.9 win% given up, eval -3.16 after. The engine wanted the line in the sibling branch.",
        "line": "f0f1 c1b3 h6e6 h5f5 f1e1 b3d4 a6c5 e9d9 e6d6 d4b5 e1e0 i6i5 f2e1 i5i4 g4e2 f5e5 c5b7 i4h4 d6a6 e3d3 e0f0 h4h3 e2c0 h3g3 a6d6 d3e3 b7c5 g3f3 g0e2 e5f5 f0e0 f5d5",
        "lineEval": "∓"
      },
      "132": {
        "glyph": "?!",
        "note": "inaccuracy: 5.9 win% given up, eval -3.49 after. The engine wanted the line in the sibling branch.",
        "line": "h3g3 f1h1 d5e5 e0d0 f3e3 e1d2 g3g2 h1a1 g2f2 d0d1 e9d9 d1d0 f2f1 i2g4 e7c5 a1d1 d9e9 d1c1 e8d7 c1a1 e3f3 a1e1 f1e1 d2e1 e5e6 d0d1 e6e8 e1d2",
        "lineEval": "−+"
      },
      "141": {
        "glyph": "?!",
        "note": "inaccuracy: 6.6 win% given up, eval -5.48 after. The engine wanted the line in the sibling branch.",
        "line": "i2g4 e3d3 e4e6 e9d9 e6g6 d8e8 e0f0 g3f3 g6h6 e8e6 h6h1 d9e9 h1h5 e9e8 h5h1 g9i7 h1g1 e6f6 g1f1 f6g6 g0i2 d3e3 f0e0 g6e6 f1f0 e3d3 e0d0",
        "lineEval": "−+"
      }
    }
  }
};

const G_M_140287: XiangqiReplaySpec = {
  "iccs": "c3c4 c9e7 b0c2 g6g5 h2e2 h9g7 h0g2 i9h9 b2a2 b9c7 a0b0 a9b9 i0h0 h7h6 a2a6 b7b3 a6a4 h6g6 h0h9 g7h9 c2d4 h9g7 e2a2 b3g3 b0b9 c7b9 g0e2 b9d8 a2b2 d9e8 a4a7 g6h6 a7c7 c6c5 c4c5 e7c5 c7c8 g3a3 g2f4 a3a4 f4d5 e6e5 d5c7 h6e6 d4c2 e6c6 c8c6 d8c6 c2d4 c6e7 d4e6 g7e6 c7e6 a4a3 e6g5",
  "red": "Meng Fanrui",
  "black": "Tony Fung Ga Zen",
  "event": "2026 Five Rams Cup, final stage",
  "resultText": "1/2-1/2",
  "annotations": {
    "byPly": {
      "15": {
        "glyph": "?!",
        "note": "inaccuracy: 5.3 win% given up, eval -0.09 after. The engine wanted the line in the sibling branch.",
        "line": "b0b4 b7b5 e2e1 b5a5 b4b9 c7b9 a2b2 b9c7 c2b4 h6g6 h0h9 g7h9 e1c1 a5f5 c0e2 h9g7 g0i2 f5f3 a3a4 c7a8 b4c6 a8b6 c6d4 f3f1 g3g4 g5g4 i2g4 b6a4 b2b9 d9e8 g2h4",
        "lineEval": "⩲"
      }
    }
  }
};

const G_M_118072: XiangqiReplaySpec = {
  "iccs": "b2e2 b9c7 c3c4 a9b9 b0c2 g6g5 a0b0 h9g7 b0b6 i9i8 h2g2 i8f8 h0i2 g7h5 c2d4 f8f6 i0i1 g9e7 i1d1 b7b8 d4c6 b8g8 b6b9 c7b9 d1d4 b9c7 i3i4 f6f3 d4e4 g5g4 e4g4 g8c8 c6d4 f3e3 g2g1 c7d5 c0a2 h5f4 c4c5 e3d3 d4f5 f4e2 g0e2 d5c3 e2c0 d9e8 i2h4 e6e5 h4g6 c3b1 c0e2 d3d0 e0e1 b1d2 a2c4 d0e0 e1f1 h7f7 f5e7 c9e7 g6e7 c8c4 g1g2 e5e4 g4g6 e0e2 g2d2 e4f4 e7f5 f4f3",
  "red": "Cheng Yin Lung",
  "black": "Tony Fung Ga Zen",
  "event": "2022 World Xiangqi Championship, round 8",
  "resultText": "0-1",
  "annotations": {
    "byPly": {
      "29": {
        "glyph": "?!",
        "note": "inaccuracy: 9.7 win% given up, eval -1.30 after. The engine wanted the line in the sibling branch.",
        "line": "e2c2 f3e3 f0e1 h5g3 d4h4 h7f7 i2g3 e3g3 g0e2 g8b8 g2i2 g3i3 i2f2 i3c3 c6b4 c7b5 c4c5 c3c5 f2i2 e7g9 c2b2 d9e8 b2b5 c5b5 b4d3 b5b3 h4d4 f7d7 d3f4 b3i3 i2g2 c9e7",
        "lineEval": "="
      },
      "30": {
        "glyph": "?",
        "note": "mistake: 10.8 win% given up, eval -0.10 after. The engine wanted the line in the sibling branch.",
        "line": "g8g3 i2g3 f3g3 g2h2 h7h2 e4h4 h2h3 h4h5 h3e3 e2i2 e3e4 h5h2 g5g4 i2i6 d9e8 h2f2 g3e3 d0e1 e3c3 e1d0 e8f7 g0i2 c3h3 i6i9 f9e8 i4i5 h3e3 d0e1 e3c3 e1d0 g4g3 f2h2",
        "lineEval": "∓"
      },
      "35": {
        "glyph": "?",
        "note": "mistake: 14.8 win% given up, eval -1.84 after. The engine wanted the line in the sibling branch.",
        "line": "d4f5 e3e5 f5h6 d9e8 g4g7 h7h8 i2h4 e5d5 d0e1 h5f4 h6g8 c8g8 g7g8 h8h5 g8g4 f4g2 h4g2 d5d3 c4c5 a6a5 g2i3 d3c3 e1d0 c3c5 i4i5 h5g5 e2h2 i6i5 h2h9 g5g9 g0e2 c7d9",
        "lineEval": "="
      },
      "38": {
        "glyph": "?",
        "note": "mistake: 14.2 win% given up, eval -0.07 after. The engine wanted the line in the sibling branch.",
        "line": "c8b8 c4c5 d5f4 c5b5 d9e8 i2h4 b8b7 g1h1 f4d3 d0e1 e3e5 d4f3 h5f4 h4g6 e5b5 g6f4 d3e5 f4e6 e5g4 g3g4 b5f5 f3d4 f5e5 h1h6 a6a5 g4g5 e5e4 g5f5",
        "lineEval": "∓"
      },
      "45": {
        "glyph": "?!",
        "note": "inaccuracy: 5.7 win% given up, eval -0.34 after. The engine wanted the line in the sibling branch.",
        "line": "a2c0 d9e8 i2h4 e7c5 g1i1 c3d1 d0e1 c8c0 g4c4 c0a0 i1d1 d3d1 c4c5 h7b7 c5b5 b7h7 b5b7 d1c1 e1d2 h7d7 h4g6 c1c5 f5h6 c5c0 e0e1 c0c6 h6g8 e9d9 g3g4 d7d6 g6f8",
        "lineEval": "="
      },
      "49": {
        "glyph": "??",
        "note": "blunder: 23.6 win% given up, eval -2.49 after. The engine wanted the line in the sibling branch.",
        "line": "g1i1 d3d2 d0e1 d2d6 e1f2 h7h5 c5d5 c3d5 g4d4 c8c7 c0e2 c7d7 a2c0 e8f7 f0e1 f9e8 i1f1 e7g5 f5e3 e5e4 d4e4 d5e3 e4e3 d7b7 e3b3 b7d7 b3c3 c9e7 g3g4 g5i7 c3e3 h5b5",
        "lineEval": "="
      },
      "55": {
        "glyph": "?!",
        "note": "inaccuracy: 7.2 win% given up, eval -3.75 after. The engine wanted the line in the sibling branch.",
        "line": "g4d4 e8d7 g1g0 d0f0 d4d2 f0f5 d2d6 e5e4 g0b0 e4e3 a2c4 f5c5 b0b9 c9a7 g6e7 h7f7 e7d9 e9d9 d6d7 d9e9 d7f7 e3d3 f7d7 d3c3 d7a7 c8e8 e2c0 c5c4 b9b2 c4e4 e1f1 e8e7",
        "lineEval": "∓"
      },
      "56": {
        "glyph": "?!",
        "note": "inaccuracy: 6.1 win% given up, eval -2.82 after. The engine wanted the line in the sibling branch.",
        "line": "h7h1 g1g0 d0f0 g4d4 d2b3 d4d8 e8d7 d8c8 b3d4 g0g2 d4f3 g2f2 f0f2 f5h4 f3d4 g6e5 f9e8 e1e0 e9f9 e5f3 d4f3 h4f3 f2f3 c8c6 e7c5 c6g6",
        "lineEval": "−+"
      },
      "61": {
        "glyph": "??",
        "note": "blunder: 21.8 win% given up, eval -9.15 after. The engine wanted the line in the sibling branch.",
        "line": "g1g0 e5e4 g0e0 e4f4 f1e1 f4g4 g6e7 e8d7 g3g4 d2b3 e0d0 c8c7 e7d5 c7c4 c5c6 c4e4 e2c0 b3d2 c6d6 f9e8 d5f6 d2f3 e1d1 e4d4 d0d4 f3d4 g4g5 e9d9 f6h5 d4b5 d6c6 f7f2",
        "lineEval": "∓"
      }
    }
  }
};

export const tonyFungGaZenArticle: Article = {
  slug: "tony-fung-ga-zen",
  homeRow: "deep-dives",
  kind: 'article',
  publisher: 'mistboard',
  boardFamily: 'xiangqi',
  title: "Tony Fung 冯家俊",
  seoTitle: "Tony Fung 冯家俊, Hong Kong's world championship finalist: games and analysis",
  summary: "Hong Kong's 2022 world championship finalist, with nine points from ten in this year's qualifier for China's top league. His last fourteen months and the 2022 run, five games on the board, 47 games analysed.",
  showSummaryOnPage: false,
  status: "published",
  publishedAt: "2026-10-03",
  updatedAt: "2026-10-03",
  thumbnail: {
    kind: 'image',
    src: "/article-thumbs/tony-fung-2023-face.jpg",
    alt: "Tony Fung in a white Hong Kong team shirt.",
  },
  audience: "English-speaking xiangqi players, and Hong Kong players who follow him through the Hong Kong association and the local sports press.",
  readNext: ["lai-ly-huynh","cao-yanlei"],
  intro: [
    {
      kind: 'image-figure',
      src: "/article-thumbs/tony-fung-2023.jpg",
      alt: "Tony Fung in a white Hong Kong team shirt, one hand resting on the edge of a xiangqi board, smiling at the camera.",
      caption: "Tony Fung in September 2023, before the Asian Games. Photo: Mr.C / Sportsoho.",
    },
    {
      kind: 'paragraph',
      text: "Tony Fung 冯家俊 is a world championship finalist for Hong Kong. In 2022 he went through eight rounds of the World Xiangqi Championship with one loss and reached the final, and second place equalled Hong Kong's best result at the event. In August 2026 he scored nine points out of ten in the qualifier for China's top league, four wins and a draw, the best individual score there, shared with Cao Yanlei.",
    },
    {
      kind: 'paragraph',
      text: "He was born in 1998 and has played for Hong Kong since he was 18. At the 2023 Asian Games in Hangzhou he was in the team that won bronze in the mixed team event, Hong Kong's first xiangqi medal at the Games. In April 2025 he won the Hong Kong Open for the first time, beating Cheng Yin Lung in the final. The WXF lists him as an International Master, and Hong Kong's own association lists him among its Hong Kong Grandmasters.",
    },
    {
      kind: 'paragraph',
      text: "This page is his last fourteen months and the 2022 run to the final, with five of his games on the board. I ran the 47 games we hold through the same engine analysis Mistboard gives your own games.",
    },
  ],
  sections: [
    {
      heading: "How he plays",
      blocks: [
        {
          kind: 'paragraph',
          text: "**He is hardest to beat with red.** Since July 2025 he has lost two of his twenty-one red games, both on one day of an open qualifier in Shanghai.",
        },
        {
          kind: 'paragraph',
          text: "**He has no single opening.** His 25 red games here start four different ways, with the central cannon, the Palcorner Cannon, a horse or a soldier, and each of them comes up at least five times.",
        },
        {
          kind: 'paragraph',
          text: "**He plays the long game.** Talking to Sportsoho in 2023, he said that neither he nor his senior Wong Hok Him is the kind of player who goes for the kill from the opening; both like to draw a game out and keep the threat hidden, a needle in the cotton. His longest win here ran 81 moves.",
        },
      ],
    },
    {
      heading: "Asian Individual Championship, Manila",
      blocks: [
        {
          kind: 'paragraph',
          text: "He is in Manila this week for the [21st Asian Individual Championship](/broadcast/xiangqi/2026-asian-individual-men), which runs to 8 October. His games there will be added to this page when it ends.",
        },
      ],
    },
    {
      heading: "China league qualifier, Hangzhou",
      blocks: [
        {
          kind: 'paragraph',
          text: "Teams outside China's top league play a qualifier to get in. Hong Kong sent a team to Hangzhou from 17 to 19 August, and Fung played all five rounds. He won four and drew the other, on the first day. Zhejiang Mintai and Cao Yanlei's Shanghai Jiahong went through.",
        },
        {
          kind: 'table',
          headers: ["Round","Opponent","Colour","Result"],
          rows: [["1","Wang Dayu","Red","Win"],["2","Zheng Yichen","Red","Draw"],["3","Lu Hao","Red","Win"],["4","Liu Zehao","Black","Win"],["5","Zhang Rui","Black","Win"]],
          compact: true,
          caption: "His league qualifier, round by round.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_142503, startPly: 26, perspective: 'red' },
          caption: "Tony Fung Ga Zen vs Wang Dayu, 2026 China league qualifier, round 1, 17 August 2026. Fung won with red in 28 moves. The board opens after black's move 13, with Fung to move.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_142542, startPly: 32, perspective: 'red' },
          caption: "Tony Fung Ga Zen vs Lu Hao, 2026 China league qualifier, round 3, 18 August 2026. Fung won with red in 40 moves. The board opens after black's move 16, with Fung to move.",
        },
        {
          kind: 'paragraph',
          text: "Cao Yanlei, who shared the top score and took Shanghai Jiahong into the league, has [his own page](/blog/cao-yanlei). The [qualifier](/broadcast/xiangqi/2026-league-qualifier) is in the broadcast archive.",
        },
      ],
    },
    {
      heading: "Five Rams Cup, Guangzhou",
      blocks: [
        {
          kind: 'paragraph',
          text: "The Five Rams Cup in Guangzhou (五羊杯) invites China's national champions and runs a qualifying group for players from Hong Kong, Macau and Taiwan. Fung won it in January. He beat Chao Yi-fan of Chinese Taipei with a win and a draw, then drew two slow games with his Hong Kong teammate Wong Hok Him and went through when Wong ran out of time in the rapid playoff.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_140266, startPly: 79, perspective: 'black' },
          caption: "Chao Yi-fan vs Tony Fung Ga Zen, 2026 Five Rams Cup, Hong Kong, Macau and Taiwan qualifier, 29 January 2026. Fung won with black in 81 moves. The board opens after red's move 40, with Fung to move.",
        },
        {
          kind: 'paragraph',
          text: "In the final stage in February he drew with black against China's Meng Fanrui, whom he had also held to a draw at the world championship in Shanghai. Wang Yubo then beat him twice, and the cup went to Cheng Yudong. The [whole event](/broadcast/xiangqi/2026-wuyang-cup) is in the broadcast archive.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_140287, startPly: 23, perspective: 'black' },
          caption: "Meng Fanrui vs Tony Fung Ga Zen, 2026 Five Rams Cup, final stage, 25 February 2026. Drawn in 28 moves. The board opens after red's move 12, with Fung to move.",
        },
      ],
    },
    {
      heading: "Every event since July 2025",
      blocks: [
        {
          kind: 'paragraph',
          text: "At the 2025 World Championship in Shanghai he finished eighth. The table has every event since July 2025 for which we hold his full record.",
        },
        {
          kind: 'table',
          headers: ["Event","Dates","W","D","L"],
          rows: [["Shanghai Cup","Sep 9, 2026","0","1","1"],["League qualifier, Hangzhou","Aug 17–19, 2026","4","1","0"],["World Championship, Shanghai","Sep 22–27, 2025","4","4","1"],["National Games, mass-participation final, Shenzhen","Sep 5–7, 2025","1","4","0"],["Shanghai Cup, open qualifier","Aug 9–10, 2025","1","0","4"],["League qualifier","Jul 30–Aug 2, 2025","3","4","0"]],
          highlightRows: [1],
          compact: true,
          caption: "The Five Rams Cup and the September 2025 World Rapid Open are left out: some of his games there are missing from our sources.",
        },
      ],
    },
    {
      heading: "2022 World Championship, Kuching",
      blocks: [
        {
          kind: 'paragraph',
          text: "The championship ran in Kuching, in Sarawak, from 24 to 28 October 2022, eight rounds and then a final between the top two. Fung won five, drew two and lost one, and finished level with Vietnam's Nguyễn Thành Bảo on 12 points, ahead on tiebreak. He lost the final to China's Wang Tianyi. Second place equalled Hong Kong's best result at a world championship, Wong Hok Him's in 2019.",
        },
        {
          kind: 'paragraph',
          text: "The win that put him in the final came in round eight, with black, against Cheng Yin Lung, his Hong Kong teammate and the man he would beat again in the Hong Kong Open final two and a half years later.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_M_118072, startPly: 49, perspective: 'black' },
          caption: "Cheng Yin Lung vs Tony Fung Ga Zen, 2022 World Xiangqi Championship, round 8, 27 October 2022. Fung won with black in 35 moves. The board opens after red's move 25, with Fung to move.",
        },
        {
          kind: 'paragraph',
          text: "Lại Lý Huynh, who won the title in 2025 and has [his own page](/blog/lai-ly-huynh), drew with Fung in round six, and again at the Asian Games a year later.",
        },
      ],
    },
    {
      heading: "All 47 games",
      blocks: [
        {
          kind: 'paragraph',
          text: "Every game on this page is in a Mistboard study with the engine's judgments and lines, and 10 of them are in the broadcast archive with the site's analysis.",
        },
        {
          kind: 'paragraph',
          text: "Sources: game records from dpxq.com, which may not hold every game of an event; the 2022 results from the Chinese Xiangqi Association's report on Sina and from China News Service; the Five Rams Cup qualifier from Yangcheng Evening News; the Asian Games from Sing Tao; the Hong Kong Open from HK01 and Sportsroad; analysis by Pikafish through Mistboard's review pipeline, October 2026.",
        },
        {
          kind: 'cta',
          buttons: [{"label":"Open the study","href":"/study/3ii1g3EK","emphasis":"primary"},{"label":"His games in the archive","href":"/players/tony-fung-ga-zen","emphasis":"secondary"}],
          layout: "single-row",
        },
      ],
    },
  ],
};
