import type { Article } from '../types.js';
import type { XiangqiReplaySpec } from '../../xiangqi-replay.js';

// Player page, draft. Prose from docs-private/players/yin-sheng/draft.md (draft
// 2, 2026-09-20); facts and their sources in facts.md beside it. The five specs
// were generated by scripts/annotated-game-to-spec.mjs from 10M-node runs of
// scripts/annotate-game.mjs over dpxq records m_143859, m_143732, m_143688,
// m_143740, m_142516. Baked, not fetched: the page must not depend on the
// study still existing. Regenerate the specs, never hand-edit a mainline.

const G_STAGE_ONE: XiangqiReplaySpec = {
  "iccs": "b0c2 c6c5 b2a2 b9c7 a0b0 a9b9 b0b4 h9g7 h0g2 h7h5 g3g4 g9e7 g0e2 c7b5 b4f4 b5c3 a2a6 b7c7 a6c6 b9b6 c6c3 c7c3 f4d4 f9e8 c2e1 e6e5 g2f4 h5f5 h2h5 g6g5 g4g5 e7g5 h5f5 g7f5 d4d5 g5e7 e1g2 f5h6 d5e5 h6f7 e5f5 i9g9 f0e1 c3b3 f5d5 f7g5 g2h4 b6h6 f4g2 g5h3 i0g0 c5c4 h4f5 g9g5 e3e4 c4c3 d5d6 h6h9 e4e5 b3b2 f5e3 g5e5 e3g4 e5g5 g2e3 h3f4 e3c4 f4d3 c4b6 h9h8 b6c8 e9f9 e1d2 h8f8 g0h0 f8f3 d6d4 e7g9 i3i4 g5g7 c8d6 b2b0 d6b5 g7e7 h0h2 f3f0 e0e1 e7f7 h2h1 b0b1 g4e5 c3c2 b5c3 f7f5",
  "red": "Chen Hongsheng",
  "black": "Yin Sheng",
  "event": "2026 象甲 league, stage one",
  "resultText": "0-1",
  "annotations": {
    "byPly": {
      "30": {
        "glyph": "?!",
        "note": "inaccuracy: 5.8 win% given up, eval -0.11 after. The engine wanted the line in the sibling branch.",
        "line": "i9h9 i0h0 c3i3 f4g2 i3a3 h5e5 h9h0 g2h0 a3a7 h0g2 b6e6 e5e4 e6c6 e1g0 f5i5 g0f2 g6g5 g4g5 g7e6 d4d1 i5i0 e2g0 e6g5",
        "lineEval": "⩱"
      },
      "47": {
        "glyph": "??",
        "note": "blunder: 20.0 win% given up, eval -2.39 after. The engine wanted the line in the sibling branch.",
        "line": "i0f0 b3b0 a3a4 b6b4 d5d6 b4a4 g2h4 g9f9 f4g2 f9h9 h4f5 b0a0 d6b6 i6i5 f5d6 a4d4 b6a6 a0b0 a6b6 b0a0 f0f4 d4f4 d6c8 e9f9 g2f4 h9h0 e1f0",
        "lineEval": "="
      },
      "49": {
        "glyph": "?!",
        "note": "inaccuracy: 6.3 win% given up, eval -3.33 after. The engine wanted the line in the sibling branch.",
        "line": "h4i2 g5f3 d5h5 h6h5 f4h5 g9g2 h5f6 e8f7 e2g0 d9e8 i0h0 c5c4 a3a4 c4c3 i3i4 b3e3 e0f0 c3c2 h0h9 e7g9 g0e2 c9e7 i2h0 g2g1",
        "lineEval": "∓"
      },
      "60": {
        "glyph": "?!",
        "note": "inaccuracy: 7.7 win% given up, eval -2.41 after. The engine wanted the line in the sibling branch.",
        "line": "h9g9 d6c6 g5g2 g0g2 g9g2 c6c3 h3g1 e0f0 b3b1 f5h6 e8d7 e5e6 g2g6 h6g4 g6e6 c3b3 b1d1 b3d3 d1b1 d3g3 e6d6 g3b3 b1c1 b3g3 e7g5 g3g2 d7e8 g2h2",
        "lineEval": "−+"
      },
      "62": {
        "glyph": "?!",
        "note": "inaccuracy: 8.9 win% given up, eval -1.08 after. The engine wanted the line in the sibling branch.",
        "line": "g5g3 d6b6 c3b3 b6d6 h9f9 e5f5 b3c3 f5f6 c3d3 d6d3 b2g2 d3d4 g2g1 e3d5 f9h9 f6e6 g3g9 d5f6 g1g7 d4d3 g7f7 g0g9 e7g9 d3g3 g9i7 f6e4 f7f9 i3i4",
        "lineEval": "∓"
      },
      "70": {
        "glyph": "?!",
        "note": "inaccuracy: 5.4 win% given up, eval +0.02 after. The engine wanted the line in the sibling branch.",
        "line": "g5f5 g0f0 f5f0 e0f0 h9h0 f0f1 e8f7 d6h6 b2b1 e1d2 h0h6 g4h6 c3c2 b6c4 b1b8 f1e1 e9f9 h6g4 b8d8 c4e5 d3f4 e5c4 c2c1 c4b2 d8e8 e1e0 c1c0 b2c0 f4e2 d0e1 e2g1 e0f0",
        "lineEval": "⩱"
      },
      "73": {
        "glyph": "??",
        "note": "blunder: 20.2 win% given up, eval -2.52 after. The engine wanted the line in the sibling branch.",
        "line": "g0f0 h8f8 f0f8 f9f8 d6f6 e8f7 c8d6 d9e8 d6e4 g5h5 e4c3 d3c1 e0f0 h5h0 f0f1 h0h3 f6b6 b2b3 b6c6 h3f3 e1f2 f3g3 f1f0 f8f9 c3d1 b3f3 f0e0 g3h3",
        "lineEval": "="
      },
      "74": {
        "glyph": "?",
        "note": "mistake: 14.9 win% given up, eval -0.74 after. The engine wanted the line in the sibling branch.",
        "line": "g5f5 d6b6 c3c2 g4e3 f5f3 b6d6 b2b3 d6d3 b3e3 d0e1 c2d2 e0d0 d2c2 c0a2 h8h3 e2c0 c2c1 d3c3 c1b1 c3d3 h3i3 d3d1 e3e5 d1b1 e8f7 g0f0 f3d3 b1d1 d9e8 d1d3 i3d3 e1d2",
        "lineEval": "−+"
      },
      "77": {
        "glyph": "??",
        "note": "blunder: 25.5 win% given up, eval -3.71 after. The engine wanted the line in the sibling branch.",
        "line": "h0h6 f3f0 e0e1 g5g7 d6f6 f0f6 h6f6 e8f7 c8d6 b2b0 d6e4 c3c2 f6d6 d3f4 d6b6 b0a0 b6f6 f4g2 f6f2 g2i1 e1e0 i1h3 f2f1 f9f8 f1h1 h3f4 h1a1 a0b0 a1b1 b0a0 b1b0 a0a1",
        "lineEval": "⩱"
      },
      "80": {
        "glyph": "?!",
        "note": "inaccuracy: 7.7 win% given up, eval -3.20 after. The engine wanted the line in the sibling branch.",
        "line": "b2b0 i4i5 i6i5 a3a4 c9e7 d4b4 c3c2 b4b0 g5g4 d0e1 c2d2 e1d2 g4c4 c8e7 d3f2 e0d0 c4c2 b0b1 c2d2 b1d1",
        "lineEval": "−+"
      },
      "83": {
        "glyph": "??",
        "note": "blunder: 20.9 win% given up, eval -11.73 after. The engine wanted the line in the sibling branch.",
        "line": "h0h5 f3f0 e0e1 f0f1 e1e0 g7e7 d4e4 c3c2 e4e7 c2d2 h5f5 f1f5 d6f5 g9e7 e0e1 d2c2 e1e0 d3c1 e0f0 c1e2 f0f1 b0b8",
        "lineEval": "−+"
      }
    }
  },
  "perspective": "black"
};
const G_MENG: XiangqiReplaySpec = {
  "iccs": "h2d2 h9g7 h0g2 i9h9 g3g4 h7i7 c0e2 b7d7 b2b1 b9c7 a0a2 h9h5 i0h0 h5b5 d2b2 b5f5 b2d2 c6c5 a2b2 c7d5 b1d1 d5c3 d1d7 i7d7 h0h6 c9e7 b2b3 d7c7 b0a2 c3d5 h6g6 d9e8 e3e4 a9c9 d0e1 f5h5 a3a4 i6i5 b3d3 c7d7 g4g5 d7d3 g5h5 d3b3 g6g7 c5c4 g7g6 c4c3 g6e6 b3a3 d2d0 c3c2 e6d6 d5b4 a2b0 c9c3 d6b6 b4d3 b0a2 d3c1 a2c1 c2c1 d0a0 c1d1 b6b0 a3b3 a0a6 e9d9 a6d6 b3b2 e1d2",
  "red": "Yin Sheng",
  "black": "Meng Fanrui",
  "event": "2026 Shanghai Cup",
  "resultText": "1-0",
  "annotations": {
    "byPly": {
      "39": {
        "glyph": "!",
        "note": "Great: the only move that punishes the error before it, and every alternative is at least a mistake worse."
      },
      "36": {
        "glyph": "?",
        "note": "mistake: 13.0 win% given up, eval +2.51 after. The engine wanted the line in the sibling branch.",
        "line": "g9i7 a3a4 e7g9 g6g7 d5e7 g4g5 f5f1 d2d1 c7g7 d1f1 g7g2 f1f2 c5c4 g5f5 c4d4 f5f6 c9c5 b3g3 g2h2 f6e6 e7c6 g3e3 d4e4 e3e4 h2h7 e6d6 c6d8 a2b4 a6a5 d6d7 d8b7 b4d3",
        "lineEval": "⩲"
      },
      "37": {
        "glyph": "??",
        "note": "blunder: 19.0 win% given up, eval +0.28 after. The engine wanted the line in the sibling branch.",
        "line": "b3d3 c7d7 g4g5 h5g5 g6g5 e7g5 d3d5 d7d2 d5d2 c9b9 a2c3 b9b3 c3d5 b3g3 g2e3 g3i3 d2b2 i3f3 a3a4 e8d9 b2b6 g5e7 b6a6 i6i5 a4a5 i5i4 a5b5 i4h4 a6a5 h4g4 b5c5 g4f4",
        "lineEval": "+−"
      },
      "38": {
        "glyph": "??",
        "note": "blunder: 21.0 win% given up, eval +2.78 after. The engine wanted the line in the sibling branch.",
        "line": "h5h7 e4e5 c7c6 g6g7 h7g7 e5d5 g7f7 d5d6 c6c7 d6e6 c7d7 d2c2 d7c7 c2b2 c7d7 e6d6 d7d9 b2c2 c9a9 e2c0 a6a5 a4a5 f7f6 b3b6 a9a5 d6e6 f6f3 e6e7 g9e7 b6e6 f3g3 e6e7",
        "lineEval": "⩲"
      },
      "63": {
        "glyph": "?!",
        "note": "inaccuracy: 5.4 win% given up, eval +2.71 after. The engine wanted the line in the sibling branch.",
        "line": "d0d6 c1d1 b6b0 c3c6 d6d5 c6c5 e4e5 e8d9 g2e3 a3i3 e2c4 i3i4 b0b1 i4e4 g0e2 d1c1 b1b2 f9e8 b2d2 e4a4 c4a2 a4e4 e3c4 e4h4 e1d0 h4e4 f0e1",
        "lineEval": "+−"
      },
      "66": {
        "glyph": "?!",
        "note": "inaccuracy: 5.5 win% given up, eval +3.72 after. The engine wanted the line in the sibling branch.",
        "line": "a6a5 e4e5 e7c9 a4a5 g9e7 h5i5 a3a4 a0a2 c3c2 a2a3 c2c3 a3a2 e8d9 a2d2 a4d4 g2h4 c3c1 h4f5 f9e8 d2d3 d4e4 d3e3 e4a4 e5e6",
        "lineEval": "+−"
      }
    }
  }
};
const G_JIN: XiangqiReplaySpec = {
  "iccs": "c3c4 b7c7 h2e2 g9e7 b0a2 b9a7 a0b0 a9a8 h0g2 a8f8 e2e6 f9e8 e6a6 c6c5 c4c5 f8f5 i0h0 f5c5 g0e2 h9f8 b2b6 i6i5 b0b4 c5a5 b4a4 a5b5 b6d6 b5d5 d6b6 i9f9 h0h4 f8h9 a2c3 d5d3 c3b5 f9f5 b5d6 f5d5 f0e1 h9i7 d6f7 e8f7 h4h7 f7e8 h7h4 d5c5 b6f6 c5f5 f6e6 d3d6 e6e4 i7h5 g3g4 c7c2 g4g5 g6g5 h4h5 c2g2 a4a5 f5f9 h5g5 g2i2 g5g0 d6h6 e1f0 i2f2 d0e1 f2f1 g0g1 h6e6 g1h1 f1f7 h1h5 f7g7 h5e5 f9f1 e2g4 g7h7 e5h5 h7f7 h5h3 f7f9 g4e2 f9g9 e4g4 f1f4 g4g8 e6c6 c0a2 i5i4 i3i4 f4i4 g8h8 g9h9 h8g8 h9f9 g8g4 c6e6 a2c0 i4i1 h3f3 i1h1 g4i4 h1i1 i4h4 i1h1 h4i4 h1i1 i4h4 i1h1 h4i4 f9g9 f3g3 g9g5 i4c4 h1h5 e1d0 h5h4 c4c1 h4f4 c1a1 g5c5 a5a4 f4a4 a3a4 c5c3 e3e4 e6e4 a1e1 e4a4 a6e6 a4f4 g3c3 e9f9 e1c1 f4f0 e0e1 a7b5 c3d3 f0f6 e6e5 f6f5 e5e4 f5f4 e4c4 c9a7 d3h3 b5d6 c4c3 e7g9 h3h9 d6f7 e1e0 f4f3 c3c4 e8d7 c4i4 f3i3 c1f1 f9e9 f1e1 d9e8 i4i9 e9d9 h9g9 d9d8 e1d1 i3d3 i9i8 e8f9 g9f9 f7h6 f9f8 d8d9 d1g1",
  "red": "Yin Sheng",
  "black": "Jin Bo",
  "event": "2026 Shanghai Cup",
  "resultText": "1-0",
  "annotations": {
    "byPly": {
      "59": {
        "glyph": "!!",
        "note": "Brilliant: a piece (chariot) offered and not recovered, worth 9, confirmed along the engine's own line."
      },
      "32": {
        "glyph": "?!",
        "note": "inaccuracy: 8.9 win% given up, eval +1.07 after. The engine wanted the line in the sibling branch.",
        "line": "d5b5 b6d6 b5b6 d6d2 a7c6 a6c6 b6c6 a4f4 f8e6 f4f9 e8f9 a3a4 e6c5 f0e1 c5b3 h4b4 b3d2 e1d2 c6f6 d0e1 f6f3 a2c3 c7d7 a4a5 f3g3 b4g4 g3g4 e2g4 d7d3 a5b5 d9e8",
        "lineEval": "="
      },
      "66": {
        "glyph": "?!",
        "note": "inaccuracy: 6.5 win% given up, eval +0.97 after. The engine wanted the line in the sibling branch.",
        "line": "f9f3 g0g9 f3f9 g9f9 e9f9 e2g0 i2i0 c0e2 h6f6 d0e1 i0i1 a3a4 i1i0 e4d4 f9e9 d4c4 i0i1 c4e4 e9f9 e4d4 f9e9 d4c4 i1i0 c4c1 f6g6",
        "lineEval": "="
      },
      "110": {
        "glyph": "??",
        "note": "blunder: 46.6 win% given up, eval #1 after. The engine wanted the line in the sibling branch.",
        "line": "i1i4 a5a4 e6h6 h4e4 i4i5 e4g4 i5g5 g4i4 g5i5 i4e4 i5g5 f3f8 h6e6 e4i4 g5i5 i4g4 i5g5 e3e4 f9i9 f8i8 i9f9 i8h8 f9g9 g4i4 e6i6 i4h4 g9f9 h8f8",
        "lineEval": "⩲"
      },
      "111": {
        "glyph": "??",
        "note": "blunder: 47.0 win% given up, eval +0.32 after. The engine wanted the line in the sibling branch.",
        "line": "h4i4",
        "lineEval": "+−"
      },
      "126": {
        "glyph": "?!",
        "note": "inaccuracy: 5.7 win% given up, eval +0.81 after. The engine wanted the line in the sibling branch.",
        "line": "c5g5 g3h3 g5g9 d0e1 a7b9 e1d2 b9c7 a6a9 c7d5 a4a5 e6e3 h3h9 g9f9 a1e1 e3d3 h9h5 d3d2 h5e5 d2d4 a5a6 f9f4 a6a7 d5b4 e5e7 b4c2 e7e8 e9f9",
        "lineEval": "⩲"
      },
      "128": {
        "glyph": "?!",
        "note": "inaccuracy: 5.8 win% given up, eval +1.32 after. The engine wanted the line in the sibling branch.",
        "line": "c3c1 g3e3 e6b6 e3h3 b6e6 h3h4 c1i1 a4a5 i1i0 h4h0 i0i6 a1e1 i6a6 e4e5 e6f6 a5a6 f6a6 e5e6 a7c8 h0h3 a6c6 h3h8 c6b6 e6e7 c9e7 e2c4 b6f6 h8h9 f6f9",
        "lineEval": "⩲"
      }
    }
  }
};
const G_FINAL: XiangqiReplaySpec = {
  "iccs": "c3c4 b7c7 h2e2 c9e7 d0e1 h9g7 h0g2 i9h9 i0h0 g6g5 h0h4 b9d8 b2d2 a9b9 b0a2 b9b3 a0b0 b3b0 a2b0 h7i7 h4f4 d9e8 b0c2 h9h3 d2d3 h3h5 c2d4 d8b7 d4c6 b7a5 c6a5 a6a5 c0a2 c7a7 f4d4 a7a3 c4c5 g5g4 d4g4 g7f5 e2e6 h5h6 e6e5 h6d6 d3d2 a5a4 g4a4 a3g3 g0e2 i7g7 a4g4 g9i7 d2d5 d6e6 e3e4 i7g5 g4f4 g3h3 g2h0 h3h5 d5f5 e6f6 f4f3 f6f5 f3b3 e9d9 b3b9 d9d8 b9b6 g5i7 c5d5 h5e5 e4e5 f5f3 b6i6 i7g9 i6g6 g7h7 h0g2 h7h2 a2c0 d8d9 g6h6 h2i2 e2g0 f3g3 g0i2 g3g2 h6h3 g2i2 h3e3",
  "red": "Yin Sheng",
  "black": "Chen Shaobo",
  "event": "2026 Shanghai Cup, final",
  "resultText": "1-0",
  "annotations": {
    "byPly": {
      "44": {
        "glyph": "?",
        "note": "mistake: 14.1 win% given up, eval +1.90 after. The engine wanted the line in the sibling branch.",
        "line": "f5e3 g2e3 a3e3 e0d0 e3i3 d3d2 h6h5 e5e2 h5e5 c5d5 e5e3 a2c0 i3i0 d0e0 i6i5 d5d6 i7h7 g4b4 e7c9 b4c4 c9e7 d2d5 h7g7 d5g5 e9d9 e2d2 e3d3 g5g4 d9e9 d2e2 e9d9 c4b4",
        "lineEval": "⩲"
      },
      "46": {
        "glyph": "?!",
        "note": "inaccuracy: 7.5 win% given up, eval +3.03 after. The engine wanted the line in the sibling branch.",
        "line": "d6d3 g4f4 f5g7 f4b4 g7e6 b4b9 e8d9 b9b6 i7i8 e5e7 e6f4 e7e5 f4g2 g0e2 g2i1 b6e6 i8e8 d2b2 a3b3 b2b1 d3e3 b1i1 e3e2 e0d0 e2e3 i1g1 g9i7 e1d2 e3g3",
        "lineEval": "±"
      },
      "50": {
        "glyph": "?!",
        "note": "inaccuracy: 5.7 win% given up, eval +4.02 after. The engine wanted the line in the sibling branch.",
        "line": "i7h7 d2b2 d6d9 a4f4 f5h6 b2b6 g3g7 b6i6 g9i7 f4f6 h6g4 e2g4 g7g2 g4e2 g2a2 e1d2 a2a3 f6h6 a3a7 h6b6 d9d3 f0e1 a7b7 b6e6 h7h2",
        "lineEval": "+−"
      },
      "51": {
        "glyph": "?!",
        "note": "inaccuracy: 6.2 win% given up, eval +3.02 after. The engine wanted the line in the sibling branch.",
        "line": "d2b2 d6d9 a4f4 f5h6 f4f6 h6i8 f6i6 d9c9 c5c6 c9b9 c6b6 b9a9 i6i8 a9a2 b2d2 a2a5 e5e4 g7g2 d2g2 g3h3 e1d0 e9d9 g2g1",
        "lineEval": "+−"
      },
      "61": {
        "glyph": "?!",
        "note": "inaccuracy: 6.0 win% given up, eval +2.64 after. The engine wanted the line in the sibling branch.",
        "line": "i3i4 g7f7 f4g4 f5g7 e5h5 g7h5 d5h5 e6h6 h5h4 f7g7 g4f4 g7h7 h4h7 h6h7 h0f1 e7c5 e4e5 h7i7 f1e3 i6i5 f4f5 i5i4 f5g5 c5a7 e3d5 i7b7 g5g3 b7d7 g3f3",
        "lineEval": "+−"
      },
      "63": {
        "glyph": "?!",
        "note": "inaccuracy: 6.5 win% given up, eval +1.84 after. The engine wanted the line in the sibling branch.",
        "line": "e5g5 f6f5 f4f5 h5f5 g5h5 g7h7 h0f1 e7c5 h5c5 f5f8 f1e3 e8f7 e0d0 f9e8 e3g4 e9f9 e4e5 h7i7 e2g0 f8h8 e1f2 h8h4 g4h6 i7i3 c5c6 h4d4 h6g8 d4d6 d0e0",
        "lineEval": "+−"
      },
      "72": {
        "glyph": "?!",
        "note": "inaccuracy: 9.4 win% given up, eval +2.47 after. The engine wanted the line in the sibling branch.",
        "line": "f5f4 b6d6 e8d7 d6g6 g7f7 d5d6 f4e4 e5d5 e4e2 g6g8 d8d9 g8f8 f7h7 f8f9 d9d8 h0f1 h5g5 e0d0 g5g0 d0d1 d8e8 f1g3 e2e3 g3h5 e3d3 e1d2 i7g5 d5e5 e8d8 f9f6 d7e8 f0e1",
        "lineEval": "±"
      }
    }
  }
};
const G_QUALIFIER: XiangqiReplaySpec = {
  "iccs": "h2e2 h9g7 c3c4 b7c7 b0c2 c9e7 h0g2 c6c5 i0h0 i9h9 h0h4 h7i7 h4f4 h9h5 c2b4 c7c9 e2c2 d9e8 c0e2 c9d9 d0e1 b9d8 g3g4 a6a5 f4f8 c5c4 e2c4 g6g5 f8g8 g7f5 g4g5 h5g5 g8g5 e7g5 g0e2 g5e7 c2c3 i6i5 a0a1 a9a7 b4c6 d8c6 c3c6 a7b7 b2d2 d9a9 e3e4 b7b6 c6c8 f5d6 c8a8 d6e4 a1c1 e6e5 c1c2 e4c5 a8c8 a9a3 c2a2 a5a4 d2d4 b6b3 g2h4 i7i3 h4f5 e7g5 d4g4 g9e7 c8c6 e8f7 c6h6 f9e8 h6h4 i3i4 h4h2 i4i2 a2a0 i5i4 a0d0 i4h4 g4g0 h4h3 h2f2 i2i0 f5g7 h3h2 f2f6 h2g2 f6g6 g5i7 e2g4 g2g1 g6g1 b3g3 g7f5 g3g1 c4e2 g1f1 f5e3 f1f3 e3c4 a3e3 c4e3 f3e3 d0d6 c5b3 e0d0 b3c1 e1d2 e3d3 d6d3 c1d3 g0h0 i0f0 h0h4 f0f4 h4h1 f4d4",
  "red": "Zhang Rui",
  "black": "Yin Sheng",
  "event": "2026 象甲 qualifier, Hangzhou",
  "resultText": "0-1",
  "annotations": {
    "byPly": {
      "25": {
        "glyph": "?!",
        "note": "inaccuracy: 5.5 win% given up, eval -0.20 after. The engine wanted the line in the sibling branch.",
        "line": "a0c0 c5c4 f4c4 g6g5 g2f4 i7i8 g4g5 h5g5 c2d2 d9d2 e1d2 e8d9 d2e1 a5a4 a3a4 a9a4 c4d4 f9e8 c0c8 e8d7 c8c3 d7e8 f4d5 g7f5 d4h4",
        "lineEval": "⩲"
      },
      "41": {
        "glyph": "??",
        "note": "blunder: 16.2 win% given up, eval -2.49 after. The engine wanted the line in the sibling branch.",
        "line": "c3c0 i7g7 a1b1 g7g3 c4a2 a7c7 b2c2 d9b9 b4c6 c7b7 b1b7 d8b7 a2c4 g3a3 c2a2 a3c3 a2c2 c3c6 c2c6 b9b8 c6a6 a5a4 c0c3 a4b4",
        "lineEval": "⩱"
      },
      "47": {
        "glyph": "?!",
        "note": "inaccuracy: 6.2 win% given up, eval -3.36 after. The engine wanted the line in the sibling branch.",
        "line": "a1c1 a9a3 c1c3 a3a0 c3a3 b7b0 e1d0 f5d4 c6a6 a0d0 f0e1 d0d1 e1d0 d4f3 a3a1 f3g1 e0e1 b0b6 a1d1 b6a6 d1b1 e6e5 b1b9 e8d9 b9b5 i7h7 g2h4 a6h6 d2d1 g1h3 h4f5 h6h5",
        "lineEval": "∓"
      },
      "74": {
        "glyph": "?!",
        "note": "inaccuracy: 6.5 win% given up, eval -3.74 after. The engine wanted the line in the sibling branch.",
        "line": "a4b4 g4d4 b4c4 h4c4 i3i0 e2g0 b3c3 d4d6 i0i4 g0e2 i4e4 a2a0 a3a4 d6c6 c3f3 f5g7 f3e3 a0a2 e3b3 a2a0 b3b2 e0d0 b2e2 a0b0 a4b4 b0a0 b4b9 c4a4 c5a4 a0a4 e2b2 a4e4",
        "lineEval": "−+"
      },
      "75": {
        "glyph": "?!",
        "note": "inaccuracy: 6.1 win% given up, eval -4.93 after. The engine wanted the line in the sibling branch.",
        "line": "g4i4 i5i4 h4h5 b3b0 e1d0 c5e4 f0e1 b0b6 f5e3 g5i7 h5h2 e4g5 e2g4 b6b3 e3d5 e7c5 h2g2 b3g3 g2c2 g3d3 d5c7 c5e7 c2e2 a3b3 e2c2 b3b0 c2c0 d3d7 c7a8 d7b7 a2a4",
        "lineEval": "−+"
      }
    }
  },
  "perspective": "black"
};

export const yinShengArticle: Article = {
  slug: 'yin-sheng',
  kind: 'article',
  publisher: 'mistboard',
  boardFamily: 'xiangqi',
  title: 'Yin Sheng 尹昇',
  seoTitle: 'Yin Sheng 尹昇: games, results, and analysis',
  summary:
    '31 games without a loss, August 17 to September 16, 2026, across the 象甲 qualifier, the Shanghai Cup and the first league stage. How he plays, five games on the board, all 31 analysed.',
  showSummaryOnPage: false,
  status: 'draft',
  audience:
    'English-speaking xiangqi players who have never had a way to follow the Chinese pro circuit.',
  intro: [
    {
      kind: 'paragraph',
      text: '**Yin Sheng 尹昇** · Zhejiang Mintai Bank 浙江民泰银行象棋队 · 全国大师, national master, 2023 · born 2005, Wenling, Zhejiang',
    },
    {
      kind: 'paragraph',
      text: 'League debut at fifteen, the master title in 2023. At twenty he lost the World Championship final in Shanghai to Lại Lý Huynh of Vietnam, the first non-Chinese champion in nineteen editions, and got called 千古罪人 for it online. Then this.',
    },
  ],
  sections: [
    {
      heading: "The number",
      blocks: [
        {
          kind: 'paragraph',
          text: "**31 games without a loss, August 17 to September 16, 2026.** Eleven wins, twenty draws, three events. Every game went through the same engine analysis Mistboard runs on your games: accuracy between 89 and 100, median 98, and at no move in any of the 31 did the engine put his winning chances under 44 percent.",
        },
        {
          kind: 'paragraph',
          text: "He was rated 2454 on the last official list, September 2023, 78th in China. Every rated opponent in the run stood above him on that list: Meng Fanrui 2567, Cao Yanlei 2551, Xu Wenzhang 2546, Chen Hongsheng 2517, Huang Guangying 2501, He Wenzhe 2471, Jin Bo 2467. Chen Shaobo, who he beat in the final, was too young to be on it.",
        },
      ],
    },
    {
      heading: "How he plays",
      blocks: [
        {
          kind: 'paragraph',
          text: "**With red, he opens with the pawn.** Ten of his fifteen red games start 兵七进一 or 兵三进一, the 仙人指路 systems, four more with 飞相, one with 过宫炮. Not a single central cannon all month. He is not trying to win the opening; he is trying to get a middlegame.",
        },
        {
          kind: 'paragraph',
          text: "**With black, he is nearly unmarkable.** Median accuracy 98.6 as black against 95.6 as red. One mistake in sixteen games as black. All four of his blunders came with red, three of them in games he won anyway: he errs when he is pressing, not when he is holding.",
        },
        {
          kind: 'paragraph',
          text: "**His draws are short and his wins are long.** Half the draws were over inside thirty moves; the median win took fifty-two. In nine of the eleven wins the other side made the first real mistake and the rest was conversion. The other two he ground out against opponents the engine never faulted, 52 and 84 moves of small edges.",
        },
        {
          kind: 'paragraph',
          text: "**Seventeen of the 31 games have nothing for the engine to mark on his side.** Not a brilliancy style. The engine found three `!!` and three `!` in the whole month, and one missed mate in one. What it mostly found was a player who does not give anything back.",
        },
      ],
    },
    {
      heading: "象甲 league, stage one · Hangzhou, September 14 to 16 · 3W 6D 0L",
      blocks: [
        {
          kind: 'paragraph',
          text: "The messy one. Against Chen Hongsheng, as black, the engine counts four blunders for red and one real mistake for Yin, and the evaluation swings both ways for twenty moves before red's 39th and 42nd hand it over. On the page because the paragraph above would give you the wrong idea of what these games look like from inside.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_STAGE_ONE },
          caption: "Chen Hongsheng vs Yin Sheng, 15 September 2026. The fight is moves 24 to 42.",
        },
        {
          kind: 'cta',
          buttons: [{ label: "Stage one in the archive", href: "/broadcast/xiangqi/2026-xiangqi-league", emphasis: 'secondary' }],
        },
      ],
    },
    {
      heading: "Shanghai Cup · September 9 to 13 · winner · 6W 11D 0L",
      blocks: [
        {
          kind: 'paragraph',
          text: "Seven games against Meng Fanrui: six draws, one of them 162 moves, and this one. Move 19 is a pair of edge-pawn pushes, both wrong, Meng's more so, and 20.车八平六 is the only move that punishes it.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_MENG },
          caption: "Yin Sheng vs Meng Fanrui, 11 September 2026. Watch move 19 for both sides, and 20 for red.",
        },
        {
          kind: 'paragraph',
          text: "Against Jin Bo, 88 moves. At move 30 he leaves a chariot where it can be taken and the engine agrees it should be left there. After black's 55th there is a mate in one on the board; he plays a cannon move instead and wins 32 moves later. Stop the board at move 55 and find it.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_JIN },
          caption: "Yin Sheng vs Jin Bo, 12 September 2026. The mate is on the board after black's 55th.",
        },
        {
          kind: 'paragraph',
          text: "The final against Chen Shaobo went four games, three draws and this one. Chen's 22nd move gives up 14 points of winning chances, and Yin plays the rest at 95 percent. No killing move. He just doesn't give any of it back.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_FINAL },
          caption: "Yin Sheng vs Chen Shaobo, 13 September 2026, the final. The engine's quibbles with red are three small ones, moves 26, 31 and 32.",
        },
        {
          kind: 'cta',
          buttons: [{ label: "The Shanghai Cup in the archive", href: "/broadcast/xiangqi/2026-shanghai-cup", emphasis: 'secondary' }],
        },
      ],
    },
    {
      heading: "象甲 qualifier · Hangzhou, August 17 to 19 · 2W 3D 0L",
      blocks: [
        {
          kind: 'paragraph',
          text: "Day one, black against Zhang Rui of Tianjin. Zhang's knight jump on move 21 is the one error the engine finds, and Yin needs 38 more moves to turn it into a win. This is the shape of most of them.",
        },
        {
          kind: 'xq-replay',
          spec: { ...G_QUALIFIER },
          caption: "Zhang Rui vs Yin Sheng, 17 August 2026. Move 21 is where it goes wrong for red.",
        },
        {
          kind: 'cta',
          buttons: [{ label: "The qualifier in the archive", href: "/broadcast/xiangqi/2026-league-qualifier", emphasis: 'secondary' }],
        },
      ],
    },
    {
      heading: "What's next",
      blocks: [
        {
          kind: 'paragraph',
          text: "The league's second stage is in October. The national individual championship is November 21 to 29 in Changchun; in 2023, on getting the master title, he said he'd give himself five years to a result there.",
        },
      ],
    },
    {
      heading: "All games",
      blocks: [
        {
          kind: 'paragraph',
          text: "All 31, with the engine's judgments and lines, in [the study](/study/VSX0aLce); the three events in the archive. Games from dpxq.com; analysis by Pikafish through Mistboard's review pipeline, September 2026.",
        },
        {
          kind: 'cta',
          buttons: [{ label: "The archive", href: "/broadcast/xiangqi", emphasis: 'secondary' }],
        },
      ],
    },
  ],
};
