// Bakes apps/server/src/cxa-listed-players.ts: every player on a CXA list the
// web app bundles (2026 points, 2019-2023 等级分; apps/web/src/players/), in
// the archive's spelling, with the list's group. The server lists these
// players (#458), a page for each even with no game in the archive, and the
// server cannot import web code, so the names cross as a baked module. The
// lists themselves stay single-sourced in the web app.
//
// Re-run after any module in apps/web/src/players/ changes a name:
//   npm run bake:cxa-players --workspace @mistboard/server
// apps/web/src/players/cxa-coverage.test.ts fails when the bake is stale.

import { promises as fs } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const coveragePath = resolve(here, '..', '..', '..', 'web', 'src', 'players', 'cxa-coverage.ts');

// A runtime path, so tsc does not follow it into the web package; tsx
// transpiles the TypeScript module when the script runs.
const coverage = (await import(pathToFileURL(coveragePath).href)) as {
  cxaListedPlayers: () => { name: string; group: 'men' | 'women' }[];
};
const players = coverage.cxaListedPlayers();

const lines = [
  '// Generated by src/scripts/bake-cxa-listed-players.ts from the CXA lists in',
  '// apps/web/src/players/ (names in the archive spelling, after its aliases).',
  '// Do not edit by hand; re-run `npm run bake:cxa-players`.',
  '',
  "export type CxaListedPlayer = { name: string; group: 'men' | 'women' };",
  '',
  'export const CXA_LISTED_PLAYERS: readonly CxaListedPlayer[] = [',
  ...players.map((p) => `  { name: '${p.name.replace(/['\\]/g, '\\$&')}', group: '${p.group}' },`),
  '];',
  '',
];

const outPath = resolve(here, '..', 'cxa-listed-players.ts');
await fs.writeFile(outPath, lines.join('\n'));
console.log(`wrote ${outPath} (${players.length} players)`);
