// Generated by docs-private/players/cxa-points.py --bake from the CXA 竞赛积分排名
// posts (tournament points, best events in a rolling window; replaced 等级分 in
// 2026). Men and women only; the youth groups stay in the JSON. Do not edit by hand.

export type CxaPointsList = {
  id: string;
  date: string;
  window: [string, string] | null;
  source: string;
  men: number;
  women: number;
};
export type CxaPointsEntry = {
  list: string;
  group: 'men' | 'women';
  rank: number;
  points: number;
  events: number;
  best: number;
};

export const CXA_POINTS_LISTS: readonly CxaPointsList[] = [
  {
    id: '20251228',
    date: '2025-12-28',
    window: ['2025-04-25', '2025-12-28'],
    source: 'https://mp.weixin.qq.com/s/rSYxYaSpZ8SV5DYJJ74ZaA',
    men: 50,
    women: 50,
  },
];

export const CXA_POINTS: Readonly<Record<string, readonly CxaPointsEntry[]>> = {
  孟繁睿: [{ list: '20251228', group: 'men', rank: 1, points: 3105, events: 5, best: 1500 }],
  孟辰: [{ list: '20251228', group: 'men', rank: 2, points: 2980, events: 5, best: 1500 }],
  曹岩磊: [{ list: '20251228', group: 'men', rank: 3, points: 2765, events: 5, best: 1500 }],
  王禹博: [{ list: '20251228', group: 'men', rank: 4, points: 2415, events: 8, best: 975 }],
  何文哲: [{ list: '20251228', group: 'men', rank: 5, points: 1920, events: 8, best: 975 }],
  黄光颖: [{ list: '20251228', group: 'men', rank: 6, points: 1680, events: 7, best: 500 }],
  刘子健: [{ list: '20251228', group: 'men', rank: 7, points: 1665, events: 9, best: 585 }],
  程宇东: [{ list: '20251228', group: 'men', rank: 8, points: 1430, events: 11, best: 325 }],
  刘柏宏: [{ list: '20251228', group: 'men', rank: 9, points: 1395, events: 6, best: 975 }],
  宿少峰: [{ list: '20251228', group: 'men', rank: 10, points: 1145, events: 7, best: 500 }],
  尹昇: [{ list: '20251228', group: 'men', rank: 11, points: 1130, events: 5, best: 585 }],
  郭凤达: [{ list: '20251228', group: 'men', rank: 12, points: 1075, events: 11, best: 500 }],
  顾博文: [{ list: '20251228', group: 'men', rank: 13, points: 890, events: 7, best: 325 }],
  陈羽琦: [{ list: '20251228', group: 'men', rank: 14, points: 880, events: 4, best: 750 }],
  许国义: [{ list: '20251228', group: 'men', rank: 15, points: 787, events: 5, best: 650 }],
  杨世哲: [{ list: '20251228', group: 'men', rank: 16, points: 755, events: 8, best: 160 }],
  蒋明成: [{ list: '20251228', group: 'men', rank: 17, points: 710, events: 10, best: 220 }],
  李翰林: [{ list: '20251228', group: 'men', rank: 18, points: 605, events: 8, best: 135 }],
  赵攀伟: [{ list: '20251228', group: 'men', rank: 19, points: 605, events: 4, best: 390 }],
  王昊: [{ list: '20251228', group: 'men', rank: 20, points: 420, events: 7, best: 135 }],
  莫梓健: [{ list: '20251228', group: 'men', rank: 21, points: 390, events: 5, best: 220 }],
  杜晨昊: [{ list: '20251228', group: 'men', rank: 22, points: 388, events: 8, best: 195 }],
  华辰昊: [{ list: '20251228', group: 'men', rank: 23, points: 380, events: 5, best: 220 }],
  王家瑞: [{ list: '20251228', group: 'men', rank: 24, points: 376, events: 6, best: 160 }],
  吴魏: [{ list: '20251228', group: 'men', rank: 25, points: 345, events: 6, best: 110 }],
  茹一淳: [{ list: '20251228', group: 'men', rank: 26, points: 327, events: 10, best: 65 }],
  李成蹊: [{ list: '20251228', group: 'men', rank: 27, points: 315, events: 8, best: 110 }],
  黄文俊: [{ list: '20251228', group: 'men', rank: 28, points: 315, events: 2, best: 295 }],
  王宇航: [{ list: '20251228', group: 'men', rank: 29, points: 310, events: 5, best: 160 }],
  万科: [{ list: '20251228', group: 'men', rank: 30, points: 305, events: 7, best: 110 }],
  王天琛: [{ list: '20251228', group: 'men', rank: 31, points: 295, events: 7, best: 110 }],
  刘明: [{ list: '20251228', group: 'men', rank: 32, points: 295, events: 5, best: 135 }],
  陈泓盛: [{ list: '20251228', group: 'men', rank: 33, points: 285, events: 3, best: 135 }],
  张彬: [{ list: '20251228', group: 'men', rank: 34, points: 277, events: 6, best: 135 }],
  刘新奥: [{ list: '20251228', group: 'men', rank: 35, points: 268, events: 7, best: 80 }],
  刘奕达: [{ list: '20251228', group: 'men', rank: 36, points: 245, events: 3, best: 135 }],
  许文章: [{ list: '20251228', group: 'men', rank: 37, points: 227, events: 4, best: 90 }],
  申嘉伟: [{ list: '20251228', group: 'men', rank: 38, points: 225, events: 5, best: 100 }],
  吕钦: [{ list: '20251228', group: 'men', rank: 39, points: 220, events: 1, best: 220 }],
  柳大华: [{ list: '20251228', group: 'men', rank: 39, points: 220, events: 1, best: 220 }],
  苏奕霖: [{ list: '20251228', group: 'men', rank: 41, points: 215, events: 7, best: 45 }],
  李学淏: [{ list: '20251228', group: 'men', rank: 42, points: 200, events: 6, best: 45 }],
  张学潮: [{ list: '20251228', group: 'men', rank: 43, points: 200, events: 4, best: 90 }],
  万川: [{ list: '20251228', group: 'men', rank: 44, points: 183, events: 6, best: 65 }],
  袁玮浩: [{ list: '20251228', group: 'men', rank: 45, points: 177, events: 4, best: 110 }],
  蒋融冰: [{ list: '20251228', group: 'men', rank: 46, points: 170, events: 5, best: 65 }],
  陈绍博: [{ list: '20251228', group: 'men', rank: 47, points: 170, events: 4, best: 65 }],
  马惠城: [{ list: '20251228', group: 'men', rank: 48, points: 165, events: 2, best: 135 }],
  梁辉远: [{ list: '20251228', group: 'men', rank: 49, points: 155, events: 3, best: 110 }],
  于幼华: [{ list: '20251228', group: 'men', rank: 50, points: 145, events: 3, best: 65 }],
  李沁: [{ list: '20251228', group: 'women', rank: 1, points: 2775, events: 6, best: 1500 }],
  唐丹: [{ list: '20251228', group: 'women', rank: 2, points: 1597, events: 3, best: 1500 }],
  沈思凡: [{ list: '20251228', group: 'women', rank: 3, points: 1382, events: 5, best: 500 }],
  胡家艺: [{ list: '20251228', group: 'women', rank: 4, points: 1370, events: 7, best: 975 }],
  王文君: [{ list: '20251228', group: 'women', rank: 5, points: 1300, events: 10, best: 585 }],
  时凤兰: [{ list: '20251228', group: 'women', rank: 6, points: 1270, events: 7, best: 750 }],
  粱妍婷: [{ list: '20251228', group: 'women', rank: 7, points: 1198, events: 4, best: 750 }],
  黃蕾蕾: [{ list: '20251228', group: 'women', rank: 8, points: 975, events: 6, best: 490 }],
  王琳娜: [{ list: '20251228', group: 'women', rank: 9, points: 585, events: 1, best: 585 }],
  唐思楠: [{ list: '20251228', group: 'women', rank: 10, points: 557, events: 8, best: 160 }],
  董毓男: [{ list: '20251228', group: 'women', rank: 11, points: 540, events: 4, best: 325 }],
  王子涵: [{ list: '20251228', group: 'women', rank: 12, points: 532, events: 6, best: 220 }],
  吴可欣: [{ list: '20251228', group: 'women', rank: 13, points: 405, events: 4, best: 295 }],
  刘钰: [{ list: '20251228', group: 'women', rank: 14, points: 385, events: 3, best: 295 }],
  左文静: [{ list: '20251228', group: 'women', rank: 15, points: 350, events: 2, best: 320 }],
  张婷婷: [{ list: '20251228', group: 'women', rank: 16, points: 285, events: 3, best: 110 }],
  宇诗琪: [{ list: '20251228', group: 'women', rank: 17, points: 245, events: 3, best: 135 }],
  董嘉琦: [{ list: '20251228', group: 'women', rank: 18, points: 235, events: 3, best: 220 }],
  陈幸琳: [{ list: '20251228', group: 'women', rank: 19, points: 220, events: 1, best: 220 }],
  张含莹: [{ list: '20251228', group: 'women', rank: 20, points: 215, events: 2, best: 135 }],
  吳荣萱: [{ list: '20251228', group: 'women', rank: 21, points: 210, events: 3, best: 110 }],
  郞褀琪: [{ list: '20251228', group: 'women', rank: 22, points: 170, events: 2, best: 135 }],
  周博靓: [{ list: '20251228', group: 'women', rank: 23, points: 165, events: 3, best: 65 }],
  朱兰婷: [{ list: '20251228', group: 'women', rank: 23, points: 165, events: 3, best: 65 }],
  林嘉欣: [{ list: '20251228', group: 'women', rank: 25, points: 165, events: 2, best: 100 }],
  周珈亦: [{ list: '20251228', group: 'women', rank: 26, points: 160, events: 4, best: 65 }],
  陈丽淳: [{ list: '20251228', group: 'women', rank: 27, points: 160, events: 1, best: 160 }],
  周雨霏: [{ list: '20251228', group: 'women', rank: 28, points: 145, events: 5, best: 65 }],
  张婷: [{ list: '20251228', group: 'women', rank: 29, points: 145, events: 3, best: 65 }],
  彭诗文: [{ list: '20251228', group: 'women', rank: 30, points: 135, events: 3, best: 65 }],
  何媛: [{ list: '20251228', group: 'women', rank: 31, points: 135, events: 1, best: 135 }],
  吴嘉倩: [{ list: '20251228', group: 'women', rank: 32, points: 130, events: 3, best: 65 }],
  区泳茵: [{ list: '20251228', group: 'women', rank: 33, points: 130, events: 2, best: 65 }],
  张佳雯: [{ list: '20251228', group: 'women', rank: 34, points: 115, events: 3, best: 65 }],
  吴欣语: [{ list: '20251228', group: 'women', rank: 35, points: 111, events: 4, best: 65 }],
  李越川: [{ list: '20251228', group: 'women', rank: 36, points: 110, events: 2, best: 65 }],
  胡雯銥: [{ list: '20251228', group: 'women', rank: 37, points: 101, events: 3, best: 65 }],
  朱乐儿: [{ list: '20251228', group: 'women', rank: 38, points: 100, events: 2, best: 65 }],
  罗婧涵: [{ list: '20251228', group: 'women', rank: 38, points: 100, events: 2, best: 65 }],
  玉思源: [{ list: '20251228', group: 'women', rank: 38, points: 100, events: 2, best: 65 }],
  衣璐璐: [{ list: '20251228', group: 'women', rank: 41, points: 70, events: 3, best: 30 }],
  刘校汝: [{ list: '20251228', group: 'women', rank: 42, points: 65, events: 1, best: 65 }],
  兰林依: [{ list: '20251228', group: 'women', rank: 42, points: 65, events: 1, best: 65 }],
  张曼纯: [{ list: '20251228', group: 'women', rank: 42, points: 65, events: 1, best: 65 }],
  楚逸凝: [{ list: '20251228', group: 'women', rank: 45, points: 50, events: 2, best: 35 }],
  刘若萱: [{ list: '20251228', group: 'women', rank: 45, points: 50, events: 2, best: 35 }],
  罗昀曦: [{ list: '20251228', group: 'women', rank: 47, points: 47, events: 3, best: 35 }],
  励娴: [{ list: '20251228', group: 'women', rank: 48, points: 45, events: 1, best: 45 }],
  桂丹: [{ list: '20251228', group: 'women', rank: 48, points: 45, events: 1, best: 45 }],
  张红萍: [{ list: '20251228', group: 'women', rank: 50, points: 40, events: 1, best: 40 }],
};
